### ISSUE TITLE
Foreign Policy

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#100]
### Example:star::star: :
https://foreignpolicy-com.proxy.library.emory.edu/

embeds.foreignpolicy.com
foreignpolicy.com
fpgroup.foreignpolicy.com
www.foreignpolicy.com

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello.

Need to add stanza to ezProxy: https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/Foreign_Policy

**Comment by lisahamlett** [comment]
ARTICLE, HTML
https://foreignpolicy.com:443/2018/08/09/ecuadors-all-seeing-eye-is-made-in-china/
https://foreignpolicy.com:443/2018/08/08/china-is-cheating-at-a-rigged-game/
https://foreignpolicy.com:443/2018/08/06/u-s-turns-up-heat-on-irans-economy-adding-fuel-to-massive-protests-sanctions-jcpoa/

TOC, HTML
https://foreignpolicy.com:443/author/charles-rollet/
https://foreignpolicy.com:443/author/keith-johnson/
https://foreignpolicy.com:443/channel/news/
https://foreignpolicy.com:443/channel/analysis/
https://foreignpolicy.com:443/channel/features/
https://foreignpolicy.com:443/channel/the-magazine/
https://foreignpolicy.com:443/channel/economics/
https://foreignpolicy.com:443/print-archive/

LOG:
[foreignpolicy.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2275900/foreignpolicy.txt)

**Comment by lisahamlett** [comment]
This subscription seems to be inactive.  I will check in with ECR to verify it is active before we parse it.

**Comment by lisahamlett** [comment]
> Hi Lisa,
> 
> I am also unable to access with the proxy URL. We did pay for this in February, so I am contacting the vendor about this. Thanks for reporting.
> 
> Kayleah Farist
> Library Specialist, Sr.
> Electronic and Continuing Resources Team

**Comment by lisahamlett** [comment]
SEARCH;MISC
https://foreignpolicy.com:443/channel/news/
https://foreignpolicy.com:443/category/elephants-in-the-room/
https://foreignpolicy.com:443/staff/
https://foreignpolicy.com:443/podcasts/and-now-the-hard-part

ARTICLE;HTML
https://foreignpolicy.com:443/2019/07/20/space-research-can-save-the-planet-again-climate-change-environment/
https://foreignpolicy.com:443/2019/07/12/document-of-the-week-is-the-u-n-revisiting-the-ban-on-big-tobacco/?_ga=2.253152393.162079277.1569943157-788119408.1569943157

BIO;HTML
https://foreignpolicy.com:443/author/robbie-gramer/?_ga=2.256846859.162079277.1569943157-788119408.1569943157
https://foreignpolicy.com:443/author/colum-lynch/

AUDIO;MISC
https://foreignpolicy.com:443/podcasts/and-now-the-hard-part/resetting-the-u-s-relationship-with-saudi-arabia/
https://foreignpolicy.com:443/podcasts/first-person/roots-of-a-quagmire/

[foreignpolicy_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3677180/foreignpolicy_log.txt)
