### ISSUE TITLE
InCites

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#101]
### Example:star::star: :

incites.thomsonreuters.com

### Priority: 
High

### Subscriber (Library): 
Shared

**Comment by eipeele** [comment]
I cannot find anything related to thomson reuters.  If there is no stanza for them, then this may be more work.

**Comment by AGCooper** [comment]
https://www.oclc.org/support/services/ezproxy/documentation/db/webofknowledge.en.html

Seems to have some references to thomsonreuters.

**Comment by AGCooper** [comment]
HJ https://incites.thomsonreuters.com is part of web of science. However the web page references Clarivate Analytics. And then there is thomsonreuters ... Don't know which it is.

**Comment by AGCooper** [comment]
I'll email ECR about this. incites only throws error messages.

**Comment by AGCooper** [comment]
From Jessie Copeland: "Thanks Alex.  We’re having an invoice issue with them, but it should be resolved soon."

**Comment by lisahamlett** [comment]
Thomson Reuters is part of Web of Science, but it needs to be added, as it is not parsing.  I will update WOS and close this issue.
