### ISSUE TITLE
CQ Press Library

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#102]
### Example:star::star: :

library.cqpress.com

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

Also, CQPress is a division of SAGE.

**Comment by lisahamlett** [comment]
[CQ Press Links with Rtype.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1725261/CQ.Press.Links.with.Rtype.txt)
