### ISSUE TITLE
Library PressDisplay by PressReader

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#103]
### Example:star::star: :
http://library.pressdisplay.com.proxy.library.emory.edu

images2.pressdisplay.com
library.pressdisplay.com
pressdisplay.com
www.pressdisplay.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;HTML
http://library.pressdisplay.com:80/pressdisplay/AdvancedSearch.aspx
http://library.pressdisplay.com:80/pressdisplay/AdvancedSimilarSearch.aspx?guid=f00708e1-8f15-4c19-bfb6-c48a98941ed0&title=The%20Reporter%20(Lansdale%2C%20PA)&count=5&text=Biography%20of%20Ida%20B.%20Wells%20coming%20out%20in%202021%2C%20publisher%20says&country=USA

TOC;HTML
http://library.pressdisplay.com:80/pressdisplay/pageview.aspx?cid=34c2&category=Germany%20[country]
http://library.pressdisplay.com:80/pressdisplay/PageViewManager.aspx?cid=0962&category=Croatian%20[language]
http://library.pressdisplay.com:80/pressdisplay/PageViewManager.aspx?cid=9f58&category=T%20[letter]
http://library.pressdisplay.com:80/pressdisplay/Services/ImgGalleryHandler.ashx?type=0&page=1&issue=9f582020042200000000001001

ARTICLE;HTML
http://library.pressdisplay.com:80/pressdisplay/showarticle.aspx?article=ad9b89fd-4649-49ba-927d-dbd2125f5fbc&key=LAcKN4vvFxV9C7aknxiDsg%3d%3d&issue=84222020051600000000001001
http://library.pressdisplay.com:80/pressdisplay/showarticle.aspx?article=f00708e1-8f15-4c19-bfb6-c48a98941ed0&key=XIpmFsJBCLDyW%2fU9BBGn0A%3d%3d&issue=84222020051600000000001001
http://library.pressdisplay.com:80/pressdisplay/pageview.aspx?issue=34c22020051300000000001001
http://library.pressdisplay.com:80/pressdisplay/PageViewManager.aspx?issue=09622020051500000000001001
http://library.pressdisplay.com:80/pressdisplay/PageViewManager.aspx?issue=9f582020042200000000001001
http://library.pressdisplay.com:80/pressdisplay/PageViewManager.aspx?action=showpages&issue=9f582020042200000000001001&page=2&page2=3&cpage=1&cpage2=1
http://library.pressdisplay.com:80/pressdisplay/Services/ImgGalleryHandler.ashx?type=0&page=5&issue=9f582020042200000000001001

[pressdisplay.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4653374/pressdisplay.txt)
