### ISSUE TITLE
Metropolitan Opera

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#104]
### Example:star::star: :
https://www-metopera-org.proxy.library.emory.edu/season/on-demand/

metopera.org
www.metopera.org

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
TOC;HTML
https://www.metopera.org:443/discover/articles/
https://www.metopera.org:443/discover/artists/
https://www.metopera.org:443/discover/education/
https://www.metopera.org:443/discover/education/free-student-streams/home/
https://www.metopera.org:443/discover/education/illustrated-synopses/
https://www.metopera.org:443/discover/education/educator-guides-archive/
https://www.metopera.org:443/discover/education/educational-videos/
https://www.metopera.org:443/discover/education/educator-guides-translated/
https://www.metopera.org:443/discover/video/
https://www.metopera.org:443//discover/podcasts/
https://www.metopera.org:443//discover/synopses/

ARTICLE;HTML
https://www.metopera.org:443/discover/articles/diva-as-diva/

BIO;HTML
https://www.metopera.org:443/discover/artists/baritone-and-bass/ildar-abdrazakov/

REF;HTML
https://www.metopera.org:443/discover/synopses/aida/
https://www.metopera.org:443/discover/education/illustrated-synopses/hansel-and-gretel/
https://www.metopera.org:443/discover/education/educator-guides-archive/aida/

REF;PDF
https://www.metopera.org:443/globalassets/discover/education/educator-guides/hansel-and-gretel/hanselandgretel.07-08.guide.pdf

AUDIO;MISC
https://www.metopera.org:443/discover/artists/aria-code/
https://www.metopera.org:443/discover/education/free-student-streams/audio-clips-hansel-and-gretel/

VIDEO;MISC
https://www.metopera.org:443/season/on-demand/opera/?upc=811357019078
https://www.metopera.org:443/season/on-demand/opera/?upc=811357012062

[metopera.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4653713/metopera.txt)
