### ISSUE TITLE
American Psychological Association (psyctherapy) (Woodruff 3)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#105]
### Example:star::star: :

http://psycnet.apa.org.proxy.library.emory.edu
www.apa.org

### Priority: 
Medium-High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Nothing on ezPAARSE Trello or ang.couperin.org

**Comment by AGCooper** [comment]
~@lisahamlett what about http://ang.couperin.org/platforms/54350cf85189fdbe16d53b74 ?~

That American Psychiatric Association not American Psychological Association

**Comment by lisahamlett** [comment]
~Oops.  https://trello.com/c/d66jMESY/80-american-psychiatric-association-apa~

That American Psychiatric Association not American Psychological Association

**Comment by AGCooper** [comment]
@eipeele Access provided by Ebsco? http://pid.emory.edu/ckbfc

**Comment by eipeele** [comment]
URL for ebook content:  http://psycnet.apa.org.proxy.library.emory.edu

**Comment by lisahamlett** [comment]
ABSTRACT, HTML
http://psycnet.apa.org:80/api/request/abstract.get
http://psycnet.apa.org:80/record/1991-01082-001

TOC, HTML
http://psycnet.apa.org:80/PsycBOOKS/toc/11855
http://psycnet.apa.org:80/PsycBOOKS/toc/15993
http://psycnet.apa.org:80/api/request/browsePB.getBookTOC

SEARCH, HTML
http://psycnet.apa.org:80/api/request/search.results
http://psycnet.apa.org:80/api/request/browsePB.getBooksByTitle

BOOK PART, HTML
http://psycnet.apa.org:80/search/display?id=78828c75-855f-6e08-3b54-0f429d4988f8&recordId=1&tab=all&page=1&display=25&sort=PublicationYearMSSort%20desc,AuthorSort%20asc&sr=1
http://psycnet.apa.org:80/search/display?id=78828c75-855f-6e08-3b54-0f429d4988f8&recordId=2&tab=all&page=1&display=25&sort=PublicationYearMSSort%20desc,AuthorSort%20asc&sr=1

BOOK PART, PDF
http://psycnet.apa.org:80/fulltext/2017-09577-010.pdf?dl=true
http://psycnet.apa.org:80/fulltext/2008-13592-015.pdf?sr=1
http://psycnet.apa.org:80/fulltext/2017-09577-001.pdf
http://psycnet.apa.org:80/fulltext/2008-13592-015.pdf

[PsycNET Log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2578632/PsycNET.Log.txt)
