### ISSUE TITLE
CAS, a division of the American Chemical Society

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#106]
### Example:star::star: :

www.cas.org

https://scifinder-cas-org.proxy.library.emory.edu

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
In list 12 - In "freezer"
https://trello.com/c/kwTPXYAn/246-scifinder-chemical-abstracts-chemabs-cas

http://ang.couperin.org/platforms/5571584be8ce3e33965b39f1

**Comment by AGCooper** [comment]
@eipeele @lisahamlett I could use some help getting urls for the parser.

**Comment by lisahamlett** [comment]
@AGCooper On it.

**Comment by lisahamlett** [comment]
Here are a few weirdnesses with their products:

Science IP does not proxy: https://www.scienceip.org/cgi-bin/scienceip?DO=login_form
Methods Now does not proxy: https://sso.cas.org/as/guMDv/resume/as/authorization.ping

SciFinder proxies but still asks for a login: https://scifinder-cas-org.proxy.library.emory.edu/scifinder/login?TYPE=33554433&REALMOID=06-b7b15cf0-642b-1005-963a-830c809fff21&GUID=&SMAUTHREASON=0&METHOD=GET&SMAGENTNAME=-SM-QD58dixqS9O2WCy355LCpWn%2f5ca1EADjvJZ%2ffuRIN70UvKbjKSrBjIeAJhgSm8b7&TARGET=-SM-http%3a%2f%2fscifinder%2ecas%2eorg%3a443%2fscifinder%2f

NSCI Global proxies but says my computer or IP is not authorized.  I am on the VPN.
https://nciglobal-cas-org.proxy.library.emory.edu/NCI_Global/nci/IPAuth.action

**Comment by lisahamlett** [comment]
[CAS_Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1540298/CAS_Links.txt)
