### ISSUE TITLE
Economist

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#107]
### Example:star::star: :

www.economist.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

### Trello:
https://trello.com/c/Tl5Ofdu9/439-the-economist

### Analysis:
http://ang.couperin.org/platforms/5a0f29b9ab9976bf1f8621bc

**Comment by AGCooper** [comment]
@lisahamlett http://proxy.library.emory.edu/login?url=https://www.economist.com

**Comment by lisahamlett** [comment]
These pages are in the site map, but are not proxied:
https://www.1843magazine.com/
http://www.economistgroup.com/
http://www.economisteducation.com/
http://www.cq.com/
https://www.eurofinance.com/
http://www.theworldin.com/
https://worldinfigures.com/
https://learning.ly/
https://www.corporatenetwork.com/
http://ideaspeoplemedia.com/
https://www.corporatenetwork.com/

http://worldif.economist.com/
http://films.economist.com/
http://radio.economist.com/

links to webinars at http://pages.eiu.com.proxy.library.emory.edu/Webinar-Archive.html

**Comment by lisahamlett** [comment]
[economistdone.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1483829/economistdone.txt)
Here are the links from the log

**Comment by lisahamlett** [comment]
[economistrevisited.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1496724/economistrevisited.txt)
Took a second look.  This is everything relevant.

**Comment by AGCooper** [comment]
Rework the unitid and title_id
