### ISSUE TITLE
Europa World Online (Routledge)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#108]
### Example:star::star: :
www.europaworld.com.proxy.library.emory.edu

www.europaworld.com
europaworld.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
Searches result in duplicates:
10.110.119.198 Lz5gvIT2TmD9gI2 lhamlet [19/May/2020:19:15:17 -0400] "GET http://www.europaworld.com:80/search-results?q=book&search_button=SEARCH&ssid=453663007 HTTP/1.1" 301 379 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.119.198 Lz5gvIT2TmD9gI2 lhamlet [19/May/2020:19:15:24 -0400] "GET https://www.europaworld.com:443/search-results?q=book&search_button=SEARCH&ssid=453663007 HTTP/1.1" 200 81652 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

Or even triples:
10.110.119.198 Lz5gvIT2TmD9gI2 lhamlet [19/May/2020:19:18:50 -0400] "GET https://www.europaworld.com:443/search-results?content_type_cat=i3&q=book&region=&type=&orgs_people_cat= HTTP/1.1" 302 1034 https://www-europaworld-com.proxy.library.emory.edu/search-results?q=book&search_button=SEARCH&ssid=453663007 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.119.198 Lz5gvIT2TmD9gI2 lhamlet [19/May/2020:19:18:50 -0400] "GET http://www.europaworld.com:80/search-results?content_type_cat=i3&q=book&region=&type=&ssid=668831424&orgs_people_cat= HTTP/1.1" 301 409 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.119.198 Lz5gvIT2TmD9gI2 lhamlet [19/May/2020:19:18:51 -0400] "GET https://www.europaworld.com:443/search-results?content_type_cat=i3&q=book&region=&type=&ssid=668831424&orgs_people_cat= HTTP/1.1" 200 26438 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

TOC;HTML
https://www.europaworld.com:443/countries
https://www.europaworld.com:443/regions

ENCYCLOPAEDIA_ENTRY;HTML
https://www.europaworld.com:443/entry/io-un.1943?ssid=668831424&hit=7
https://www.europaworld.com:443/entry/io-un.1893
https://www.europaworld.com:443/entry/kw
https://www.europaworld.com:443/entry/mena
https://www.europaworld.com:443/entry/men.essay.5
https://www.europaworld.com:443/entry/mena.mc
https://www.europaworld.com:443/entry/un_otherorgs.wto.1

[europaworld.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4653793/europaworld.txt)
