### ISSUE TITLE
ICPSR

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#109]
### Example:star::star: :
https://www-icpsr-umich-edu.proxy.library.emory.edu/icpsrweb/

www.icpsr.umich.edu
icpsr.umich.edu
census.icpsr.umich.edu
deposit.icpsr.umich.edu
linkagelibrary.icpsr.umich.edu
pcms.icpsr.umich.edu
radius.icpsr.umich.edu
search.icpsr.umich.edu

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://www.icpsr.umich.edu:443/web/ICPSR/search/studies?q=potato
https://www.icpsr.umich.edu:443/web/civicleads/search/studies?q=book
https://linkagelibrary.icpsr.umich.edu:443/linkagelibrary/search/studies?q=book
https://census.icpsr.umich.edu:443/census/search/studies?q=potato

https://www.icpsr.umich.edu:443/web/ICPSR/search/variables?start=0&EXTERNAL_FLAG=1&ARCHIVE=ICPSR&SERIESFULL_FACET_Q=263%7CMetropolitan%20Travel%20Behavior%20Survey%20Series&sort=VARLABEL_SORT%20asc
https://www.icpsr.umich.edu:443/web/ICPSR/search/publications?start=0&COLLECTION=DATA&ARCHIVE=ICPSR&AUTHORS_FACET=Aarebrot%2C%20Frank&sort=YEAR_PUB_DATE%20desc%2CAUTHORS_SORT%20asc
https://www.icpsr.umich.edu:443/web/ICPSR/browse/facet/variables/studies
https://www.icpsr.umich.edu:443/web/ICPSR/browse/facet/variables/series
https://www.icpsr.umich.edu:443/web/ICPSR/browse/facet/publications/authors
https://www.icpsr.umich.edu:443/web/ICPSR/browse/facet/publications/journals
https://www.icpsr.umich.edu:443/web/ICPSR/browse/facet/publications/studies

https://www-icpsr-umich-edu:443/icpsrweb/AERA/search/publications
https://www-icpsr-umich-edu:443/icpsrweb/AERA/browse/facet/publications/authors
https://www-icpsr-umich-edu:443/icpsrweb/AERA/browse/facet/publications/journals

TOC;HTML
https://www.icpsr.umich.edu:443/web/ICPSR/series/180
https://www.icpsr.umich.edu:443/web/civicleads/series/3
https://www-icpsr-umich-edu:443/icpsrweb/AERA/series/2

ARTICLE;HTML
https://www.icpsr.umich.edu:443/web/ICPSR/studies/2896
https://www.icpsr.umich.edu:443/web/civicleads/studies/7370
https://www-icpsr-umich-edu:443/icpsrweb/AERA/studies/34373
https://linkagelibrary.icpsr.umich.edu:443/linkagelibrary/project/117435/version/V1/view

CITATION;HTML
https://www.icpsr.umich.edu:443/web/ICPSR/studies/2896/publications
https://www.icpsr.umich.edu:443/web/civicleads/studies/7370/publications
https://www-icpsr-umich-edu:443/icpsrweb/AERA/studies/34373/publications

DATASET;HTML
https://pcms.icpsr.umich.edu:443/pcms/reports/studies/2896/utilization
https://pcms-icpsr-umich-edu:443/pcms/reports/studies/7370/utilization

[icpsr.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4653882/icpsr.txt)
