### ISSUE TITLE
International Monetary Fund

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#110]
### Example:star::star: :
https://www-imf-org.proxy.library.emory.edu/external/index.htm

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello

**Comment by lisahamlett** [comment]
SEARCH, HTML
http://www.imf.org:80/external/ns/search.aspx?NewQuery=bananas&submit=
http://www.imf.org:80/en/publications/search?when=After&series=IMF+Working+Papers
http://www.imf.org:80/en/News/Search?Type=Communique
http://www.imf.org:80/en/News/Search?type=News+Article
http://www.imf.org:80/en/Publications/SPROLLs/IMF-Departmental-Papers
http://www.imf.org:80/en/Publications/SPROLLs/Staff-Discussion-Notes

TOC, HTML
http://www.imf.org:80/en/countries
http://www.imf.org:80/en/Countries/PAN
http://www.imf.org:80/en/Countries/ROU

ARTICLE, HTML
http://www.imf.org:80/en/News/Articles/2018/07/27/pr18315-conclusions-of-the-xv-regional-conference-on-central-america-panama-the-dominican-republic
https://www.imf.org:443/en/News/Articles/2018/08/08/na080818-belgium-fsap-cf

ABSTRACT, HTML
http://www.imf.org:80/en/Publications/WP/Issues/2018/08/02/Using-Administrative-Data-to-Enhance-Policymaking-in-Developing-Countries-Tax-Data-and-the-46054
http://www.imf.org:80/en/Publications/WP/Issues/2016/12/30/U-S-16991
https://www.imf.org:443/en/Publications/Departmental-Papers-Policy-Papers/Issues/2018/07/10/Opportunity-for-All-Promoting-Growth-and-Inclusiveness-in-the-Middle-East-and-North-Africa-45981

ARTICLE, PDF
http://www.imf.org:80/External/Pubs/FT/irb/2017/02/index.pdf
http://www.imf.org:80/External/Pubs/FT/irb/2015/04/index.pdf
http://www.imf.org:80/~/media/Files/Publications/CR/2018/cr18171.ashx (this is the PDF downloader even though it doesn't end in .pdf)
http://www.imf.org:80/external/np/res/dfidimf/newsletter/Mar2018.pdf

LOG:
[imf.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2275956/imf.txt)

**Comment by lisahamlett** [comment]
SEARCH;MISC
https://www.imf.org:443/en/search?NewQuery=potatoes
https://www.imf.org:443/en/publications
https://www.imf.org:443/en/publications/search?when=After&series=IMF Working Papers
https://www.imf.org:443/en/Publications/Publications-By-Subject?subject=Financial%20institutions
https://www.imf.org:443/en/countries
https://www.imf.org:443/en/Countries/PAN
https://www.imf.org:443/external/mmedia/view.aspx?st=Categories&variable=Africa&variableId=2
https://www.imf.org:443/en/news/searchnews
https://blogs.imf.org:443/category/government-2/
https://blogs.imf.org:443/category/inclusive-growth/
https://blogs.imf.org:443/?s=brain

ABS;HTML
https://www.imf.org:443/en/Publications/WP/Issues/2019/09/13/Financial-Openness-and-Capital-Inflows-to-Emerging-Markets-In-Search-of-Robust-Evidence-48553
https://www.imf.org:443/en/Publications/CR/Issues/2016/12/31/Panama-Report-on-Observance-of-Standards-and-Codes-FATF-Recommendations-for-Anti-Money-41349
https://www.imf.org:443/en/Publications/GFSR/Issues/2018/09/25/Global-Financial-Stability-Report-October-2018
https://www.imf.org:443/~/media/Files/Publications/GFSR/2018/Oct/CH1/doc/sum1.ashx?la=en
https://www.imf.org:443/en/Publications/Books/Issues/2016/12/31/Measuring-the-Non-Observed-Economy-A-Handbook-31025
https://www.imf.org:443/en/Publications/Annual-Report-on-Exchange-Arrangements-and-Exchange-Restrictions/Issues/2018/08/10/Annual-Report-on-Exchange-Arrangements-and-Exchange-Restrictions-2017-44930

(WP, CR, GFSR, Annual-Report... are publication titles!!!)

BIO;HTML
https://blogs.imf.org:443/bloggers/christine-lagarde/

ARTICLE;HTML
https://www.imf.org:443/en/News/Articles/2018/12/28/pr18499-panama-imf-executive-board-concludes-2018-article-iv-consultation
https://www.imf.org:443/en/News/Articles/2018/10/03/mcs1032018-panama-staff-concluding-statement-of-the-2018-article-iv-mission
https://blogs.imf.org:443/2019/05/03/getting-real-on-meeting-paris-climate-change-commitments/

ARTICLE;PDF
https://www.imf.org:443/~/media/Websites/IMF/imported-full-text-pdf/external/pubs/ft/scr/2008/_cr08201.ashx
https://www.imf.org:443/~/media/Files/Publications/GFSR/2018/Oct/CH1/doc/text.ashx?la=en
https://www.imf.org:443/~/media/Files/Publications/WP/2019/wpiea2019194-print-pdf.ashx

DATASET;MISC
http://data.imf.org:80/?sk=E6A5F467-C14B-4AA8-9F6D-5A09EC4E62A4
http://data.imf.org:80/?sk=E5DCAB7E-A5CA-4892-A6EA-598B5463A34C
http://data.imf.org:80/api/document/download?key=61622605&checkOnly=true

VIDEO;MISC
https://www.imf.org:443/external/mmedia/view.aspx?vid=6085402166001
https://mediacenter.imf.org:443/b-roll/news/imf-world-economic-outlook-update/a/fcefb869-506e-4fd3-854b-e264f5752536
http://mediacenter.imf.org:80/b-roll/all/imf-b-roll/a/89d5796c-40be-47d0-a9fa-df429c912678
http://mediacenter.imf.org:80/press-briefings/all/imf-ecb---jordan---china---venezuela/s/1a779bb9-be5b-4f36-b423-b088e5993b15
http://mediacenter.imf.org:80/annual-and-spring-meetings/all/imf-family-photo-imfc/s/7f7727d5-fddc-45bc-b626-1d027eccbfd8
http://mediacenter.imf.org:80/features/all/imf-lagarde---trade---us-economy/s/c74e8f12-14d5-4cc8-a5bb-e9d9db6b3a55

NOTE
There are PDFs on the old site like this one: https://www.imf.org:443/External/Pubs/FT/irb/2019/SpringSummer/index.pdf but opening them puts multiple entries into the log, so we don't want to parse it

**Comment by lisahamlett** [comment]
Log: [imf.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3617877/imf.txt)

**Comment by lisahamlett** [comment]
Log: [imf.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3617879/imf.txt)
