### ISSUE TITLE
Keesing's

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#111]
### Example:star::star: :
http://www.keesings.com.proxy.library.emory.edu

www.keesings.com
keesings.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
MAIN PAGE -- DO NOT PARSE
http://www.keesings.com:80/index_new.php

SEARCH;HTML
http://www.keesings.com:80/index_new.php?page=advanced-search&search_for=potatoes

ARTICLE;HTML
http://www.keesings.com:80/index_new.php?page=article&article=5289cee0&search=%22germany%22

ARTICLE;PDF
http://www.keesings.com:80/index_new.php?page=download-article&article=5289cee0
http://www.keesings.com:80/index_new.php?page=print-article&article=5289cee0

[keesings.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4689230/keesings.txt)
