### ISSUE TITLE
Latinobarometro Database

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#112]
### Example:star::star: :
www.latinobarometro.org.proxy.library.emory.edu

latinobarometro.com
www.latinobarometro.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
ARTICLE;PDF
http://www.latinobarometro.org:80/latdocs/Annus_Horribilis.pdf
http://www.latinobarometro.org:80/LATDC/DC00638/F00008674-FichasTecnicas_Latinobarometro_2018.pdf
http://www.latinobarometro.org:80/LATDC/DC00592/F00008742-Latinobarometro_2015_Libro_de_codigos_v20190707.pdf
http://www.latinobarometro.org:80/LATDC/DC00326/F00002226-Latinobarometro_Codebook_Guatemala_1996.pdf

DATASET;MISC
http://www.latinobarometro.org:80/LATDC/DC00638/F00008542-Latinobarometro_2018_Eng_Spss_v20190303.zip
http://www.latinobarometro.org:80/LATDC/DC00638/F00008543-Latinobarometro_2018_Eng_Stata_v20190303.zip

Searches and online data analysis are unparseable.

[latinobarometro.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4689306/latinobarometro.txt)
