### ISSUE TITLE
Intellex Past Masters

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#113]
### Example:star::star: :
http://www.library.nlx.com.proxy.library.emory.edu/xtf/search?browse-collections=true

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/55898a4d612f07f5d906940f
Trello: https://trello.com/c/YdGjnXXZ/273-intelex-past-masters-ipm

**Comment by lisahamlett** [comment]
SEARCH, HTML
http://www.library.nlx.com:80/xtf/search?browse-collections=true
http://www.library.nlx.com:80/xtf/search?browse-subjects-list=true
http://www.library.nlx.com:80/xtf/search?browse-languages-list=true
http://www.library.nlx.com:80/xtf/search?keyword=bananas&smode=advanced&brand=default
http://www.library.nlx.com:80/xtf/search?browse-subject-classical=true;brand=default

BOOK PART, HTML
http://www.library.nlx.com:80/xtf/view?docId=fichte_de/fichte_de.00.xml;brand=default
http://www.library.nlx.com:80/xtf/view?docId=fichte_de/fichte_de.01.xml;chunk.id=div.fichte.I.35;toc.depth=1;toc.id=div.fichte.I.35;brand=default
http://www.library.nlx.com:80/xtf/view?docId=chinese1/chinese1.00.xml;brand=default
http://www.library.nlx.com:80/xtf/view?docId=chinese1/chinese1.00.xml;chunk.id=div.ratio.pmpreface.1;toc.depth=2;toc.id=div.ratio.pmpreface.1;hit.rank=0;brand=default
http://www.library.nlx.com:80/xtf/view?docId=kierkegaard_da/kierkegaard_da.00.xml;brand=default
http://www.library.nlx.com:80/xtf/view?docId=kierkegaard_da/kierkegaard_da.06.xml;chunk.id=div.kierk.FB.8;toc.depth=1;toc.id=div.kierk.FB.3;brand=default

LOG:
[intellex.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2279324/intellex.txt)
