### ISSUE TITLE
Medici.tv

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#114]
### Example:star::star: :
https://www-medici-tv.proxy.library.emory.edu

edu.medici.tv
musicwithvision.medici.tv
www.medici.tv
medici.tv

### Priority: 
Woodruff

### Subscriber (Library): 
Low

### ezPAARSE
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
(en|es|ru)
(concerts|operas|ballets|documentaries|masterclasses)


SEARCH;HTML
https://www.medici.tv:443/en/search/?q=swan+lake
https://www.medici.tv:443/en/documentaries/
https://www.medici.tv:443/en/operas/?composer=Richard+Wagner
https://musicwithvision.medici.tv:443/category/playlists/
https://musicwithvision.medici.tv:443/category/community/
https://musicwithvision.medici.tv:443/?s=wagner

VIDEO;MISC
https://www.medici.tv:443/en/ballets/swan-lake-rudolf-nureyev-jose-martinez-agnes-letestu-opera-national-de-paris/

BIO;HTML
https://www.medici.tv:443/en/artists/olivier-messiaen/
https://musicwithvision.medici.tv:443/author/alixmedicitv/

ARTICLE;HTML
https://musicwithvision.medici.tv:443/video-of-the-moment-archives/
https://musicwithvision.medici.tv:443/clef-notes/one-thing-to-listen-for/brahms-violin-concerto/
https://musicwithvision.medici.tv:443/artists/herbert-von-karajan/10-dinner-party-facts-about-about-der-chef-herbert-von-karajan/

[medicitv.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4246989/medicitv.txt)
