### ISSUE TITLE
Now Publishers

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#115]
### Example:star::star: :
https://www-nowpublishers-com.proxy.library.emory.edu/

www.nowpublishers.com
nowpublishers.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://www.nowpublishers.com:443/Search?q=brain&s2=Artificial%20Intelligence%20in%20Robotics

TOC;HTML
https://www.nowpublishers.com:443/Journal
https://www.nowpublishers.com:443/ASTP
https://www.nowpublishers.com:443/ASTP?vol=2
https://www.nowpublishers.com:443/FnTs
https://www.nowpublishers.com:443/DBS
https://www.nowpublishers.com:443/DBS?vol=8
https://www.nowpublishers.com:443/BookSeries/Details/CBSB

ABS;HTML
https://www.nowpublishers.com:443/article/Details/MAL-071
https://www.nowpublishers.com:443/article/BookDetails/9781680834864

ARTICLE;PDF
https://www.nowpublishers.com:443/article/Download/MAL-071
https://www.nowpublishers.com:443/article/DownloadSummary/MAL-071

BOOK;PDF
https://www.nowpublishers.com:443/article/DownloadEBook/9781680834864?format=pdf

BOOK;MISC
https://www.nowpublishers.com:443/article/DownloadEBook/9781680834864?format=epub

[nowpublishers.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4689379/nowpublishers.txt)
