### ISSUE TITLE
Otzar

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#116]
### Example:star::star: :
http://www.otzar.org.proxy.library.emory.edu/

otzar.org
tablet.otzar.org
www.otzar.org

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://tablet.otzar.org:443/pages/search.php?type=nosim&data=%7B%22noseid%22%3A%228%22%2C%22nosedesc%22%3A%22Receipt%22%2C%22sefer%22%3A%22nosim%22%7D

TOC;PDF
http://www.otzar.org:80/booklists/shlomo.PDF
http://www.otzar.org:80/internetsite/18/booklist.pdf

TOC;MISC
http://www.otzar.org:80/booklists/shlomo.xlsx

BOOK_SECTION;HTML
https://tablet.otzar.org:443/book/getimg.php?width=824&book=62722&page=2

[otzar.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4689609/otzar.txt)
