### ISSUE TITLE
Oxford Music Online

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#117]
### Example:star::star: :

www.oxfordmusiconline.com

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/58bd5a17b9f9f3c71b50af77
https://trello.com/c/kaN2F1xo/398-oxford-music-online-omo

**Comment by lisahamlett** [comment]
Domain registered to OXFORD UNIVERSITY PRESS:
http://analogist.couperin.org/platforms/54116a16acd3da4c1bec5684
https://trello.com/c/qMvApJ31/58-oxford-university-press-oup

**Comment by lisahamlett** [comment]
[Oxford Music Online Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1696827/Oxford.Music.Online.Links.txt)

**Comment by lisahamlett** [comment]
[Oxford Music Online Links with Rtype.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1721880/Oxford.Music.Online.Links.with.Rtype.txt)
