### ISSUE TITLE
Oxford Reference

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#118]
### Example:star::star: :

www.oxfordreference.com

### Priority: 

Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
Domain registered to OXFORD UNIVERSITY PRESS:
http://analogist.couperin.org/platforms/54116a16acd3da4c1bec5684
https://trello.com/c/qMvApJ31/58-oxford-university-press-oup

**Comment by lisahamlett** [comment]
[Oxford Reference Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1696788/Oxford.Reference.Links.txt)

**Comment by lisahamlett** [comment]
[Oxford Reference Links with Rtype.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1721863/Oxford.Reference.Links.with.Rtype.txt)
