### ISSUE TITLE
Palgrave

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#119]
### Example:star::star: :

www.palgrave.com
palgrave.nature.com
### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
https://trello.com/c/OPlyvYdd/1-palgrave-journals-springer
http://ang.couperin.org/platforms/53a87b453a6718c446c6fdf4

**Comment by lisahamlett** [comment]
Trello says platform up to day.

**Comment by lisahamlett** [comment]
https://login.proxy.library.emory.edu/login?url=http://www.palgrave.com drops proxy.
This is the only log entry for it: 170.140.213.222 5ge9vGQUTjvubTn lhamlet [01/Aug/2018:16:33:33 -0400] "GET http://www.palgrave.com:80/ HTTP/1.1" 301 0 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

https://login.proxy.library.emory.edu/login?url=http://palgrave.nature.com redirects to http://www.palgrave.com

**Comment by lisahamlett** [comment]
Apparently Palgrave isn't proxied, which is why it doesn't proxy.  I figured that one out all by myself.
I will add the stanza.

**Comment by lisahamlett** [comment]
Title Palgrave Connect (updated 20150513)
URL http://www.palgraveconnect.com/
HJ www.palgraveconnect.com
DJ palgraveconnect.com 

Title Palgrave Journals (updated 20160713)
URL https://www.palgrave.com/gp/journals
HJ https://palgrave.com
HJ https://www.palgrave.com
HJ palgrave-journals.com
HJ palgrave.com
HJ www.palgrave-journals.com
HJ www.palgrave.com
DJ palgrave-journals.com
DJ palgrave.com
NeverProxy static.springer.com

**Comment by lisahamlett** [comment]
https://login.proxy.library.emory.edu/login?url=https://www.palgrave.com
Yup...  Works a lot better when it's set up to proxy...

**Comment by lisahamlett** [comment]
TOC, HTML
https://www.palgrave.com:443/us/campaigns/media-and-marginalisation
https://www.palgrave.com:443/gp/series/14906

REF?, HTML
https://www.palgrave.com:443/us/book/9783319905808
https://www.palgrave.com:443/us/book/9783319933566

ARTICLE, HTML
https://www.nature.com:443/articles/palcomms201640
https://www.nature.com:443/articles/palcomms201611
https://link.springer.com:443/article/10.1057/s41286-017-0031-0?wt_mc=Other.Other.2.CON744.MedMar_1807_CampaignPage_Subjectivity_Hope_s41286-017-0031-0&utm_medium=other&utm_source=other&utm_content=medmar_1807_campaignpage_subjectivity_hope_s41286-017-0031-0&utm_campaign=2_kelechi.jinanwa_medmar_1807_campaignpage_subjectivity_hope_s41286-017-0031-0

ARTICLE, PDF
https://www.nature.com:443/articles/palcomms201640.pdf
https://www.nature.com:443/articles/palcomms201611.pdf

SEARCH, HTML
https://www.palgrave.com:443/us/search?query=sandwich

LOG:
[Palgrave.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2251243/Palgrave.txt)

**Comment by AGCooper** [comment]
www.nature.com should be getting parsed by npg
link.springer.com should be handled by the springer parser
we also have palgrave-journals and palgrave-connect already as parsers

:thinking:

**Comment by eipeele** [comment]
This could be from before nature and palgrave-journals were put in.  If it's parsing from one of those, then it should be working.

**Comment by lisahamlett** [comment]
I guess add the Palgrave links to the other parsers if they aren't already?

**Comment by eipeele** [comment]
These seems to be more for books and the like that aren't being parsed by the other parsers.  Maybe amplify the palgrave-journals parser with these?

**Comment by eipeele** [comment]
@AGCooper Does this need to move to another project in the future?

**Comment by AGCooper** [comment]
@lisahamlett please check nature links against npg and and springer links against springer

**Comment by lisahamlett** [comment]
Nature and Springer work in their own parsers, so we should be good to go on this.
