### ISSUE TITLE
BMJ Journals

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/ezpaarse-platforms#12]
URL: http://journals.bmj.com
Priority: High
Subscriber: Health

**Comment by AGCooper** [comment]
journals.bmj.com is not on the list of unknown domains and can be found in the high wire pkb list: 

"hw/pkb/hw_AllTitles_2016-12-19.txt:http://journals.bmj.com	journals.bmj.com	BMJ Publishing Group Ltd	journals.bmj.com	BMJ Specialist Journals"

**Comment by lisahamlett** [comment]
This is done as part of BMJ Publishing under High Wire, so I am closing this issue.
