### ISSUE TITLE
Statista

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#120]
### Example:star::star: :

www.statista.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
SEARCH, HTML
https://www.statista.com:443/search/?q=nutrition
https://www.statista.com:443/search/?q=computers
https://www.statista.com:443/search/?q=&surveys=1
https://www.statista.com:443/search/?q=+&dossiers=1
https://www.statista.com:443/publication-finder
https://www.statista.com:443/publication-finder?q=books&submit=&yearFrom=2001&yearTo=2018&idBranch=0&docType=0&numPages=0&charsPerPageTo=0&hq=1
https://www.statista.com:443/publication-finder?q=money&submit=&yearFrom=2001&yearTo=2018&idBranch=413&docType=report&numPages=0&charsPerPageTo=0&hq=1

TOC, HTML
https://www.statista.com:443/study/22762/child-health-and-nutrition-statista-dossier/
https://www.statista.com:443/study/11695/us-home-appliance-market-statista-dossier/

TOC?, HTML
https://www.statista.com:443/markets/418/technology-telecommunications/
https://www.statista.com:443/outlook/consumer-markets
https://www.statista.com:443/outlook/consumer-markets/methodology
https://www.statista.com:443/studies-and-reports/
https://www.statista.com:443/surveys
https://www.statista.com:443/chartoftheday/
https://www.statista.com:443/chartoftheday/ALL/p/2/
https://www.statista.com:443/dossiers
https://www.statista.com:443/customercloud/global-consumer-survey

IMAGE, HTML
https://www.statista.com:443/statistics/480418/annual-household-expenditure-on-tablet-computers-canada/
https://www.statista.com:443/statistics/199796/wireless-operating-revenues-of-us-telecommunication-providers/
https://www.statista.com:443/statistics/462357/desktop-browsers-usage-share-in-france/
https://www.statista.com:443/chart/14963/california-wildfires-inflict-structural-damage/
https://www.statista.com:443/chart/14972/study-finds-epa-underestimates-methane-emissions/

Downloads don't seem to have much indicating a specific type.  Maybe you can figure that out better than I could:
ARTICLE, POWERPOINT
https://www.statista.com:443/download/MTUzMzMyMzYwMSMjNTIwMDA1IyMyMjc2MiMjMSMjbnVsbCMjU3R1ZHk=
https://www.statista.com:443/download/MTUzMzMyNDEwNCMjNTIwMDA1IyMxMTY5NSMjMSMjbnVsbCMjU3R1ZHk= 

ARTICLE, PDF
https://www.statista.com:443/download/MTUzMzMyMzYwMSMjNTIwMDA1IyMyMjc2MiMjMSMjcGRmIyNTdHVkeQ==
https://www.statista.com:443/download/MTUzMzMyNDEwNCMjNTIwMDA1IyMxMTY5NSMjMSMjcGRmIyNTdHVkeQ==

IMAGE, PNG
https://www.statista.com:443/download/MTUzMzMyMzc1OCMjNTIwMDA1IyM0ODA0MTgjIzEjI3BuZyMjU3RhdGlzdGlj
https://www.statista.com:443/download/MTUzMzMyNDIwMiMjNTIwMDA1IyM0NjIzNTcjIzEjI3BuZyMjU3RhdGlzdGlj
https://www.statista.com:443/logGenerateHighchart/693200/png
https://www.statista.com:443/logGenerateHighchart/272014/png

IMAGE, PDF
https://www.statista.com:443/download/MTUzMzMyMzc1OCMjNTIwMDA1IyM0ODA0MTgjIzEjI3BkZiMjU3RhdGlzdGlj
https://www.statista.com:443/download/MTUzMzMyNDIwMiMjNTIwMDA1IyM0NjIzNTcjIzEjI3BkZiMjU3RhdGlzdGlj

IMAGE, EXCEL
https://www.statista.com:443/download/MTUzMzMyMzc1OCMjNTIwMDA1IyM0ODA0MTgjIzEjI3hsc3gjI1N0YXRpc3RpYw==
https://www.statista.com:443/download/MTUzMzMyNDIwMiMjNTIwMDA1IyM0NjIzNTcjIzEjI3hsc3gjI1N0YXRpc3RpYw==

IMAGE, POWERPOINT
https://www.statista.com:443/download/MTUzMzMyMzc1OCMjNTIwMDA1IyM0ODA0MTgjIzEjI3BwdHgjI1N0YXRpc3RpYw==
https://www.statista.com:443/download/MTUzMzMyNDIwMiMjNTIwMDA1IyM0NjIzNTcjIzEjI3BwdHgjI1N0YXRpc3RpYw==

LOG:
[Statista.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2258605/Statista.txt)
