### ISSUE TITLE
Journal of Jewish Studies

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/ezpaarse-platforms#126]
### Example:star::star: :
https://www-jjs-online-net.proxy.library.emory.edu/

www.jjs-online.net
jjs-online.net

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
SEARCH;MISC
https://www.jjs-online.net:443/contents/search/searchme:masada
https://www.jjs-online.net:443/contents/search/searchme:herod/year:/type:all/volume:/fpage:
https://www.jjs-online.net:443/archives/keywords
https://www.jjs-online.net:443/contents/search/searchme:Persian/what%5B0%5D:keywords

TOC;HTML
https://www.jjs-online.net:443/archives/contents
https://www.jjs-online.net:443/archives/volume/60

ABS;HTML
https://www.jjs-online.net:443/supplements/series_1

REF;HTML
https://www.jjs-online.net:443/archives/article/1858
https://www.jjs-online.net:443/archives/article/831
https://www.jjs-online.net:443/supplements/catalogue

ARTICLE;PDF
https://www.jjs-online.net:443/archives/fulltext/1858
https://www.jjs-online.net:443/archives/fulltext/831

[jjs_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3677238/jjs_log.txt)
