### ISSUE TITLE
Duke University Press

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#127]
11/29/2017 EPM
Duke was on the Highwire platform previous to November 22nd.  They switched to Silverchair.  
Any duke university press stanzas from Highwire will need to be transitioned to Silverchair.
Info about the migration:  https://www.dukeupress.edu/Libraries/migration.php

5/9/2019 LH
https://read-dukeupress-edu.proxy.library.emory.edu/
read.dukeupress.edu
reader.dukeupress.edu
www.dukeupress.edu
dukeupress.edu 

Stanza on AnalogIST is for Highwire

**Comment by lisahamlett** [comment]
SEARCH, HTML
https://read.dukeupress.edu:443/search-results?page=1&q=aristotle
https://read.dukeupress.edu:443/books/search-results?page=1&f_FacetCategoryIDs_1=6&fl_SiteID=1000007&allBooks=1

SEARCH or TOC, HTML
https://read.dukeupress.edu:443/books/pages/Browse_by_Subject
https://read.dukeupress.edu:443/journals/pages/Browse_by_Title
https://read.dukeupress.edu:443/journals/pages/Browse_by_Subject

ABSTRACT, HTML
https://read.dukeupress.edu:443/books/book/2045/Natural-and-Moral-History-of-the-Indies
https://read.dukeupress.edu:443/tikkun/article/30383/?searchresult=1&searchresult=1
https://read.dukeupress.edu:443/hope/article-abstract/18/3/523/11287/Aristotle-as-a-Welfare-Economist-A-Comment-with-a?searchresult=1
https://read.dukeupress.edu:443/hope/article-abstract/17/3/391/11238/Aristotle-and-the-Problem-of-Insatiable-Desires-A

ARTICLE, PDF
https://read.dukeupress.edu:443/hope/article-pdf/423764/ddhope_17_3_391.pdf
https://read.dukeupress.edu:443/hope/article-pdf/423764/ddhope_17_3_391.pdf

BOOK CHAPTER, PDF
https://read.dukeupress.edu:443/books/chapter-pdf/494704/9780822383932-011.pdf
https://read.dukeupress.edu:443/books/chapter-pdf/494704/9780822383932-011.pdf1
