### ISSUE TITLE
American Physiological Society

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#128]
#### Example:star::star: :
https://www-physiology-org.proxy.library.emory.edu/

#### Priority: 
High

#### Subscriber (Library): 
Woodruff

#### ezPAARSE
Analysis: http://analogist.couperin.org/platforms/559694a112120d440d1ec726  (The information is wrong here (it says it is part of High Wire).)
Trello: https://trello.com/c/gmBBbUSB/276-american-physiological-society-hw

#### Details:
Migrated to Atyphon from Wiley

**Comment by lisahamlett** [comment]
https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/physiology

> Title American Physiological Society (updated 20180725)
> URL https://www.physiology.org
> HJ http://www.physiology.org/
> HJ advan.physiology.org
> HJ ajpcell.physiology.org
> HJ ajpcon.physiology.org
> HJ ajpendo.physiology.org
> HJ ajpgi.physiology.org
> HJ ajplegacy.physiology.org
> DJ cloudfront.net
> HJ https://d2avczb82rh8fa.cloudfront.net
> HJ d2avczb82rh8fa.cloudfront.net
> HJ ajpheart.physiology.org
> HJ ajplegacy.physiology.org
> HJ ajplung.physiology.org
> HJ ajpregu.physiology.org
> HJ ajprenal.physiology.org
> HJ apsselect.physiology.org
> HJ jap.physiology.org
> HJ jappl.physiology.org
> HJ jn.physiology.org
> HJ physiolgenomics.physiology.org
> HJ physiologyonline.org
> HJ physiologyonline.physiology.org
> HJ physreports.physiology.org
> HJ physrev.physiology.org
> HJ www.physiologyonline.org
> HJ www.the-aps.org
> DJ physiology.org
> DJ the-aps.org

A Hosted EZproxy Include File is available for this resource. Hosted EZproxy customers will receive automatic updates with OCLC’s latest version of this stanza by adding the following line to config.txt:

> IncludeFile databases/physiology.txt

If you experience problems with the proxy dropping when downloading PDFs, try adding the following lines to the end of your stanza:

> Find physiology.org\/sites
> Replace ^Pphysiology.org^\/sites
> Find physiology.org\/content\/
> Replace ^Pphysiology.org^\/content\/

**Comment by lisahamlett** [comment]
The information is wrong here (it says it is part of High Wire), but this is the link for the platform:
http://analogist.couperin.org/platforms/559694a112120d440d1ec726

**Comment by CB987** [comment]
DOMAINS
www.physiology.org

SEARCH, HTML
https://www.physiology.org:443/action/doSearch?AllField=rainbow
https://www.physiology.org:443/action/doSearch?AllField=rainbow&startPage=&SeriesKey=ajpregu
https://www.physiology.org:443/action/doSearch?AllField=%22J.+L.+Barton%22
https://www.physiology.org:443/action/doSearch?field1=Contrib&text1=BArton&publication=&Ppub=&Ppub=&AfterMonth=&AfterYear=&BeforeMonth=&BeforeYear=
https://www.physiology.org:443/author/Burton%2C+R+R
https://www.physiology.org:443/keyword/Emphysema

TOC, HTML
https://www.physiology.org:443/journal/ajpheart
https://www.physiology.org:443/journal/physiologyonline
https://www.physiology.org:443/toc/ajprenal/316/5
https://www.physiology.org:443/toc/physiologyonline/34/3
https://www.physiology.org:443/topic/cross-journal/featured-articles?seriesKey=&tagCode=
https://www.physiology.org:443/topic/advances-collections/2018-institute-for-teaching-and-learning?seriesKey=&tagCode=
https://www.physiology.org:443/toc/ajprenal/current

REF, HTML
https://www.physiology.org:443/ajprenal/about

ABS, HTML
https://www.physiology.org:443/doi/abs/10.1152/jappl.1967.22.4.782

ARTICLE, HTML
https://www.physiology.org:443/doi/full/10.1152/ajpheart.00004.2019
https://www.physiology.org:443/doi/full/10.1152/physiol.00007.2019
https://www.physiology.org:443/doi/full/10.1152/advan.00045.2019


ARTICLE, PDF
https://www.physiology.org:443/doi/pdf/10.1152/ajpheart.00004.2019
https://www.physiology.org:443/doi/pdf/10.1152/physiol.00007.2019
https://www.physiology.org:443/doi/pdf/10.1152/jappl.1967.22.4.782

LOG:
[amphyssoc_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3188336/amphyssoc_log.txt)
