### ISSUE TITLE
Journal of Clinical Psychiatry

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/ezpaarse-platforms#13]
URL: http://www.psychiatrist.com

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
Three members of their "family of sites" do not proxy:
- http://www.cmeinstitute.com/
- http://neurologyknowledge.com/
- http://www.strongveterans.com/

Not sure they're supposed to, but I figured I should note it anyway.

**Comment by lisahamlett** [comment]
[Journal of Clinical Psychiatry Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1657568/Journal.of.Clinical.Psychiatry.Links.txt)

**Comment by lisahamlett** [comment]
[Journal of Clinical Psychiatry with Rtype.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1725183/Journal.of.Clinical.Psychiatry.with.Rtype.txt)
