### ISSUE TITLE
Gallup Analytics

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#138]
### Example:star::star: :
http://analytics.gallup.com/213617/gallup-analytics.aspx
https://analyticscampus-gallup-com.proxy.library.emory.edu/

### Priority: 
High

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by AGCooper** [comment]
According to dbs_toplevel.txt we only use https://analyticscampus-gallup-com.proxy.library.emory.edu and that web site says "Access Denied".

**Comment by eipeele** [comment]
@AGCooper  Was this decided as unnecessary?

**Comment by AGCooper** [comment]
@eipeele I guess the question is what to do? - I can't find anything relevant.

**Comment by eipeele** [comment]
I should have looked at my own notes before putting it in the project.  This is a new subscription so we don't have it yet, nor is there a standard ezproxy database stanza for it.  Put a pin in it for now, and I'll take care of it.

**Comment by lisahamlett** [comment]
This is active now and can be parsed, but there is nothing on AnalogIST.

**Comment by CB987** [comment]
analyticscampus.gallup.com

TABLE, HTML
https://analyticscampus.gallup.com:443/Charts

GRAPH, HTML
https://analyticscampus.gallup.com:443/Tables/ 

MAP, HTML
https://analyticscampus.gallup.com:443/Explore

REF, HTML
https://analyticscampus.gallup.com:443/Profiles

Map is the only place I can find identifiers showing a specific question is searched for
https://analyticscampus.gallup.com:443/Data/GetMapRankData?questionId=130&regionId=32&demoId=67
https://analyticscampus.gallup.com:443/Data/GetMapRankData?questionId=182&regionId=32&demoId=67
https://analyticscampus.gallup.com:443/Data/GetProfileMetricData?questionId=107&geoId=&regionId=32
https://analyticscampus.gallup.com:443/Data/GetProfileMetricData?questionId=347&geoId=&regionId=31

ARTICLE, HTML <these are obvs articles but similar structure to above results
https://analyticscampus.gallup.com:443/Data/GetArticleData?itemId=257597
https://analyticscampus.gallup.com:443/Data/GetArticleData?itemId=257612

ezProxy log
[gallup_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3188107/gallup_log.txt)
