### ISSUE TITLE
UNiLibrary

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#139]
### Example:star::star: :
unilibrary.org (wouldn't load as of 12/6/2017)

Should be http://www.un-ilibrary.org/ (12/20/2017)

### Priority: 
High

### Subscriber (Library): 
Woodruff

#Note:  Same platform as OECDiLibrary, so will be added to that.

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello

**Comment by AGCooper** [comment]
Added to issue #79
