### ISSUE TITLE
ProQuest Primary Source Purchase

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#140]
### Example:star::star: :
1: News Policy and Politics Magazine Archive $40,941
http://www.proquest.com/products-services/News-Policy-Politics-Magazine-Archive.html
2. Women’s Magazine Archive I: One-Time Purchase, $40,941 http://www.proquest.com/products-services/Womens-Magazine-Archive.html
3: History Vault: American Politics and Society from Kennedy to Watergate
http://cisupa.proquest.com/ksc_assets/history_vault/americanpoliticsandsociety.pdf
 4: History Vault: Women’s Studies from the Schlesinger Library Collections
http://cisupa.proquest.com/ksc_assets/history_vault/struggleforwomen.pdf
5: History Vault: American Indians and the American West, 1809-1971
http://proquest.libguides.com/historyvault/amerindians
6: History Vault: Immigration: Records of the INS http://cisupa.proquest.com/ksc_assets/history_vault/immigration_insrecords.pdf
7: History Vault: American Politics and the Early Cold War—Truman and Eisenhower Administrations, 1945-1961

### Priority: 
High

### Subscriber (Library): 
Woodruff

#Note:  ProQuest isn't a completed parser from EZPaarse, so this may need to wait until that is complete or at least in available beta.

**Comment by AGCooper** [comment]
There already is an issue for proquest #70
