### ISSUE TITLE
Tibetan Buddhist Resource Center

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#142]
### Example:star::star: :
https://www-tbrc-org.proxy.library.emory.edu
https://www-tbrc-org.proxy.library.emory.edu/#!specials/core

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
Closing because same as https://github.com/emory-libraries/ezpaarse-platforms/issues/83
