### ISSUE TITLE
Mathematical Sciences Publishers [MSP]

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/ezpaarse-platforms#15]
#### Example:star::star: :
https://msp-org.proxy.library.emory.edu/

www.msp.org
msp.org

#### Priority: 
Low

#### Subscriber (Library): 
Woodruff

#### ezPAARSE
Analysis: http://ang.couperin.org/platforms/54364f73cb35340a3a7b0c30
Trello: https://trello.com/c/8nlde7bh/141-mathematical-sciences-publishers-msp

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://msp.org:443/publications/journals/
https://msp.org:443/publications/books/
https://msp-org:443/publications/websites/
https://msp.org:443/pjm/about/journal/specialissues.html
https://msp.org:443/index/ai.php?jpath=pjm

TOC;HTML
https://msp.org:443/involve/
https://msp.org:443/involve/2020/13-2/
https://msp.org:443/paa/2020/2-2/
https://msp.org:443/paa/2019/1-4/index.xhtml

ABS;HTML
https://msp.org:443/paa/2019/1-4/p02.xhtml
https://msp.org:443/obs/2019/2/p26.xhtml

ARTICLE;PDF
https://msp.org:443/involve/2015/8-3/involve-v8-n3-p01-s.pdf
https://msp.org:443/paa/2019/1-4/paa-v1-n4-p02-p.pdf

[msp.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4685421/msp.txt)
