### ISSUE TITLE
Bates Visual Guide To Physical Examination

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#17]
Example: 
batesvisualguide.com
Priority:  Medium

**Comment by lisahamlett** [comment]
Nothing on Trello or Couperin.

Links:


ARTICLE, PDF
http://batesvisualguide.com:80/data/multimedia/lww_bates_osce3_sorethroat_transcript_final.pdf
http://batesvisualguide.com:80/data/multimedia/lww_bates_osce5_cough_transcript_final.pdf
http://batesvisualguide.com:80/DocumentLibrary/Bates/BatesVideoPersistentUrls.pdf
 
TOC, HTML
http://batesvisualguide.com:80/multimedia.aspx?categoryId=21787
http://batesvisualguide.com:80/multimedia.aspx?categoryid=21788
 
VIDEO, HTML
http://batesvisualguide.com:80/MultimediaPlayer.aspx?multimediaid=6091076
http://batesvisualguide.com:80/MultimediaPlayer.aspx?multimediaid=6091248
http://batesvisualguide.com:80/MultimediaPlayer.aspx?multimediaid=6130474
http://batesvisualguide.com:80/MultimediaPlayer.aspx?multimediaid=6130478
 
SEARCH, HTML
http://batesvisualguide.com:80/searchresults.aspx
