### ISSUE TITLE
Dynamed

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#174]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=http://search.ebscohost.com/login.aspx?authtype=uid&user=s4173904&password=password&profile=dmp

### Priority: 
High

### Subscriber (Library): 
Health

*This is for the sole purpose of getting how many hits to Dynamed Health is receiving.  Once users pass through proxy, the proxy drops, so we really just need to find users go through this link or find it through other sources.  Eventually, we can parse all of the Ebsco database, but this one is more important for right now.

**Comment by AGCooper** [comment]
- &profile=ehost > EBSCOhost Research Databases
- &profile=gideon > Gideon Online
- &profile=dmp > Dynamed Plus
- &profile=rrc > Rehabilitation Reference Center
- &profile=isabel > Isabel Healthcare - Dynamed Plus

**Comment by eipeele** [comment]
Isabel is technically not proxied (http://www.isabelhealthcare.com/login/login?&resource=DMP&custid=s4173904) so this will likely be incomplete, but go for it.

All ebscohost databases can be parsed based on the profile code.  I'm attached the list of profile codes Chris sent as well as marking whether or not Emory has them & cares to know about them.

@AGCooper Do you want this issue to be solely focused on Dynamed and the others you listed, or Ebscohost processing as a whole?

**Comment by eipeele** [comment]
[EBSCO.codes.for.EZProxy.xlsx](https://github.com/emory-libraries/ezpaarse-platforms/files/1857087/EBSCO.codes.for.EZProxy.xlsx)
