### ISSUE TITLE
American Heart Journal

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#175]
### Example:star::star: :

www.ahjonline.com

### Priority: 
High

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
Nothing on AnalogIST, Trello, or OCLC.
Stanza in ezProxy looks complete.

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello

**Comment by lisahamlett** [comment]
This is already parsing as part of Science Direct
