### ISSUE TITLE
The American Journal of Medicine

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#176]
### Example:star::star: :
www.amjmed.com

### Priority: 
High

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
Copyright © 2018 Elsevier Inc.
Nothing on Couperin or Trello.
Resource not proxied.  Will need to do that before I can look for links.
EDIT: Double checked and this actually isn't proxied.

**Comment by lisahamlett** [comment]
Added proxy.  Images don't show in the log, which is all sorts of annoying.

ARTICLE, HTML
https://www.amjmed.com:443/article/S0002-9343(17)30403-5/fulltext
https://www.amjmed.com:443/article/S0002-9343(17)30456-4/fulltext
https://www.amjmed.com:443/article/S0002-9343(17)31280-9/fulltext
https://www.amjmed.com:443/article/S0002-9343(18)30008-1/fulltext
https://www.amjmed.com:443/article/S0002-9343(18)30039-1/fulltext
https://www.amjmed.com:443/article/S0002-9343(18)30044-5/fulltext
https://www.amjmed.com:443/article/S0002-9343(18)30408-X/fulltext
https://www.amjmed.com:443/article/S0002-9343(18)30409-1/fulltext
 
ARTICLE, PDF
https://www.amjmed.com:443/article/S0002-9343(18)30008-1/pdf
https://www.amjmed.com:443/article/S0002-9343(18)30039-1/pdf
https://www.amjmed.com:443/article/S0002-9343(18)30044-5/pdf
https://www.amjmed.com:443/article/S0002-9343(18)30409-1/pdf
 
SUPPL, POWERPOINT
https://www.amjmed.com:443/article/S0002-9343(18)30409-1/ppt
 
TOC, HTML
https://www.amjmed.com:443/content/diagnosticdilemma
https://www.amjmed.com:443/current
https://www.amjmed.com:443/issue/S0002-9343(17)X0002-8
https://www.amjmed.com:443/issues
https://www.amjmed.com:443/issues?publicationCode=ajm&journal=ajm&jc=ajm
https://www.amjmed.com:443/mmaeducation
https://www.amjmed.com:443/supplements
 
SEARCH, HTML
https://www.amjmed.com:443/action/doSearchSecure?searchType=quick&searchText=ethanol&occurrences=all&journalCode=ajm&searchScope=fullSite&code=ajm-site
