### ISSUE TITLE
American Society for Microbiology

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#177]
### Example:star::star: :
https://www-asm-org.proxy.library.emory.edu/

### Priority: 
High

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/5435107c690651b3ac384351
Trello: https://trello.com/c/lVBBrrUU/102-american-society-for-microbiology-hw

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/5435107c690651b3ac384351
https://trello.com/c/lVBBrrUU/102-american-society-for-microbiology-hw

Added stanza to ezProxy:
https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/American_Society_for_Microbiology

**Comment by lisahamlett** [comment]
Part of High Wire.
Will add as part of issue https://github.com/emory-libraries/ezpaarse-platforms/issues/186
