### ISSUE TITLE
BioTechniques - The International Journal of Lice Science Methods

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#179]
### Example:star::star: :
www.biotechniques.com

### Priority: 
High 

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
Redirects to https://www.future-science.com/journal/btn
Nothing on AnalogIST or Trello.
Does not proxy -- will add stanza.

**Comment by lisahamlett** [comment]
There's very little specifically for BioTechniques, as all the articles and searches go back to Future Science, so we might want to consider changing the stanza and building a Future Science parser.

TOC, HTML
https://www.future-science.com:443/journal/btn
https://www.future-science.com:443/btn/mostcited

REF, HTML
https://www.future-science.com:443/btn/newsandmedia
https://www.future-science.com:443/btn/news
https://www.future-science.com:443/btn/media
https://www.future-science.com:443/btn/interviews
https://www.future-science.com:443/btn/glossary
http://forums.biotechniques.com:80/

ARTICLE, HTML
https://www.future-science.com:443/btn/interview/15
https://www.future-science.com:443/btn/opinion/1
http://www.future-science.com:80/btn/news/dec17/17
http://www.future-science.com:80/btn/news/feb17/28
https://www.future-science.com:443/doi/10.2144/btn-2018-0014
https://www.future-science.com:443/doi/10.2144/000113610
https://www.future-science.com:443/doi/10.2144/000112257

SEARCH, HTML
https://www.future-science.com:443/author/Liew%2C+Teresa
https://www.future-science.com:443/action/doSearch?AllField=pizza

FORUM (No idea what you want to call this), HTML
http://forums.biotechniques.com:80/viewforum.php?f=2&sid=0ade39f8b7a4e9e1b61206e3779e1799
http://forums.biotechniques.com:80/viewtopic.php?f=2&t=45158
http://forums.biotechniques.com:80/viewforum.php?f=28
http://forums.biotechniques.com:80/viewtopic.php?f=28&t=44741

LOG:
[BioTechniques.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2258708/BioTechniques.txt)
