### ISSUE TITLE
Cochrane

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#18]
Example:
training.cochrane.org
cochraneclinicalanswers.com
methods.cochrane.org
www.cochrane.org
www.cochranelibrary.com
Priority:  Medium
Subscriber:  Health

**Comment by lisahamlett** [comment]
In list 11 - "analysis infeasible"
https://trello.com/c/sCEso9q1/250-cochrane-library-cochrane-library

http://ang.couperin.org/platforms/5656e6edd2f68a880d257f53

**Comment by AGCooper** [comment]
@eipeele Content provider is Wiley Online.

**Comment by eipeele** [comment]
yes, they are part of Wiley:  https://www.oclc.org/support/services/ezproxy/documentation/db/cochrane.en.html

**Comment by lisahamlett** [comment]
Closing because this is part of Wiley
