### ISSUE TITLE
CHEST

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#180]
### Example:star::star: :

journal.chestnet.org

### Priority: 
High

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello.

TOC, HTML
https://journal.chestnet.org:443/current
https://journal.chestnet.org:443/issues
https://journal.chestnet.org:443/inpress
https://journal.chestnet.org:443/meetings
https://journal.chestnet.org:443/issue/S0012-3692(17)X0003-2
https://journal.chestnet.org:443/multimedia
https://journal.chestnet.org:443/ultrasound
https://journal.chestnet.org:443/pearls
https://journal.chestnet.org:443/giants
https://journal.chestnet.org:443/podcast
https://journal.chestnet.org:443/chest
https://journal.chestnet.org:443/reports
https://journal.chestnet.org:443/asthma

ARTICLE, HTML
https://journal.chestnet.org:443/article/S0012-3692(17)31547-7/fulltext
https://journal.chestnet.org:443/article/S0012-3692(17)33281-6/fulltext

ARTICLE, PDF
https://journal.chestnet.org:443/article/S0012-3692(17)31547-7/pdf
https://journal.chestnet.org:443/article/S0012-3692(17)33281-6/pdf 

ARTICLE, POWERPOINT
https://journal.chestnet.org:443/article/S0012-3692(17)31547-7/ppt
https://journal.chestnet.org:443/article/S0012-3692(17)33281-6/ppt 

SEARCH, HTML
https://journal.chestnet.org:443/action/doSearchSecure?searchType=quick&searchText=brain&occurrences=all&journalCode=chest&searchScope=fullSite&code=chest-site
https://journal.chestnet.org:443/action/doSearchSecure?searchType=quick&searchText=blister&occurrences=all&journalCode=chest&searchScope=fullSite&code=chest-site

VIDEO, HTML
https://journal.chestnet.org:443/cms/attachment/a8cf188e-8b14-429f-8800-0940c91678b8/mmc1.mp4

LOG:
[CHEST.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2255208/CHEST.txt)
