### ISSUE TITLE
CNKI

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#181]
### Example:star::star: :
search.cnki.net

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
So... um... yeah...
We're probably gonna need someone who speaks Chinese to do this one...

**Comment by lisahamlett** [comment]
I can't read nothin' on this page.

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/59561ef9f98950acd74a2c89
https://trello.com/c/tJYNxKmP/356-cnki-cnki

**Comment by AGCooper** [comment]
T China National Knowledge Infrastructure
U http://cnki.net
HJ en.oversea.cnki.net
HJ eng.oversea.cnki.net
HJ gb.oversea.cnki.net
HJ hd.cnki.net/kxhd
DJ cnki.net

x.cnki.net

**Comment by AGCooper** [comment]
http://oversea.cnki.net.proxy.library.emory.edu

**Comment by lisahamlett** [comment]
Updated stanza to match OCLC

**Comment by lisahamlett** [comment]
kns.cnki.net does not proxy -- i will add it

**Comment by lisahamlett** [comment]
PDF and other downloads do not show in the log

**Comment by lisahamlett** [comment]
SEARCH, HTML
http://oversea.cnki.net:80/kcms/detail/search.aspx?dbcode=CJFD&sfield=kw&skey=%e9%bb%84%e8%8a%b1%e9%b1%bc
http://oversea.cnki.net:80/kcms/detail/search.aspx?dbcode=CJFD&sfield=kw&skey=large+jellyfish
 
TOC, HTML
http://oversea.cnki.net:80/kns55/Navi/CDMDNavi.aspx?XueKe=1&NaviID=36&xkCode=020209&xkName=Quantitative+Economics
http://oversea.cnki.net:80/kns55/Navi/CDMDNavi.aspx?XueKe=1&NaviID=36&xkCode=030201&xkName=Political+Theory
http://oversea.cnki.net:80/kns55/Navi/CDMDNavi.aspx?XueKe=1&NaviID=36&xkCode=040201&xkName=Basic+Psychology
http://oversea.cnki.net:80/kns55/Navi/CDMDNavi.aspx?XueKe=1&NaviID=36&xkCode=05&xkName=Literature
 
ABSTRACT, HTML
http://oversea.cnki.net:80/Kcms/detail/detail.aspx?filename=STXB201610036&dbcode=CJFD&dbname=CJFD2016
http://oversea.cnki.net:80/kns55/detail/detail.aspx?QueryID=94&CurRec=1&DbCode=CJFD&dbname=CJFDLAST2017&filename=KXYY201708057
http://oversea.cnki.net:80/kns55/detail/detail.aspx?QueryID=94&CurRec=2&DbCode=CJFD&dbname=CJFDLAST2017&filename=SICA201709019
http://oversea.cnki.net:80/kns55/detail/detail.aspx?recid=&FileName=HYFZ201706023&DbName=CJFD2017&DbCode=CJFD
http://kns.cnki.net:80/KXReader/Detail?dbcode=CJFD&filename=KXYY201708057&uid=WEEvREcwSlJHSldRa1FhcEE0RVZycFZqd0tMMFdSNWFYTk9sR2loYUhMOD0=$9A4hF_YAuvQ5obgVAqNKPCYcEjKensW4ggI8Fm4gTkoUKaID8j8gFw!!

**Comment by AGCooper** [comment]
Update the stanza in ezproxy

**Comment by lisahamlett** [comment]
ARTICLE, PDF
http://oversea.cnki.net:80/kcms/download.aspx?filename=XWRJmWWRzMxFzc0d3Ni52MpdnYW1mUOdVcmJEbNVTeSVHdw50KrdFNRlFbHNWO0JHWTFVZElFbBlkR=0zYC9UWrZESHBTMR52cSZXVLJWV4I3d4p3TulzarJ1QGJXZOtSQph3Spd2NOVWSyEnbShndaFESOF&dflag=catalog&tablename=CDFD1214&cflag=pdf
http://oversea.cnki.net:80/kcms/download.aspx?filename=VM5VjSt5kMsNnaBNTMsRFN0IzSXF1SidUaa5EamFzQo1kYDhFVqhXez1GVhdje5k0ZWhHa2R2SNZmV=0zYCRXWxp3Vr02S58iSjlURzJzSLlkVN50cPplarkDSolER11GazZkNOlka4Z3d0oFN5sUNGN0Uwg&dflag=catalog&tablename=CDFD1214&cflag=pdf
