### ISSUE TITLE
Data-planet

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#182]
### Example:star::star: :
www.data-planet.com

### Priority: 
HIgh

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Nothing on Couperin or Trello.
Resource not proxied. Will need to do that before I can look for links.
EDIT: There's a stanza for this, but it needs to be modified.

**Comment by lisahamlett** [comment]
Susan Gue reported this one today, so I updated the stanza to match OCLC.

**Comment by lisahamlett** [comment]
Links: 
[DataPlanet.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2011012/DataPlanet.txt)
