### ISSUE TITLE
Digital Campus - Swank Motion Pictures

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#183]
### Example:star::star: :
digitalcampus.swankmp.net
### Priority: 
High

### Subscriber (Library): 
Woodruff

Notes:  I don't think Swank proxies like normal, so this may take some work with Chris to figure out what they want (I could be wrong).

**Comment by lisahamlett** [comment]
Nothing on Couperin or Trello.
Resource not proxied, per EPM's note above. Will need to do that before I can look for links.
EDIT: Updated stanza to match OCLC

**Comment by lisahamlett** [comment]
Updated stanza to match OCLC.

**Comment by lisahamlett** [comment]
Still dropping proxy. No idea what to do with this.

**Comment by lisahamlett** [comment]
Note from OCLC stanza page:

> In order to access your subscribed resources at Swank Digital Campus, you must construct your starting point URLs following this example:
> 
> https://ezproxy.mylib.edu/login?url=https://digitalcampus.swankmp.net/{portal_id}
> 
> where you replace {portal_id} with the Portal ID provided to you by Swank. For questions about this identifier, please contact Swank directly.

Do we know our portal id?

**Comment by lisahamlett** [comment]
https://digitalcampus.swankmp.net/emory274900

**Comment by lisahamlett** [comment]
Every time you click something (anything), you get one of these in the log:
170.140.212.239 7SCJNHN6BjT5479 lhamlet [30/May/2018:13:23:36 -0400] "POST https://digitalcampus.swankmp.net:443/emory274900/Analytics/PushEvent/ HTTP/1.1" 200 0 https://digitalcampus-swankmp-net.proxy.library.emory.edu/emory274900 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

When you click play on a video, you get this:
170.140.212.239 7SCJNHN6BjT5479 lhamlet [30/May/2018:13:28:02 -0400] "GET https://digitalcampus.swankmp.net:443/services/s3services/mobile/playinfo?contentId=82531&contentUrl=https:%2F%2Fdc.swankmp.net%2Fcontent%2Fcenc%2FA14093_E2_XX_XX_XX%2F37141733%2FA14093_E2_XX_XX_XX.mpd&deviceId=d6ee23af-5b83-482d-b4aa-5624b6b03dbd HTTP/1.1" 200 519 https://digitalcampus-swankmp-net.proxy.library.emory.edu/emory274900 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
The actual link is https://digitalcampus-swankmp-net.proxy.library.emory.edu/emory274900#/play/82531, so it looks like the 82531 is the title id

Searches show up with a jasonapi call:
170.140.212.239 7SCJNHN6BjT5479 lhamlet [30/May/2018:13:33:49 -0400] "POST https://digitalcampus.swankmp.net:443/emory274900/jsonapi/SearchContent?encodeTypes=cenc,cenc2&portalId=6e7cbb88-ca7f-48ec-9dfb-259e5bbc1749 HTTP/1.1" 200 1891 https://digitalcampus-swankmp-net.proxy.library.emory.edu/emory274900 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

That's all that is showing in the logs.

**Comment by AGCooper** [comment]
New stanza:

T Swank Digital Campus
U https://digitalcampus.swankmp.net/
H digitalcampus.swankmp.net
H digitalcampus.swankmp.com
H dc.swankmp.com
H https://digitalcampus.swankmp.net
H https://digitalcampus.swankmp.com
H https://dc.swankmp.com
H https://www.swank.com`
D swankmp.com
D swankmp.net
