### ISSUE TITLE
eHRAF

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#184]
### Example:star::star: :
https://hraf-yale-edu.proxy.library.emory.edu/
https://ehrafarchaeology-yale-edu.proxy.library.emory.edu/ehrafa/
https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/ehrafe/

### Priority: 
High

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello.

OCLC Stanza:
https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/eHRAF_World_Cultures

**Comment by CB987** [comment]
[hraf_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3363766/hraf_log.txt)
