### ISSUE TITLE
Add to High Wire (hw)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#186]
### Example:star::star: :
American Society for Microbiology
https://www-asm-org.proxy.library.emory.edu/
www.asm.org
asm.org/

Journal of the American College of Cardiology
http://www.onlinejacc.org.proxy.library.emory.edu/
www.onlinejacc.org
onlinejacc.org

Remove Duke University Press and Add to Silverchair

### Priority: 
High

### Subscriber (Library): 
Health

### Note:
https://github.com/emory-libraries/ezpaarse-platforms/tree/master/hw/pkb
run scrape all

**Comment by lisahamlett** [comment]
Nothing on AnalogIST, Trello, or OCLC.
Added stanza to ezProxy.
