### ISSUE TITLE
Journal of Clinical Epidemiology (WHSCL 4)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#187]
### Example:star::star: :
https://login.proxy.library.emory.edu/login?url=https://www.jclinepi.com/

### Priority: 
High

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
Nothing on AnalogIST, Trello, or OCLC.
Added stanza to ezProxy.

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello.
No official OCLC stanza.

**Comment by lisahamlett** [comment]
Part of Elsevier but not on the Elsevier domain.

**Comment by lisahamlett** [comment]
SEARCH, HTML
https://www.jclinepi.com:443/action/doSearchSecure?searchType=quick&searchText=potato&occurrences=all&journalCode=jce&searchScope=fullSite&code=jce-site
https://www.jclinepi.com:443/action/doSearchSecure?searchType=quick&searchText=jones&occurrences=author&journalCode=jce&searchScope=fullSite&code=jce-site

ABSTRACT, HTML
https://www.jclinepi.com:443/article/S0895-4356(17)30015-X/abstract

ARTICLE, HTML
https://www.jclinepi.com:443/article/S0895-4356(06)00209-5/fulltext
https://www.jclinepi.com:443/article/S0895-4356(17)30015-X/fulltext
https://www.jclinepi.com:443/article/S0895-4356(01)00414-0/fulltext

ARTICLE, PDF
https://www.jclinepi.com:443/article/S0895-4356(06)00209-5/pdf
https://www.jclinepi.com:443/article/S0895-4356(17)30015-X/pdf

SUPPLEMENT, HTML
https://www.jclinepi.com:443/article/S0895-4356(17)30015-X/references
https://www.jclinepi.com:443/article/S0895-4356(01)00414-0/references

IMAGES?, HTML
https://www.jclinepi.com:443/action/showFullTextImages?pii=S0895-4356%2801%2900414-0

[jclinepi_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2601011/jclinepi_log.txt)
