### ISSUE TITLE
Journal of Studies on Alcohol and Drugs

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#188]
### Example:star::star: :
www.jsad.com

### Priority: 
High

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/573b3d768452a7a877771056
https://trello.com/c/Uy9cq1u4/365-journal-of-studies-on-alcohol-and-drugs-jsad

I can't get anything to show in the logs for this.  Not even a session log in. :(

**Comment by AGCooper** [comment]
@lisahamlett You may want to look again I get a bunch of stuff including for example:

10.110.26.49 RuVYu89yrCEErP1 acoope5 [02/Aug/2018:12:39:55 -0400] "GET https://www.jsad.com:443/doi/abs/10.15288/jsad.2018.79.391 HTTP/1.1" 200 49508 https://www-jsad-com.proxytest.library.emory.edu/ Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

**Comment by lisahamlett** [comment]
Here's my log for clicking around:
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:41:58 -0400] "GET http://proxy.library.emory.edu:80/admin HTTP/1.1" 200 339 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:42:02 -0400] "GET http://proxy.library.emory.edu:80/usage?find=lhamlet HTTP/1.1" 200 6483 http://proxy.library.emory.edu/admin Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:43:51 -0400] "GET http://proxy.library.emory.edu:80/usage?find=lhamlet HTTP/1.1" 200 6483 http://proxy.library.emory.edu/admin Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:43:55 -0400] "GET http://proxy.library.emory.edu:80/usage?find=lhamlet HTTP/1.1" 200 6483 http://proxy.library.emory.edu/admin Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:44:06 -0400] "GET http://proxy.library.emory.edu:80/usage?find=lhamlet HTTP/1.1" 200 6483 http://proxy.library.emory.edu/admin Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:44:28 -0400] "GET http://proxy.library.emory.edu:80/usage?find=lhamlet HTTP/1.1" 200 6483 http://proxy.library.emory.edu/admin Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:44:54 -0400] "GET http://proxy.library.emory.edu:80/usage?find=lhamlet HTTP/1.1" 200 6483 http://proxy.library.emory.edu/admin Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:44:57 -0400] "GET https://fonts.googleapis.com:443/css?family=Titillium+Web:400,700 HTTP/1.1" 200 2192 https://www-jsad-com.proxy.library.emory.edu/action/doSearch?AllField=liver Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:45:08 -0400] "GET http://proxy.library.emory.edu:80/usage?find=lhamlet HTTP/1.1" 200 6483 http://proxy.library.emory.edu/admin Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:45:32 -0400] "GET http://proxy.library.emory.edu:80/usage?find=lhamlet HTTP/1.1" 200 6483 http://proxy.library.emory.edu/admin Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:45:47 -0400] "GET http://proxy.library.emory.edu:80/usage?find=lhamlet HTTP/1.1" 200 6483 http://proxy.library.emory.edu/admin Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:46:43 -0400] "GET https://doi.org:443/10.15288/jsad.2018.79.5 HTTP/1.1" 302 626 https://www-jsad-com.proxy.library.emory.edu/doi/abs/10.15288/jsad.2018.79.5 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

**Comment by lisahamlett** [comment]
Nothing shows in the logs if you're in production -- only in test.

**Comment by AGCooper** [comment]
:man_shrugging: weird

**Comment by lisahamlett** [comment]
Clicked everything I can think of.  Here is my log:
10.110.27.246 bssxljE1iqBPVNZ lhamlet [08/Aug/2018:13:38:46 -0400] "GET https://fonts.googleapis.com:443/css?family=Titillium+Web:400,700 HTTP/1.1" 200 2269 https://www-jsad-com.proxy.library.emory.edu/ Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.27.246 bssxljE1iqBPVNZ lhamlet [08/Aug/2018:13:39:01 -0400] "GET https://doi.org:443/10.15288/jsad.2018.79.391 HTTP/1.1" 302 635 https://www-jsad-com.proxy.library.emory.edu/doi/full/10.15288/jsad.2018.79.391 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.27.246 bssxljE1iqBPVNZ lhamlet [08/Aug/2018:13:40:22 -0400] "GET https://doi.org:443/10.15288/jsad.2014.75.908 HTTP/1.1" 302 632 https://www-jsad-com.proxy.library.emory.edu/doi/full/10.15288/jsad.2014.75.908 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

**Comment by lisahamlett** [comment]
SEARCH, HTML
https://www.jsad.com:443/action/doSearch?AllField=bananas

ABSTRACT, HTML
https://www.jsad.com:443/doi/abs/10.15288/jsa.1982.43.146
https://www.jsad.com:443/doi/abs/10.15288/jsad.2016.77.371
https://www.jsad.com:443/doi/abs/10.15288/QJSA.1940.1.110

ARTICLE, HTML
https://www.jsad.com:443/doi/full/10.15288/jsad.2016.77.371
https://www.jsad.com:443/doi/full/10.15288/jsad.2018.79.333

ARTICLE, PDF
https://www.jsad.com:443/doi/pdf/10.15288/jsa.1982.43.146
https://www.jsad.com:443/doi/pdf/10.15288/jsad.2016.77.371
https://www.jsad.com:80/doi/pdf/10.15288/QJSA.1940.1.110

REF, HTML
https://www.jsad.com:443/doi/ref/10.15288/jsad.2016.77.371
https://www.jsad.com:443/doi/ref/10.15288/jsad.2018.79.333

SUPPLEMENT, HTML
https://www.jsad.com:443/doi/suppl/10.15288/jsad.2016.77.371

CITATION, HTML
https://www.jsad.com:443/doi/citedby/10.15288/jsad.2016.77.371
https://www.jsad.com:443/doi/citedby/10.15288/QJSA.1940.1.110

LOG:
[jsad.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2271457/jsad.txt)
