### ISSUE TITLE
Journal of the American Academy of Child and Adolescent Psychiatry

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#189]
### Example:star::star: :
https://www-jaacap-org.proxy.library.emory.edu/

### Priority: 
High

### Subscriber (Library): 
Health

### ezPAARSE
Analysis: None
Trello: None

### Note:
Part of Elsevier but not on the Elsevier domain.

**Comment by lisahamlett** [comment]
Nothing on AnalogIST, Trello, or OCLC.
Added stanza to ezProxy.

**Comment by CB987** [comment]
SEARCH, HTML
https://www.jaacap.org:443/action/doSearch?occurrences=all&searchText=childhood+anxiety&searchType=quick&searchScope=fullSite&journalCode=jaac
https://www.jaacap.org:443/action/doSearch?occurrences=all&searchText=rainbow&searchType=quick&searchScope=fullSite&journalCode=jaac
https://www.jaacap.org:443/action/doSearch?searchType=authorLookUp&author=Belcher,%20Harolyn%20M.E.&prod=HA

REF, HTML
https://www.jaacap.org:443/article/S0890-8567(18)32061-6/references
https://www.jaacap.org:443/action/showCitFormats?pii=S0890-8567%2816%2931569-6&doi=10.1016%2Fj.jaac.2016.09.340
https://www.jaacap.org:443/action/showCitFormats?pii=S0890-8567%2818%2931967-1&doi=10.1016%2Fj.jaac.2018.08.013
https://www.jaacap.org:443/content/jaac_otc_50_10 (vol 50 no 10)
https://www.jaacap.org:443/content/jaac_otc_58_5 (vol 58 no 5)

TOC, HTML
https://www.jaacap.org:443/issue/S0890-8567(18)X0007-0
https://www.jaacap.org:443/issue/S0890-8567(17)X0002-6
https://www.jaacap.org:443/content/clinpersp
https://www.jaacap.org:443/content/ednotes
https://www.jaacap.org:443/master_clinician_reviews
https://www.jaacap.org:443/current
https://www.jaacap.org:443/commentary

ABSTRACT, HTML
https://www.jaacap.org:443/article/S0890-8567(19)30117-0/abstract
https://www.jaacap.org:443/article/S0890-8567(19)30002-4/abstract

ARTICLE, HTML
https://www.jaacap.org:443/article/S0890-8567(19)30173-X/fulltext
https://www.jaacap.org:443/article/S0890-8567(19)30174-1/fulltext
https://www.jaacap.org:443/article/S0890-8567(18)31967-1/fulltext

ARTICLE, PDF
https://www.jaacap.org:443/article/S0890-8567(19)30173-X/pdf
https://www.jaacap.org:443/article/S0890-8567(19)30117-0/pdf
https://www.jaacap.org:443/article/S0890-8567(17)31731-8/pdf


IMAGE, JPEG
https://www.jaacap.org:443/action/showFullTextImages?pii=S0890-8567%2818%2932061-6
https://www.jaacap.org:443/action/showFullTextImages?pii=S0890-8567%2818%2931967-1

AUDIO, MP3
https://www.jaacap.org:443/pb/assets/raw/Health%20Advance/journals/jaac/jaac_pc_58_06-1558713372970.mp3
https://www.jaacap.org:443/pb/assets/raw/Health%20Advance/journals/jaac/jaac_pc_58_03-1551734789133.mp3

IMAGE, MISC
https://www.jaacap.org:443/article/S0890-8567(18)31967-1/ppt
https://www.jaacap.org:443/article/S0890-8567(18)31967-1/ppt

[jaacap_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3307228/jaacap_log.txt)
