### ISSUE TITLE
Journal of Urology

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#190]
### Example:star::star: :
www.jurology.com

### Priority: 
High

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
I lied... I this did show in the logs:
170.140.213.222 0XlGSLqSsFgJBn6 lhamlet [03/Aug/2018:13:44:13 -0400] "GET http://www.jurology.com:80/ HTTP/1.1" 301 0 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

The link from DiscoverE goes to ScienceDirect, so could that be part of the issue?
170.140.213.222 0XlGSLqSsFgJBn6 lhamlet [03/Aug/2018:13:47:24 -0400] "GET https://www.sciencedirect.com:443/journal/the-journal-of-urology HTTP/1.1" 200 98270 http://na03.alma.exlibrisgroup.com/view/uresolver/01GALI_EMORY/openurl?ctx_enc=info:ofi/enc:UTF-8&ctx_id=10_1&ctx_tim=2018-08-03T12:47:06IST&ctx_ver=Z39.88-2004&url_ctx_fmt=info:ofi/fmt:kev:mtx:ctx&url_ver=Z39.88-2004&rfr_id=info:sid/primo.exlibrisgroup.com-01EMORY_ALMA&req_id=&rft_dat=ie=01GALI_EMORY:51272014230002486,language=eng,view=discovere&svc_dat=viewit&u.ignore_date_coverage=true&req.skin=Default Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
I can't find any links at Emory where it goes to jurology.com

**Comment by lisahamlett** [comment]
This one isn't proxied, which probably has something to do with why it doesn't work...  Adding a stanza for it now.

**Comment by lisahamlett** [comment]
SEARCH, HTML
https://www.jurology.com:443/action/doSearchSecure?searchType=quick&searchText=freud&occurrences=all&journalCode=juro&searchScope=fullSite&code=juro-site
https://www.jurology.com:443/action/doSearchSecure?searchType=quick&searchText=bananas&occurrences=all&journalCode=juro&searchScope=fullSite&code=juro-site

ARTICLE, HTML
https://www.jurology.com:443/article/S0022-5347(18)43403-9/fulltext
https://www.jurology.com:443/article/S0022-5347(18)43118-7/fulltext

ARTICLE, PDF
https://www.jurology.com:443/article/S0022-5347(18)43403-9/pdf
https://www.jurology.com:443/article/S0022-5347(18)43118-7/pdf

ARTICLE, POWERPOINT
https://www.jurology.com:443/article/S0022-5347(18)39418-7/ppt

TOC, HTML
https://www.jurology.com:443/current
https://www.jurology.com:443/issues
https://www.jurology.com:443/inpress
https://www.jurology.com:443/issue/S0022-5347(18)X0002-0
https://www.jurology.com:443/supplements
https://www.jurology.com:443/issues?publicationCode=juro&journal=juro&jc=juro
https://www.jurology.com:443/content/UrologicalSurvey
https://www.jurology.com:443/content/FeaturedArticles

LOG:
[Urology.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2258487/Urology.txt)
