### ISSUE TITLE
Journal of Vascular Surgery

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#191]
### Example:star::star: :
https://www-jvascsurg-org.proxy.library.emory.edu/

### Priority: 
High

### Subscriber (Library): 
Health

### ezPAARSE
Analysis: None
Trello: None

### Note:
Part of Elsevier but not on the Elsevier domain.

**Comment by lisahamlett** [comment]
Nothing on AnalogIST, Trello, or OCLC.

Added stanza to ezProxy.

**Comment by CB987** [comment]
SEARCH, HTML
https://www.jvascsurg.org:443/action/doSearch?occurrences=all&searchText=rainbow&searchType=quick&searchScope=fullSite&journalCode=ymva
https://www.jvascsurg.org:443/action/doSearch?searchType=quick&occurrences=all&ltrlSrch=true&searchScope=fullSite&searchText=Abdominal%20aortic%20aneurysm%20(AAA)&code=ymva-site

TOC, HTML
https://www.jvascsurg.org:443/issue/S0741-5214(19)X0007-5
https://www.jvascsurg.org:443/issue/S0741-5214(19)X0006-3
https://www.jvascsurg.org:443/issue/S0741-5214(17)X0013-X
https://www.jvascsurg.org:443/content/SVS2018
https://www.jvascsurg.org:443/content/specialCTU
https://www.jvascsurg.org:443/content/ymva-ImagesArchive

ABS, HTML
https://www.jvascsurg.org:443/article/S0741-5214(18)32469-8/abstract
https://www.jvascsurg.org:443/article/S0741-5214(06)01485-6/abstract

ARTICLE, HTML
https://www.jvascsurg.org:443/article/S0741-5214(18)32556-4/fulltext
https://www.jvascsurg.org:443/article/S0741-5214(18)32481-9/fulltext

ARTICLE, PDF
https://www.jvascsurg.org:443/article/S0741-5214(18)32556-4/pdf
https://www.jvascsurg.org:443/article/S0741-5214(03)01112-1/pdf

IMAGE, MISC
https://www.jvascsurg.org:443/ymva_va_70_1_2_full
https://www.jvascsurg.org:443/ymva_va_68_6_2_full

VIDEO, MISC
https://www.jvascsurg.org:443/cms/attachment/d527a335-3b5d-4cee-8baf-95fbec831b83/mmc1.mp4
https://www.jvascsurg.org:443/cms/attachment/7a8bbded-5320-45d8-a4f4-e50af2d5a017/mmc1.mp4

[jvascsurg_logs.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3369246/jvascsurg_logs.txt)
