### ISSUE TITLE
JoVE - Peer Reviewed Scientific Video Journal- Methods and Protocols

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#192]
### Example:star::star: :
dev-stats.jove.com
ecsource.jove.com
stats.jove.com

### Priority: 
High

### Subscriber (Library): 
Woodruff/Health

**Comment by lisahamlett** [comment]
TOC, HTML
https://www.jove.com:443/author/Heying_Cui
https://www.jove.com:443/author/Kyle++M._Loftus
https://www.jove.com:443/author/Sozanne++R._Solmaz
https://www.jove.com:443/author/William+R._Katzka
https://www.jove.com:443/institutions/NA-North-America/US-United-States/NY-New-York/26331-Binghamton-University
https://www.jove.com:443/journal/behavior
https://www.jove.com:443/journal/chemistry
https://www.jove.com:443/journal/immunology-infection
https://www.jove.com:443/methods-collections/11/mechanical-stimulation-techniques
https://www.jove.com:443/methods-collections/2/protein-protein-interaction-methods
https://www.jove.com:443/science-education/basicbio
https://www.jove.com:443/science-education/eng
https://www.jove.com:443/science-education/physics
 
ARTICLE, PDF
https://www.jove.com:443/pdf/10318/jove-science-education-10318-rcrllc-circuits
https://www.jove.com:443/pdf/1555/jove-protocol-1555-freezing-and-thawing-human-embryonic-stem-cells
https://www.jove.com:443/pdf/50146/jove-protocol-50146-generation-topically-transgenic-rats-utero-electroporation-vivo
https://www.jove.com:443/pdf/5019/jove-science-education-5019-an-introduction-to-the-centrifuge
https://www.jove.com:443/pdf/5034/jove-science-education-5034-introduction-to-serological-pipettes-and-pipettors
https://www.jove.com:443/pdf/57262/jove-protocol-57262-development-microfluidic-devices-to-study-elongation-capability-tip
 
ARTICLE, HTML
https://www.jove.com:443/science-education/10114/electrical-safety-precautions-and-basic-equipment
https://www.jove.com:443/science-education/10318/rcrllc-circuits
https://www.jove.com:443/science-education/5019/an-introduction-to-the-centrifuge
https://www.jove.com:443/science-education/5034/introduction-to-serological-pipettes-and-pipettors
https://www.jove.com:443/science-education-library/35/electrical-engineering
 
SEARCH, HTML
https://www.jove.com:443/search/ajax?q=amphetamine&filter_type_1=and&filter_val_1=&filter_type_2=or&filter_val_2=&filter_type_3=not&filter_val_3=&authors=&from=&to=&exclude_sections=&exclude_series=
 
VIDEO, HTML
https://www.jove.com:443/video/1555/freezing-and-thawing-human-embryonic-stem-cells
https://www.jove.com:443/video/50146/generation-topically-transgenic-rats-utero-electroporation-vivo
https://www.jove.com:443/video/5019/an-introduction-to-the-centrifuge
https://www.jove.com:443/video/57262/development-microfluidic-devices-to-study-elongation-capability-tip
https://www.jove.com:443/video/57395/assessing-activity-based-anorexia-in-mice
https://www.jove.com:443/video/57674/identification-cyclin-dependent-kinase-1-specific-phosphorylation

**Comment by AGCooper** [comment]
https://trello.com/c/qF4qd4FG/295-jove
http://ang.couperin.org/platforms/565d7485d5d046415b5db469

**Comment by AGCooper** [comment]
So there is already a parser for www.jove.com, and trello and couperin entries.

These domains all redirect to www.jove.com:

dev-stats.jove.com
ecsource.jove.com
stats.jove.com

**Comment by AGCooper** [comment]
try running some of the links through /ezpaarse-platforms/jove/parser.js on master

**Comment by lisahamlett** [comment]
TOC, HTML (does not parse)
https://www.jove.com:443/journal/behavior
https://www.jove.com:443/journal/chemistry
https://www.jove.com:443/journal/immunology-infection
https://www.jove.com:443/methods-collections/11/mechanical-stimulation-techniques
https://www.jove.com:443/methods-collections/2/protein-protein-interaction-methods
https://www.jove.com:443/science-education/basicbio
https://www.jove.com:443/science-education/eng
https://www.jove.com:443/science-education/physics
 
ARTICLE, HTML (parses as video, which I could see maybe)
https://www.jove.com:443/science-education/10114/electrical-safety-precautions-and-basic-equipment
https://www.jove.com:443/science-education/10318/rcrllc-circuits
https://www.jove.com:443/science-education/5019/an-introduction-to-the-centrifuge
https://www.jove.com:443/science-education/5034/introduction-to-serological-pipettes-and-pipettors
https://www.jove.com:443/science-education-library/35/electrical-engineering
 
SEARCH, HTML (does not parse)
https://www.jove.com:443/search/ajax?q=amphetamine&filter_type_1=and&filter_val_1=&filter_type_2=or&filter_val_2=&filter_type_3=not&filter_val_3=&authors=&from=&to=&exclude_sections=&exclude_series=
 
VIDEO, HTML (parses as article, which is incorrect)
https://www.jove.com:443/video/1555/freezing-and-thawing-human-embryonic-stem-cells
https://www.jove.com:443/video/50146/generation-topically-transgenic-rats-utero-electroporation-vivo
https://www.jove.com:443/video/5019/an-introduction-to-the-centrifuge
https://www.jove.com:443/video/57262/development-microfluidic-devices-to-study-elongation-capability-tip
https://www.jove.com:443/video/57395/assessing-activity-based-anorexia-in-mice
https://www.jove.com:443/video/57674/identification-cyclin-dependent-kinase-1-specific-phosphorylation

**Comment by AGCooper** [comment]
Those videos are described as Journal Articles in crossref.org. Keep in mind this parser has been in ezpaarse for a while now so  changing it will yield conflicting data. But if we don't have to worry about that then I can go ahead.

Adding things will do.

**Comment by lisahamlett** [comment]
That's fine then.  No worries.
