### ISSUE TITLE
Nature

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#193]
### Example:star::star: :
mts-nbt.nature.com
mts-nchem.nature.com
mts-ncomms.nature.com
www.nature.org
mts-nenergy.nature.com
mts-ng.nature.com
mts-ni.nature.com
mts-nm.nature.com
mts-nmicrobiol.nature.com
mts-nn.nature.com
mts-nri.nature.com
mts-nrmicro.nature.com
mts-nrn.nature.com
cancer-immunity.nature.com
masterclasses.nature.com (this is going to Shib at some point in the future)

### Priority: 
High

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/5410711521bf25051e829c16
https://trello.com/c/IeVYqyr6/68-nature-publishing-group-npg

**Comment by lisahamlett** [comment]
ARTICLE, HTML
https://blog.nature.org:443/science/2016/05/09/elk-antlers-prairie-shed-hunt-benefit-local-community-kids-nature-activities/?utm_source=cgs&utm_medium=archive&utm_campaign=Connect+with+Nature
https://blog.nature.org:443/science/2016/06/15/steering-a-new-course-for-kenyas-fisheries/
https://blog.nature.org:443/science/2018/03/08/urban-leopards-can-save-lives-by-eating-feral-dogs/?utm_source=cgs&utm_medium=archive&utm_campaign=Big+Questions
https://blog.nature.org:443/science/2018/05/11/bird-advisor-one-intrepid-birder-reviews-historic-sites/?intc=nature.hp.science
https://global.nature.org:443/content/beyond-the-source
https://global.nature.org:443/content/down-to-earth
https://global.nature.org:443/content/nature-is-our-strongest-ally-in-ensuring-global-water-security?intc=nature.hp.news2
 
ARTCLE, XML
https://www.nature.org:443/magazine/archives/counting-on-fish.xml
https://www.nature.org:443/magazine/archives/growing-green.xml
https://www.nature.org:443/magazine/archives/junejuly-2016.xml
https://www.nature.org:443/magazine/archives/nature-conservancy-magazine-spring-2018-issue.xml
https://www.nature.org:443/magazine/archives/nautical-quest.xml
https://www.nature.org:443/ourinitiatives/regions/northamerica/unitedstates/georgia/can-we-save-the-gopher-tortoise.xml
https://www.nature.org:443/ourinitiatives/regions/northamerica/unitedstates/georgia/explore/georgia-job-corps-longleaf-pine-restoration.xml
https://www.nature.org:443/ourinitiatives/regions/northamerica/unitedstates/georgia/newsroom/chattahoochee-oconee-nf-land-adjustment-act-introduced.xml
https://www.nature.org:443/ourinitiatives/regions/northamerica/unitedstates/georgia/placesweprotect/charles-harrold-preserve.xml
https://www.nature.org:443/ourinitiatives/regions/northamerica/unitedstates/oregon/oregon-forests-and-beer.xml
https://www.nature.org:443/ourinitiatives/regions/northamerica/unitedstates/wildlife-live-cams-and-trail-camera-traps.xml
 
TOC, HTML
https://blog.nature.org:443/science/innovations/
https://blog.nature.org:443/science/section/big-questions/
https://blog.nature.org:443/science/section/nature-and-you/
https://www.nature.org:443/magazine/archives/index.htm
https://www.nature.org:443/magazine/index.htm?intc=nature.hp.magazine
https://www.nature.org:443/ourinitiatives/regions/northamerica/unitedstates/georgia/index.htm
https://www.nature.org:443/ourinitiatives/regions/northamerica/unitedstates/georgia/newsroom/index.htm
https://www.nature.org:443/ourinitiatives/regions/northamerica/unitedstates/georgia/placesweprotect/index.htm
https://www.nature.org/ourinitiatives/regions/northamerica/unitedstates/nature-unites-us-all.xml?intc=nature.hp.volunteer
https://www.nature.org:443/ourinitiatives/regions/northamerica/unitedstates/nature-unites-us-all.xml?intc=nature.hp.volunteer
https://www.nature.org:443/ourinitiatives/regions/northamerica/unitedstates/oregon/index.htm
 
VIDEO, HTML
https://www.nature.org:443/photos-and-video/video/natureunitesus-louisvillehcsthcsthcst
 
SEARCH, HTML
https://www.nature.org:443/search/index.htm?site=prod_nature_org&client=NatureOrg&ie=UTF-8&oe=UTF-8&output=xml_no_dtd&ud=1&entqr=0&q=alcohol
