### ISSUE TITLE
NEJM Journal Watch (JWatch)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#194]
### Example:star::star: :
https://www-jwatch-org.proxy.library.emory.edu/

### Priority: 
High

### Subscriber (Library): 
Health

### ezPAARSE
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
Nothing on Couperin or Trello.
Resource not proxied. Will need to do that before I can look for links.

**Comment by lisahamlett** [comment]
JWatch is non-functional at the moment.
Service Now Ticket: INC02918733

**Comment by CB987** [comment]
[jwatch_logs.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3408042/jwatch_logs.txt)
