### ISSUE TITLE
Chicago Manual of Style

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#196]
### Example:star::star: :
chicagomanualofstyle.org
www.chicagomanualofstyle.org

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Nothing on Couperin or Trello.

Links:

BOOK PART, HTML
http://www.chicagomanualofstyle.org:80/book/ed17/part1/ch02/psec004.html
http://www.chicagomanualofstyle.org:80/book/ed17/part1/ch02/psec140.html
http://www.chicagomanualofstyle.org:80/book/ed17/part2/ch10/psec050.html
http://www.chicagomanualofstyle.org:80/book/ed17/part2/ch13/psec009.html
http://www.chicagomanualofstyle.org:80/book/ed17/part2/ch13/psec025.html
http://www.chicagomanualofstyle.org:80/book/ed17/part3/ch14/psec009.html
http://www.chicagomanualofstyle.org:80/book/ed17/part3/ch14/psec146.html
 
SUPPLEMENT
http://www.chicagomanualofstyle.org:80/book/ed17/backmatter/glos.html
http://www.chicagomanualofstyle.org:80/book/ed17/part2/ch09/tables/tbl001.html
http://www.chicagomanualofstyle.org:80/book/ed17/part2/ch11/tables/tbl001.html
http://www.chicagomanualofstyle.org:80/book/ed17/part2/ch11/tables/tbl002.html
http://www.chicagomanualofstyle.org:80/book/ed17/part2/ch12/tables/tbl004.html
 
TOC, HTML
http://www.chicagomanualofstyle.org:80/book/ed17/backmatter/biblio/toc.html
http://www.chicagomanualofstyle.org:80/book/ed17/part1/ch02/toc.html
http://www.chicagomanualofstyle.org:80/book/ed17/part2/ch13/toc.html
http://www.chicagomanualofstyle.org:80/book/ed17/part3/ch14/toc.html
http://www.chicagomanualofstyle.org:80/book/ed17/frontmatter/tables.html
http://www.chicagomanualofstyle.org:80/book/ed17/frontmatter/toc.html
http://www.chicagomanualofstyle.org:80/qanda/topicList
 
SEARCH, HTML
http://www.chicagomanualofstyle.org:80/search.html?clause=abbreviations
http://www.chicagomanualofstyle.org:80/search.html?clause=reference+symbols
 
REF, HTML
http://www.chicagomanualofstyle.org:80/help-tools/my-manual/notes.html
http://www.chicagomanualofstyle.org:80/help-tools/resources.html
http://www.chicagomanualofstyle.org:80/help-tools/Resources-for-Librarians-and-Teachers.html
http://www.chicagomanualofstyle.org:80/help-tools/Videos.html
http://www.chicagomanualofstyle.org:80/qanda/data/faq/topics/LessorFewer.html
http://www.chicagomanualofstyle.org:80/qanda/latest.html
http://www.chicagomanualofstyle.org:80/tools_citationguide.html
http://www.chicagomanualofstyle.org:80/tools_citationguide/citation-guide-2.html
