### ISSUE TITLE
Royal Society of Chemistry

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#197]
### Example:star::star: :
www.rsc.org

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/54117196c7315fd853984bf8
https://trello.com/c/nDHEA6x9/74-royal-society-of-chemistry-rsc

[RoyalSocietyChemistry Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1996627/RoyalSocietyChemistry.Links.txt)
