### ISSUE TITLE
The Lancet

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#198]
### Example:star::star: :
www.thelancet.com

### Priority: 
High

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
Nothing on Couperin or Trello

**Comment by lisahamlett** [comment]
One of their journals, EBioMedicine (http://www.ebiomedicine.com/), drops the proxy.

**Comment by lisahamlett** [comment]
FYI:
Copyright © 2018 Elsevier Limited except certain content provided by third parties.
The Lancet is a trade mark of Elsevier Limited.
The Lancet.com website is operated by Elsevier Inc. The content on this site is intended for health professionals.

**Comment by lisahamlett** [comment]
[lancet.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1876910/lancet.txt)
