### ISSUE TITLE
Transplantation Proceedings

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#199]
### Example:star::star: :
www.transplantation-proceedings.org

### Priority: 
High

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
Nothing on Trello or Couperin.
Also, this drops proxy once you get in to the site, so I have no links to add.

**Comment by AGCooper** [comment]
Access: http://www.transplantation-proceedings.org:80/
