### ISSUE TITLE
Embase

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#20]
Example:
www.embase.com
Priority:  Medium
Subscriber:  Health

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/5a14420c66ebb553abd43b7a
https://trello.com/c/Mb2x9DaF/440-embase-emb

**Comment by lisahamlett** [comment]
I didn't find much that they didn't already have linked in the AnalogIST analyses.
But here's my file anyway.

[embaselinks.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1557146/embaselinks.txt)
