### ISSUE TITLE
Update Chadwyck

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#200]
### Example:star::star: :
https://www-proquest-com.proxy.library.emory.edu/products-services/connect/connect_ch.html
https://github.com/emory-libraries/ezpaarse-platforms/tree/master/chadwyck

### Priority: 
High (Changed from low because part of this one is done and we need to finish it because the data in Libstats is half complete.)

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
These are the Publication Titles for all of the Chadwyck titles that have not yet moved to ProQuest.

 if (result.rtype !== null) {
    if (/(aabd.chadwyck.com|aabd.chadwyck.com.co.uk)/i.test(host)) {
      // aabd.chadwyck.com
      result.publication_title = 'African American Biographical Database';
    } else if (/(acta.chadwyck.com|acta.chadwyck.co.uk)/i.test(host)) {
      // acta.chadwyck.com
      result.publication_title = 'Acta Sanctorum';
    } else if (/(bsc.chadwyck.com|bsc.chadwyck.co.uk)/i.test(host)) {
      // bsc.chadwyck.com
      result.publication_title = 'Black Studies Center';
    } else if (/(collections.chadwyck.com|collections.chadwyck.co.uk)/i.test(host)) {
      // collections.chadwyck.com
      result.publication_title = 'Chadwyck-Healey Literature Collections';
    } else if (/(eebo.chadwyck.com|eebo.chadwyck.co.uk)/i.test(host)) {
      // eebo.chadwyck.com
      result.publication_title = 'Early English Books Online';
    } else if (/(gerritsen.chadwyck.com|gerritsen.chadwyck.co.uk)/i.test(host)) {
      // gerritsen.chadwyck.com
      result.publication_title = 'The Gerritsen Collection';
    } else if (/(glc.chadwyck.com|glc.chadwyck.co.uk)/i.test(host)) {
      // glc.chadwyck.com
      result.publication_title = 'German Literature Collections';
    } else if (/(glp.chadwyck.com|glp.chadwyck.co.uk)/i.test(host)) {
      // glp.chadwyck.com
      result.publication_title = 'Die Deutsche Lyrik';
    } else if (/(goethe.chadwyck.com|goethe.chadwyck.co.uk)/i.test(host)) {
      // goethe.chadwyck.com
      result.publication_title = 'Goethes Werke';
    } else if (/(history.chadwyck.com|history.chadwyck.co.uk)/i.test(host)) {
      // history.chadwyck.co.uk
      result.publication_title = 'Historical Newspapers';
    } else if (/(historymakers.chadwyck.com|historymakers.chadwyck.co.uk)/i.test(host)) {
      // historymakers.chadwyck.com
      result.publication_title = 'The HistoryMakers';
    } else if (/(historynews.chadwyck.com|historynews.chadwyck.co.uk)/i.test(host)) {
      // historynews.chadwyck.com
      result.publication_title = 'Historical Newspapers';
    } else if (/(iibp.chadwyck.com|iibp.chadwyck.co.uk)/i.test(host)) {
      // iibp.chadwyck.com
      result.publication_title = 'Index to Black Periodicals';
    } else if (/(johnjohnson.chadwyck.com|johnjohnson.chadwyck.co.uk)/i.test(host)) {
      // johnjohnson.chadwyck.com
      result.publication_title = 'The John Johnson Collection';
    } else if (/(kafka.chadwyck.com|kafka.chadwyck.co.uk)/i.test(host)) {
      // kafka.chadwyck.com
      result.publication_title = 'Kafka Werke';
    } else if (/(klassiker.chadwyck.com|klassiker.chadwyck.co.uk)/i.test(host)) {
      // klassiker.chadwyck.com
      result.publication_title = 'Bibliothek deutscher Klassiker';
    } else if (/(luther.chadwyck.com|luther.chadwyck.co.uk)/i.test(host)) {
      // luther.chadwyck.com
      result.publication_title = 'Luthers Werke';
    } else if (/(nstc.chadwyck.com|nstc.chadwyck.co.uk)/i.test(host)) {
      // nstc.chadwyck.com
      result.publication_title = 'Nineteenth-Century Short Title Catalogue';
    } else if (/(pld.chadwyck.com|pld.chadwyck.co.uk)/i.test(host)) {
      // pld.chadwyck.co.uk
      result.publication_title = 'Patrologia Latina';
    } else if (/(qvj.chadwyck.com|qvj.chadwyck.co.uk)/i.test(host)) {
      // qvj.chadwyck.com
      result.publication_title = 'Queen Victoria\'s Journals';
    } else if (/(teso.chadwyck.com|teso.chadwyck.co.uk)/i.test(host)) {
      // teso.chadwyck.com
      result.publication_title = 'Teatro Español del Siglo de Oro';
    } else if (/(wellesley.chadwyck.com|wellesley.chadwyck.co.uk)/i.test(host)) {
      // wellesley.chadwyck.co.uk
      result.publication_title = 'The Wellesley Index to Victorian Periodicals, 1824-1900';
    }

**Comment by lisahamlett** [comment]
[Chadwyck Log 1.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3340916/Chadwyck.Log.1.txt)
[Chadwyck Log 2.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3340917/Chadwyck.Log.2.txt)

**Comment by lisahamlett** [comment]
[Chadwyck Test.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3387824/Chadwyck.Test.txt)
[Chadwyck Workbook.xlsx](https://github.com/emory-libraries/ezpaarse-platforms/files/3387825/Chadwyck.Workbook.xlsx)
