### ISSUE TITLE
Aluka

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#201]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=https://www.aluka.org/

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE:
Analysis: None

### Notes:
Technically part of JSTOR, but has its own domain.
Need to add to EZProxy.

**Comment by lisahamlett** [comment]
Has now moved to JSTOR.
