### ISSUE TITLE
Atlas of North American English

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#203]
### Example:star::star: :
http://www.atlas.mouton-content.com.proxy.library.emory.edu/

atlas.mouton-content.com
www.atlas.mouton-content.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE:
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
![image](https://user-images.githubusercontent.com/32074210/83039089-b598dd00-a00b-11ea-83f7-1cb60a04523b.png)

**Comment by lisahamlett** [comment]
Is now part of De Gruyter and that's where our links route.
