### ISSUE TITLE
Biomedical Journal - Table of Contents

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#204]
### Example:star::star: :
http://biomedj.cgu.edu.tw.proxy.library.emory.edu/

### Priority: 
Low

### Subscriber (Library): 
Health

### ezPAARSE:
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
The TOC can be parsed.  The articles are on PubMed.

**Comment by lisahamlett** [comment]
TOC;HTML
http://biomedj.cgu.edu.tw:80/
http://biomedj.cgu.edu.tw:80/backissues.htm
http://biomedj.cgu.edu.tw:80/2014_37_6.htm

ARTICLE;PDF
http://biomedj.cgu.edu.tw:80/pdfs/2014/37/6/images/BiomedJ_2014_37_6_339_146538.pdf
http://biomedj.cgu.edu.tw:80/pdfs/2014/37/6/images/BiomedJ_2014_37_6_375_132883.pdf

CITATION;HTML
http://biomedj.cgu.edu.tw:80/articlecited.asp?issn=2319-4170;year=2015;volume=38;issue=4;spage=317;epage=322;aulast=Amin;aid=BiomedJ_2015_38_4_317_151034

[biomedj.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4689517/biomedj.txt)
