### ISSUE TITLE
Docuseek

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#206]
### Example:star::star: :
http://docuseek2.com.proxy.library.emory.edu/

docuseek2.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE:
Analysis: None

**Comment by lisahamlett** [comment]
SEARCH;HTML
http://docuseek2.com:80/cart/advsearch/hf
https://docuseek2.com:443/cart/advsearch/hf?subjectid=75

TOC;HTML
http://docuseek2.com:80/cart/newreleases_2018
http://docuseek2.com:80/cart/subject_list
https://docuseek2.com:443/cart/collections_new
https://docuseek2.com:443/ds-whists
https://docuseek2.com:443/ds-allca

VIDEO;MISC
http://docuseek2.com:80/bf-whose
http://docuseek2.com:80/if-oday

[docuseek2.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4689750/docuseek2.txt)
