### ISSUE TITLE
Films on Demand

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#207]
### Example:star::star: :
https://fod-infobase-com.proxy.library.emory.edu/ does not work
https://proxy.library.emory.edu/login?url=http://digital.films.com/PortalPlaylists.aspx?aid=26092 is the link under the PID from the databases and seems to be everything authorized for Emory.

digital.films.com
fod.infobase.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE:
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://digital.films.com:443/p_Search.aspx?rd=title&type=browse&home=1
https://digital.films.com:443/p_Search.aspx?rd=a&q=%22Humanities%22

VIDEO;MISC
https://digital.films.com:443/p_ViewVideo.aspx?xtid=7619&tScript=0
https://digital.films.com:443/p_ViewVideo.aspx?xtid=120519&tScript=0

**Comment by lisahamlett** [comment]
[films.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4689804/films.txt)
