### ISSUE TITLE
Frontiers in Bioscience

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#208]
### Example:star::star: :
http://www.bioscience.org.proxy.library.emory.edu/

bioscience.org
www.bioscience.org

### Priority: 
Low

### Subscriber (Library): 
Health

### ezPAARSE:
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://www.bioscience.org:443/search-article/index.php?keywords=spine&author_names=&year=&volume=&pages=&pubmed_no=&abstract=&submit=1

TOC;HTML
https://www.bioscience.org:443/open-access
https://www.bioscience.org:443/fast-track
https://www-bioscience-org:443/express-open-access

ABS;HTML
https://www.bioscience.org:443/2002/v7/d/storz/list.htm
http://www.bioscience.org:80/2009/v14/af/3585/list.htm

ARTICLE;HTML
https://www.bioscience.org:443/2002/v7/d/storz/fulltext.htm
http://www.bioscience.org:80/2009/v14/af/3585/fulltext.htm

ARTICLE;PDF
https://www.bioscience.org:443/fbs/getfile.php?FileName=/2002/v7/d/storz/storz.pdf
https://www.bioscience.org:443/fbs/getfile.php?FileName=/2009/v14/af/3585/3585.pdf

BIO;HTML
https://www.bioscience.org:443/1998/v3/d/palmada/address.htm
https://www.bioscience.org:443/1998/v3/a/xiao/address.htm

DATASET;MISC
https://www.bioscience.org:443/metrics?id=3616
https://www.bioscience.org:443/year-metrics?type=fasttrack

[bioscience.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4690037/bioscience.txt)
