### ISSUE TITLE
Domains to Add to Cambridge University Press (cup)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#209]
### Domains:
https://africabibliography-cambridge-org.proxy.library.emory.edu/
https://dib-cambridge-org.proxy.library.emory.edu/
https://hsus-cambridge-org.proxy.library.emory.edu
http://stahlonline.cambridge.org.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://analogist.couperin.org/platforms/5409ae556363c837e1396094
Trello: https://trello.com/c/YIH50UlD/50-cambridge-university-press-cup

### Note:
https://github.com/emory-libraries/ezpaarse-platforms/tree/master/cup

**Comment by lisahamlett** [comment]
@CB987 To find how to get to these, you need to look at the A-Z list:
https://guides.main.library.emory.edu/az.php?q=africa%20bibliography
https://guides.main.library.emory.edu/az.php?q=irish%20bibliography
https://guides.main.library.emory.edu/az.php?q=historical%20statistics
I can't find Stahl.  I will keep looking.

**Comment by lisahamlett** [comment]
Stahl online is a resource provided by the Stahl Family Foundation (They give us money: https://news.emory.edu/stories/2012/05/dev_student_hardship_fund_gift/campus.html) and provides resources for the medical school.  I can't find a direct link to the resource, but it proxies and we have access, so just use the link I provided and don't worry about how to get to it.
