### ISSUE TITLE
JAMA Network

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#21]
Example:
archopht.jamanetwork.com
www.ama-assn.org
archotol.jamanetwork.com
archsurg.jamanetwork.com
jamaevidence.mhmedical.com
jama.jamanetwork.com
Priority:  High
Subscriber:  Health

**Comment by AGCooper** [comment]
Part of silverchair's platform.

**Comment by AGCooper** [comment]
- archopht.jamanetwork.com => https://jamanetwork.com/journals/jamaophthalmology
- www.ama-assn.org => AMA
- archotol.jamanetwork.com => https://jamanetwork.com/journals/jamaotolaryngology
- archsurg.jamanetwork.com => https://jamanetwork.com/journals/jamasurgery
- jamaevidence.mhmedical.com => Part of  McGraw-Hill Medical
- jama.jamanetwork.com => https://jamanetwork.com/journals/jama

**Comment by eipeele** [comment]
Merged Pull request #26 which included this issue.
