### ISSUE TITLE
Irish News Archives

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#210]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=https://www.irishnewsarchive.com

archive.irishnewsarchive.com
www.irishnewsarchive.com
irishnewsarchive.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE:
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
Emailed ECR to see if this subscription is still active because nothing seems to be accessible from the site.

**Comment by lisahamlett** [comment]
I have updated the above link to the proper access one.

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://archive.irishnewsarchive.com:443/Olive/APA/INA.Edu/get/search.ashx?kind=search&text=seamus%20heaney&in=Article

TOC;HTML
https://archive.irishnewsarchive.com:443/Olive/APA/INA.Edu/get/browse.ashx?kind=years&pub=IND 
https://archive.irishnewsarchive.com:443/Olive/APA/INA.Edu/get/browse.ashx?kind=years&pub=BNH

ARTICLE;HTML
https://archive.irishnewsarchive.com:443/Olive/APA/INA.Edu/get/prxml.ashx?kind=doc&href=CTB%2F2014%2F04%2F18
https://archive.irishnewsarchive.com:443/Olive/APA/INA.Edu/get/prxml.ashx?kind=doc&href=BNH%2F1962%2F01%2F27

DO NOT PARSE!!!
https://archive.irishnewsarchive.com:443/Olive/APA/INA.Edu/get/image.ashx?kind=preview
https://archive.irishnewsarchive.com:443/Olive/APA/INA.Edu/get/image.ashx?kind=page
https://archive.irishnewsarchive.com:443/Olive/APA/INA.Edu/get/prxml.ashx?kind=page

[irishnewsarchive.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4313134/irishnewsarchive.txt)
