### ISSUE TITLE
National Journal

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#212]
### Example:star::star: :
https://www-nationaljournal-com.proxy.library.emory.edu

www.nationaljournal.com
nationaljournal.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE:
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://www.nationaljournal.com:443/search/?q=book&by=relv
https://www.nationaljournal.com:443/almanac/search/?q=&type=&office=Sen&office=Rep&office=Gov&party=&gender=&ethnicity=&religion=Other&jobtitle2=&state=&majmin=

TOC;HTML
https://www.nationaljournal.com:443/daily
https://www.nationaljournal.com:443/daybook
https://www.nationaljournal.com:443/hotline
https://www.nationaljournal.com:443/racetracker
https://www.nationaljournal.com:443/almanac
https://www.nationaljournal.com:443/presentations
https://www.nationaljournal.com:443/events/membership
https://www.nationaljournal.com:443/research
https://www.nationaljournal.com:443/research/grassroots-advocacy/
https://www.nationaljournal.com:443/2020election

ARTICLE;HTML
https://www.nationaljournal.com:443/s/704929/hotline-extra-some-wisdom-from-nigel-farage?
https://www.nationaljournal.com:443/md/707067/coronavirus-health-impact-on-american-indian-and-alaska-native-communities/?

ARTICLE;PDF
https://www.nationaljournal.com:443/media/documents/2020/05/27/nj_covid_aian_health_52720.pdf

ARTICLE;MISC
https://www.nationaljournal.com:443/media/documents/2020/05/27/nj_covid_aian_health_52720.pptx

?;HTML (Event?)
https://www.nationaljournal.com:443/daybook/event/91434/
https://www.nationaljournal.com:443/virtual-event-cook-catch-up-may-29?
https://www.nationaljournal.com:443/the-day-after-the-election-national-journal-member-summit?

DATASET;HTML
https://www.nationaljournal.com:443/racetracker/state/GA/2020/

BIO;HTML
https://www.nationaljournal.com:443/almanac/person/270/
https://www.nationaljournal.com:443/almanac/committee/274/
https://www.nationaljournal.com:443/almanac/staff/254984/

[nationaljournal.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4690163/nationaljournal.txt)
