### ISSUE TITLE
Naxos

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#213]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=http://emory.naxosworks.com/
https://proxy.library.emory.edu/login?url=http://emory.naxosmusiclibrary.com/
https://proxy.library.emory.edu/login?url=http://emory.naxosmusiclibrary.com/jazz/
https://proxy.library.emory.edu/login?url=http://emory.naxosmusiclibrary.com/World/
https://proxy.library.emory.edu/login?url=http://emory.naxosvideolibrary.com/
https://proxy.library.emory.edu/login?url=http://emory.naxosspokenwordlibrary.com/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff (Music & Media)

### ezPAARSE:
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
[Naxos.log](https://github.com/emory-libraries/ezpaarse-platforms/files/3503102/Naxos.log)

**Comment by lisahamlett** [comment]
[NaxosTest.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3507206/NaxosTest.txt)
