### ISSUE TITLE
Open Helix

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#215]
### Example:star::star: :
http://www.openhelix.com.proxy.library.emory.edu/

### Priority: 
Low

### Subscriber (Library): 
Health

### ezPAARSE:
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
Direct link doesn't work and neither does access from discoverE (http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA51285038790002486)

I have emailed eJournals to ask about the status of the platform.

**Comment by lisahamlett** [comment]
eJournals never got back to me, so I'm going to close this.  I will revisit if it shows back up on the missing domains list.
