### ISSUE TITLE
Johns Hopkins Guide to Library Theory and Criticism

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#217]
### Example:star::star: :
https://litguide-press-jhu-edu.proxy.library.emory.edu/

litguide.press.jhu.edu

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE:
Analysis: None

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://litguide.press.jhu.edu:443/cgi-bin/search.cgi?flag=basic

REF;HTML
https://litguide.press.jhu.edu:443/table_of_contents.html
https://litguide.press.jhu.edu:443/entries/index.html
https://litguide.press.jhu.edu:443/contributors.html
https://litguide.press.jhu.edu:443/topical_index.html

BOOK_SECTION;HTML
https://litguide.press.jhu.edu:443/foreword.html
https://litguide.press.jhu.edu:443/preface.html
https://litguide.press.jhu.edu:443/acknowledgements.html
https://litguide.press.jhu.edu:443/cgi-bin/view.cgi?eid=8
https://litguide.press.jhu.edu:443/cgi-bin/view.cgi?section_id=2107

[litguide.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4690230/litguide.txt)
