### ISSUE TITLE
Update National Bureau of Economic Research (nber)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#218]
### Example:star::star: :
https://papers-nber-org.proxy.library.emory.edu/papers.html

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE:
https://github.com/emory-libraries/ezpaarse-platforms/tree/master/nber
http://ang.couperin.org/platforms/54661af263198b780a729ad4

**Comment by lisahamlett** [comment]
Things to add:
BIO;HTML
https://admin.nber.org:443/people/john_cochrane

TOC;HTML
https://admin-nber-org.proxy.library.emory.edu/themes/energy/energysummary.shtml
https://conference.nber.org:443/conferences/2019/SI2019/EFGs19/summary.html

REF;HTML
https://conference.nber.org:443/workinggroups/ent/ent.html

SUPPL;PDF
https://www.nber.org:443/feldstein_lecture_2018/2018feldstein_lecture.pdf 

VIDEO;MISC
https://conference.nber.org:443/feldstein_lecture_2018/feldstein_lecture_2018.html
https://conference.nber.org:443/si2018_video/tradepanel/
https://conference.nber.org:443/si2018_video/socialsecurity/

[nber_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3462897/nber_log.txt)
