### ISSUE TITLE
Brill Databases (World Christian & World Religion)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#219]
### Example:star::star: :
https://worldchristiandatabase-org.proxy.library.emory.edu/
https://worldreligiondatabase-org.proxy.library.emory.edu/

www.worldchristiandatabase.org
worldchristiandatabase.org
www.worldreligiondatabase.org
worldreligiondatabase.org

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE:
Analysis: http://ang.couperin.org/platforms/to_be_completed/

### Note:
Technically part of Brill, but they don't parse the same way.

**Comment by lisahamlett** [comment]
CONNECTION;MISC
https://worldreligiondatabase.org:443/wrd
https://worldchristiandatabase.org:443/wcd

SEARCH;HTML
https://worldreligiondatabase.org:443/wrd/launcher/wcd_search.json?term=cows
https://worldchristiandatabase.org:443/wcd/value_list/gkc:2066
https://worldchristiandatabase.org:443/wcd/launcher/wcd_search.json?term=catholic

ENCYCLOPEDIA_ENTRY;HTML
https://worldreligiondatabase.org:443/wrd/detail/country/data/9.json
https://worldreligiondatabase.org:443/wrd/detail/city/data/133.json
https://worldreligiondatabase.org:443/wrd/detail/province/data/2966.json
https://worldreligiondatabase.org:443/wrd/detail/city-2010-archive/data/14.json
https://worldchristiandatabase.org:443/wcd/detail/denomination/data/1577.json

[brill.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4246746/brill.txt)
