### ISSUE TITLE
East View (eastview)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#220]
### Example:star::star: :
http://wnc.eastview.com.proxy.library.emory.edu/
http://gpa.eastview.com.proxy.library.emory.edu/

gpa.eastview.com
wnc.eastview.com

https://github.com/emory-libraries/ezpaarse-platforms/tree/master/eastview

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE:
Analysis: http://ang.couperin.org/platforms/58f8afce3a0cd8cfcbdd2518

**Comment by lisahamlett** [comment]
Basic searches do not show in the logs in any unique way.

SEARCH;HTML
https://wnc.eastview.com:443/wnc/news

ARTICLE;HTML
https://wnc.eastview.com:443/wnc/simple/doc?art=0&id=32464222
https://wnc.eastview.com:443/wnc/simple/doc?pager.offset=1
https://wnc.eastview.com:443/wnc/simple/articles?pager.offset=0
https://wnc.eastview.com:443/wnc/article?id=38220718&backlink=/wnc/news

WNC is now located at https://www.eastview.com/resources/e-collections/world-news-connection-archive/ though the old site is still active.
GPA is now located at https://www.eastview.com/resources/gpa/ and the old site is defunct.

We do not have access to the new sites, so I am going to add the few lines above and we'll do a parser for the new pages if we acquire them at some point.

**Comment by lisahamlett** [comment]
[eastview.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/5231946/eastview.txt)
