### ISSUE TITLE
World Religion Database

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#221]
### Example:star::star: :
https://worldreligiondatabase-org.proxy.library.emory.edu/

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE:
Analysis: None

### Note:
Technically part of Brill, but has its own domain.

**Comment by lisahamlett** [comment]
Merging with https://github.com/emory-libraries/ezpaarse-platforms/issues/219
