### ISSUE TITLE
World Shakespeare Bibliographys

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#222]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=https://www.worldshakesbib.org/

www.worldshakesbib.org
worldshakesbib.org

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE:
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://www.worldshakesbib.org:443/basic-search/results?[PAYLOAD]
https://www.worldshakesbib.org:443/advanced-search/results?[PAYLOAD]
https://www.worldshakesbib.org:443/browse
https://www.worldshakesbib.org:443/bibliography/biographical-studies
https://www.worldshakesbib.org:443/bibliography/comedies

ENCYCLOPAEDIA_ENTRY;HTML
https://www.worldshakesbib.org:443/entry/aw31?back=/basic-search/results%3Fkeywords%3Dmacbeth%26sort_by%3Dsearch_api_relevance
https://www.worldshakesbib.org:443/entry/aaf1459?back=/basic-search/results%3Fkeywords%3Dmacbeth%26sort_by%3Dsearch_api_relevance
https://www.worldshakesbib.org:443/entry/export/text/601998
https://www.worldshakesbib.org:443/entry/export/ris/601998

[worldshakesbib.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4690268/worldshakesbib.txt)
