### ISSUE TITLE
JPS Journals

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#224]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=https://journals.jps.jp

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: None

### Note:
If you go directly to the website, it authenticates and drops proxy.  If you go through the A-Z list, you get one parsable line:
CONNECTION;MISC
http://journals.jps.jp:80/loi/jpsj

**Comment by lisahamlett** [comment]
Needs to be added to EZproxy.

**Comment by lisahamlett** [comment]
No longer exists in the A-Z list and does not show in the logs at all.
