### ISSUE TITLE
AMA Manual of Style

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#225]
### Example:star::star: :
https://www-amamanualofstyle-com.proxy.library.emory.edu/

www.amamanualofstyle.com
amamanualofstyle.com

### Priority: 
Medium

### Subscriber (Library): 
Health

### ezPAARSE:
Analysis: None

### Note:
Technically part of the JAMA Network and OUP, which is part of Silverchair.  However, the links do not function like Silverchair and it has its own domain, so let's write it separately.

**Comment by lisahamlett** [comment]
SEARCH;MISC
https://www.amamanualofstyle.com:443/search?q=book&searchBtn=Search&isQuickSearch=true
https://www.amamanualofstyle.com:443/search?btog=chap&isQuickSearch=true&pageSize=20&q=book&sort=relevance&t=AMAMOS_SECTIONS%3Amed-9780195176339-chapter-13
https://www.amamanualofstyle.com:443/browse?t1=AMAMOS_SECTIONS%3Amed-9780195176339-chapter-13

SEARCH;PDF
https://www.amamanualofstyle.com:443/oso/search:downloadsearchresultaspdf?t1=AMAMOS_SECTIONS%3Amed-9780195176339-chapter-13

TOC;HTML
https://www.amamanualofstyle.com:443/page/style-quizzes
https://www.amamanualofstyle.com:443/page/si-conversion-calculator
https://www.amamanualofstyle.com:443/view/10.1093/jama/9780195176339.001.0001/med-9780195176339
https://www.amamanualofstyle.com:443/view/10.1093/jama/9780195176339.001.0001/med-9780195176339-chapter-13

REF;HTML
https://www.amamanualofstyle.com:443/view/10.1093/jama/9780195176339.001.0001/med-9780195176339-div2-359
https://www.amamanualofstyle.com:443/view/10.1093/jama/9780195176339.001.0001/med-9780195176339-div2-371?rskey=IhYxpu&result=4

REF;PDF
https://www.amamanualofstyle.com:443/view/10.1093/jama/9780195176339.001.0001/med-9780195176339-div2-361?print=pdf
https://www.amamanualofstyle.com:443/view/10.1093/jama/9780195176339.001.0001/med-9780195176339-div2-362?print=pdf
https://www.amamanualofstyle.com:443/fileasset/files/quizzes/AMA%20MoS%209-2015%20Quiz.pdf
https://www.amamanualofstyle.com:443/fileasset/files/quizzes/References_Answers_final.pdf

TEST
out-print_identifier;out-doi;out-unitid;out-title_id;out-rtype;out-mime;in-url
;;;;SEARCH;MISC;https://www.amamanualofstyle.com:443/search?q=book&searchBtn=Search&isQuickSearch=true
;;;;SEARCH;MISC;https://www.amamanualofstyle.com:443/browse?t1=AMAMOS_SECTIONS%3Amed-9780195176339-chapter-13
;;;;SEARCH;PDF;https://www.amamanualofstyle.com:443/oso/search:downloadsearchresultaspdf?t1=AMAMOS_SECTIONS%3Amed-9780195176339-chapter-13
;;style-quizzes;style-quizzes;TOC;HTML;https://www.amamanualofstyle.com:443/page/style-quizzes
;;si-conversion-calculator;si-conversion-calculator;TOC;HTML;https://www.amamanualofstyle.com:443/page/si-conversion-calculator
9780195176339;10.1093/jama/9780195176339.001.0001;10.1093/jama/9780195176339.001.0001;10.1093/jama/9780195176339.001.0001;TOC;HTML;https://www.amamanualofstyle.com:443/view/10.1093/jama/9780195176339.001.0001/med-9780195176339
9780195176339;10.1093/jama/9780195176339.001.0001;10.1093/jama/9780195176339.001.0001;10.1093/jama/9780195176339.001.0001;TOC;HTML;https://www.amamanualofstyle.com:443/view/10.1093/jama/9780195176339.001.0001/med-9780195176339-chapter-13
9780195176339;10.1093/jama/9780195176339.001.0001;10.1093/jama/9780195176339.001.0001;10.1093/jama/9780195176339.001.0001;REF;HTML;https://www.amamanualofstyle.com:443/view/10.1093/jama/9780195176339.001.0001/med-9780195176339-div2-359
9780195176339;10.1093/jama/9780195176339.001.0001;10.1093/jama/9780195176339.001.0001;10.1093/jama/9780195176339.001.0001;REF;HTML;https://www.amamanualofstyle.com:443/view/10.1093/jama/9780195176339.001.0001/med-9780195176339-div2-371?rskey=IhYxpu&result=4
9780195176339;10.1093/jama/9780195176339.001.0001;10.1093/jama/9780195176339.001.0001;10.1093/jama/9780195176339.001.0001;REF;PDF;https://www.amamanualofstyle.com:443/view/10.1093/jama/9780195176339.001.0001/med-9780195176339-div2-361?print=pdf
9780195176339;10.1093/jama/9780195176339.001.0001;10.1093/jama/9780195176339.001.0001;10.1093/jama/9780195176339.001.0001;REF;PDF;https://www.amamanualofstyle.com:443/view/10.1093/jama/9780195176339.001.0001/med-9780195176339-div2-362?print=pdf
;;AMA%20MoS%209-2015%20Quiz;AMA%20MoS%209-2015%20Quiz;REF;PDF;https://www.amamanualofstyle.com:443/fileasset/files/quizzes/AMA%20MoS%209-2015%20Quiz.pdf
;;References_Answers_final;References_Answers_final;REF;PDF;https://www.amamanualofstyle.com:443/fileasset/files/quizzes/References_Answers_final.pdf

[ama_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3678034/ama_log.txt)
