### ISSUE TITLE
American Economic Association (aea)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#226]
### Example:star::star: :
https://www-aeaweb-org.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### Analysis:
http://ang.couperin.org/platforms/573b33a3778504780f6f07ba

**Comment by lisahamlett** [comment]
This is not currently on the server and needs to be pulled in from the main project.

**Comment by lisahamlett** [comment]
Has information on AnalogIST, but there's nothing for it in the main project.

**Comment by CB987** [comment]
SEARCH;HTML:
https://www.aeaweb.org:443/search?q=barton
https://www.aeaweb.org:443/search?jelCode=A12&type=Articles&q=economy
https://www.aeaweb.org:443/journals/search-results?within%5Btitle%5D=on&within%5Babstract%5D=on&within%5Bauthor%5D=on&journal=&from=a&q=thomas

ABS;HTML;
https://www.aeaweb.org:443/articles?id=10.1257/aer.101.7.3368
https://www.aeaweb.org:443/articles?id=10.1257/aer.20170973
https://www.aeaweb.org:443/articles?id=10.1257/jel.45.1.83&within%5Btitle%5D=on&within%5Babstract%5D=on&within%5Bauthor%5D=on&journal=&from=a&q=thomas&from=j
https://www.aeaweb.org:443/articles?id=10.1257/aer.20180888&&from=f
https://www.aeaweb.org:443/articles?id=10.1257/jep.33.3.3

TOC;HTML;
https://www.aeaweb.org:443/issues/558
https://www.aeaweb.org:443/issues/508

ARTICLE;PDF;
https://www.aeaweb.org:443/articles/pdf/doi/10.1257/aer.101.7.3368 or http://pubs.aeaweb.org:80/doi/pdfplus/10.1257/aer.101.7.3368 or https://pubs.aeaweb.org:443/doi/pdfplus/10.1257/aer.101.7.3368 <- last
https://pubs.aeaweb.org:443/doi/pdfplus/10.1257/aer.20170973
https://pubs.aeaweb.org:443/doi/pdfplus/10.1257/jep.33.3.3

DATA;HTML;
https://www.aeaweb.org:443/research/charts/rising-income-inequality-china-us
https://www.aeaweb.org:443/research/charts/kidney-donor-paid-repugnant-transaction

DATASET;PDF;
https://assets.aeaweb.org:443/asset-server/articles-attachments/aer/data/dec2011/20090781_app.pdf
https://assets.aeaweb.org:443/asset-server/files/10030.pdf 

JOURNAL???;PDF;
https://www.aeaweb.org:443/full_issue.php?doi=10.1257/jep.33.3

VIDEO;HTML
https://www.aeaweb.org:443/resources/students/careers/video/career-in-economics

[aea_logs.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3506607/aea_logs.txt)
