### ISSUE TITLE
Annals of Allergy, Asthma & Immunology (Elsevier)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#227]
### Example:star::star: :
https://www-annallergy-org.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Health

### ezPAARSE
Analysis: None

**Comment by lisahamlett** [comment]
Our subscription for this is through Science Direct, not the journal website, so this no longer needs to be parsed.
