### ISSUE TITLE
Biology of Blood and Marrow Transplantation (Elsevier)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#228]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=http://www.bbmt.org

### Priority: 
Medium

### Subscriber (Library): 
Health

### ezPAARSE
Analysis: None

**Comment by lisahamlett** [comment]
Authenticates and drops proxy. Check stanza in EZproxy.

**Comment by lisahamlett** [comment]
Subscription is through Science Direct and the publisher's site is not proxied because the journal is open access.  So, there's nothing to parse.
