### ISSUE TITLE
Brachytherapy

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#229]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=http://www.brachyjournal.com

### Priority: 
Medium

### Subscriber (Library): 
Health

### ezPAARSE
Analysis: None

**Comment by lisahamlett** [comment]
Authenticates and drops proxy. Check stanza in EZproxy.

**Comment by lisahamlett** [comment]
Our subscription for this is through Clinical Key, not the journal website, so this no longer needs to be parsed.
