### ISSUE TITLE
Unbound Medicine

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#23]
Example:
www.unboundmedicine.com | Unbound Medicine
Priority:  Low
Subscriber:  Health

**Comment by lisahamlett** [comment]
[Unbound Medicine with RType.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1808948/Unbound.Medicine.with.RType.txt)

**Comment by AR-Shicheng** [comment]
I’m curious why Unbound Medicine is considered a low priority. Does that mean we have a better resource available for comparison?

**Comment by AGCooper** [comment]
This hasn't been updated in 6 years. Pretty sure it's a moot point.

Also, what is your affiliation with this repo? Most of my team are not in this repo.

Thanks!
