### ISSUE TITLE
British History Online

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#230]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=http://www.british-history.ac.uk/

www.british-history.ac.uk
british-history.ac.uk

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: None

### Note:
This is the only thing you get for this because it only uses proxy to authenticate and then drops it.
CONNECTION:MISC
https://proxy.library.emory.edu:443/connect?session=sImyB8NcFVtJAwzv&qurl=http%3a%2f%2fwww.british-history.ac.uk%2f

**Comment by lisahamlett** [comment]
Authenticates and drops proxy. Check stanza in EZproxy.

**Comment by lisahamlett** [comment]
Log:
10.110.27.250 vpZxm42OhLPkKOA lhamlet [01/Oct/2019:12:17:05 -0400] "GET http://proxy.library.emory.edu:80/usage?find=lhamlet HTTP/1.1" 200 33107 http://proxy.library.emory.edu/admin Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.27.250 kRFEUKTub1rIBwx lhamlet [01/Oct/2019:12:18:02 -0400] "GET https://proxy.library.emory.edu:443/connect?session=skRFEUKTub1rIBwx&qurl=http%3a%2f%2fwww.british-history.ac.uk%2f HTTP/1.1" 302 0 https://login.emory.edu/idp/profile/SAML2/POST/SSO?execution=e1s1 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.27.250 kRFEUKTub1rIBwx lhamlet [01/Oct/2019:12:18:03 -0400] "GET http://www.british-history.ac.uk:80/ HTTP/1.1" 301 439 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

**Comment by lisahamlett** [comment]
SEARCH;MISC
https://www.british-history.ac.uk:443/search?query=cromwell
https://www.british-history.ac.uk:443/search/place/london?query=cromwell
https://www.british-history.ac.uk:443/search/place/london/subject/administrative-and-legal?query=cromwell
https://www.british-history.ac.uk:443/search/place/london/subject/administrative-and-legal/result-type/book-section?query=cromwell
https://www.british-history.ac.uk:443/search/series/jrnl-trade-plantations
https://www.british-history.ac.uk:443/search/series/cal-state-papers--venice
https://www.british-history.ac.uk:443/search/series/rushworth-papers

TOC;HTML
https://www.british-history.ac.uk:443/catalogue
https://www.british-history.ac.uk:443/catalogue/maps
https://www.british-history.ac.uk:443/catalogue/south-east
https://www.british-history.ac.uk:443/using-bho
https://www.british-history.ac.uk:443/using-bho/subject-guides
https://www.british-history.ac.uk:443/using-bho/biography-guide

https://www.british-history.ac.uk:443/no-series/dict-english-furniture-makers
https://www.british-history.ac.uk:443/no-series/vestry-mins-colechurch-1613-72
https://www.british-history.ac.uk:443/cal-state-papers/venice/vol3
https://www.british-history.ac.uk:443/rushworth-papers/vol2

BOOK_SECTION;HTML
https://www.british-history.ac.uk:443/cal-state-papers/venice/vol3/pp152-159
https://www.british-history.ac.uk:443/rushworth-papers/vol2/pp319-378

**Comment by lisahamlett** [comment]
[BHO_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3865537/BHO_log.txt)
