### ISSUE TITLE
China Maxx

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#232]
### Example:star::star: :
http://www.chinamaxx.net.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: None

**Comment by lisahamlett** [comment]
SEARCH;MISC
http://www.chinamaxx.net:80/GetBooks.action?isshowall=off&classNumber=0G
http://www.chinamaxx.net:80/SearchBooks.action

BOOK_SECTION;HTML
http://www.chinamaxx.net:80/goPngRead.jsp?d=8EA41D886B7150931D74A51D840CD7C5&ssid=10005014&pagetype=1&sp=1&ep=-1

out-unitid;out-rtype;out-mime;in-url
;SEARCH;MISC;http://www.chinamaxx.net:80/GetBooks.action?isshowall=off&classNumber=0G
;SEARCH;MISC;http://www.chinamaxx.net:80/SearchBooks.action
10005014;BOOK_SECTION;HTML;http://www.chinamaxx.net:80/goPngRead.jsp?d=8EA41D886B7150931D74A51D840CD7C5&ssid=10005014&pagetype=1&sp=1&ep=-1

[chinamaxx_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4037791/chinamaxx_log.txt)
