### ISSUE TITLE
Digitalia

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#233]
### Example:star::star: :
http://www.digitaliapublishing.com.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by CB987** [comment]
[Digitalia_logs.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4055950/Digitalia_logs.txt)

Keyword search results only yield a POST request, not a GET, and it just says /fulltext or /advancedsearchresults

SEARCH;HTML; -Searching with a filter gets a GET
http://www.digitaliapublishing.com:80/fulltext/filter/tipo/0

SEARCH;HTML; More like a browse from pre-defined topics on the site
http://www.digitaliapublishing.com:80/co/1392
http://www.digitaliapublishing.com:80/co/721
http://www.digitaliapublishing.com:80/ejournals/119/art
http://www.digitaliapublishing.com:80/s/98/language-and-linguistics
http://www.digitaliapublishing.com:80/s/100

TOC;HTML; 
http://www.digitaliapublishing.com:80/a/34355/12-arquitectos-contemporaneos (book)
http://www.digitaliapublishing.com:80/a/39177/gestion-de-grandes-proyectos-urbanos-en-espacios-metropolizados---los-sistemas-integrados-de-transporte-masivo-en-colombia
http://www.digitaliapublishing.com:80/a/19774/ajoblanco-segunda-etapa-n.-116 (journal)
http://www.digitaliapublishing.com:80/a/3986/secuencias-no.-25 (journal)
http://www.digitaliapublishing.com:80/a/21321/anuario-musical-numero-66
http://www.digitaliapublishing.com:80/a/3762/metaliteratura-y-metaficcion--balance-critico-y-perspectivas-comparadas (journal)

ABSTRACT;HTML; the same as a TOC for a book
http://www.digitaliapublishing.com:80/a/51807/pediatric-nutrition--7th-ed.-
http://www.digitaliapublishing.com:80/a/43538/adivina--o-te-devoro---el-enigma-de-los-simbolos

BOOK;PDF;
http://www.digitaliapublishing.com:80/visor/51807
http://www.digitaliapublishing.com:80/visor/34355

BOOK;HTML;
http://www.digitaliapublishing.com:80/visorswf/518073
http://www.digitaliapublishing.com:80/visorswf/34355

BOOK;EPUB;
http://www.digitaliapublishing.com:80/visorepub/43538
http://www.digitaliapublishing.com:80/visorepub/45558

JOURNAL;PDF;
http://www.digitaliapublishing.com:80/visor/3987
http://www.digitaliapublishing.com:80/visor/3762

JOURNAL;HTML;
http://www.digitaliapublishing.com:80/visorswf/3987
http://www.digitaliapublishing.com:80/visorswf/3762

BOOKPAGE;PDF;
http://www.digitaliapublishing.com:80/index.jsp?o=501&id=45558&page=301
http://www.digitaliapublishing.com:80/index.jsp?o=501&id=7959&page=123

BOOKPAGE;HTML;
http://www.digitaliapublishing.com:80/visorpagehtml/51807_2.page
http://www.digitaliapublishing.com:80/visorpagehtml/51807_81.page?resolution=200
http://www.digitaliapublishing.com:80/visorpagehtml/34355_3.page

JOURNALPAGE;PDF;
http://www.digitaliapublishing.com:80/index.jsp?o=501&id=3762&page=101
http://www.digitaliapublishing.com:80/index.jsp?o=501&id=19774&page=2

JOURNALPAGE;HTML;
http://www.digitaliapublishing.com:80/visorpagehtml/3762_16.page
http://www.digitaliapublishing.com:80/visorpagehtml/41628_101.page

BOOK;AUDIO;
http://www.digitaliapublishing.com:80/visorreadspeaker/34355
http://www.digitaliapublishing.com:80/visorreadspeaker/39177

JOURNAL;AUDIO;
http://www.digitaliapublishing.com:80/visorreadspeaker/19774
http://www.digitaliapublishing.com:80/visorreadspeaker/21321

**Comment by CB987** [comment]
there's a couple things which may be just me not remembering-- but the way this site does the urls but also just the presentation of the material is that a full journal is the same as a full book, and then within that the only subsection is a single page, not article or chapter or anything. so i made everything a book, since there's no journal mime anyway, and then a book_section for the pages.
