### ISSUE TITLE
Edinburgh University Press (eup)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#235]
### Example:star::star: :
https://www-euppublishing-com.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE:
http://ang.couperin.org/platforms/573af3a6a85b45ad78bd5a3a

**Comment by lisahamlett** [comment]
Has information on AnalogIST, but there's nothing for it in the main project.

**Comment by CB987** [comment]
SEARCH;HTML;
https://www.euppublishing.com:443/action/doSearch?startPage=0&field1=AllField&text1=barton&Ppub=&Ppub=&AfterMonth=&AfterYear=&BeforeMonth=&BeforeYear=&earlycite=on
https://www.euppublishing.com:443/action/doSearch?AllField=puffins&ConceptID=
https://www.euppublishing.com:443/action/doSearch?AllField=10.3366%2Fanh.2018.0477&ConceptID=

TOC;HTML;
https://www.euppublishing.com:443/toc/anh/45/1
https://www.euppublishing.com:443/toc/afg/current
https://www.euppublishing.com:443/toc/drs/36/1

REF;HTML;
https://www.euppublishing.com:443/doi/ref/10.3366/anh.2018.0485
https://www.euppublishing.com:443/doi/ref/10.3366/drs.2018.0218

ABS;HTML;
https://www.euppublishing.com:443/doi/abs/10.3366/jshs.2005.25.1.73
https://www.euppublishing.com:443/doi/abs/10.3366/anh.2018.0477
https://www.euppublishing.com:443/doi/abs/10.3366/E1471576708000211
https://www.euppublishing.com:443/doi/abs/10.3366/anh.2014.0206?journalCode=anh

ARTICLE;HTML;
https://www.euppublishing.com:443/doi/full/10.3366/anh.2018.0485
https://www.euppublishing.com:443/doi/full/10.3366/vic.2015.0194
https://www.euppublishing.com:443/doi/full/10.3366/drs.2018.0218

ARTICLE;PDF;
https://www.euppublishing.com:443/doi/pdfplus/10.3366/jshs.2005.25.1.73
https://www.euppublishing.com:443/doi/pdfplus/10.3366/anh.2018.0477

[eup_logs.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3506601/eup_logs.txt)
