### ISSUE TITLE
Foundation Center (Candid)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#236]
### Example:star::star: :
http://foundationcenter.org.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: None

**Comment by lisahamlett** [comment]
This is now Candid and the link redirects to https://candid.org/?fcref=lr and drops proxy.
I cannot find a link to either Foundation Center or Candid in any of our sites, so I am going to close this for now and we can reevaluate if it comes up again.
