### ISSUE TITLE
HAPI

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#237]
### Example:star::star: :
http://hapi.ucla.edu.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;MISC
http://hapi.ucla.edu:80/search/
http://hapi.ucla.edu:80/search/advanced

CITATION;HTML
http://hapi.ucla.edu:80/article/citation/348313

[hapi.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4042715/hapi.txt)
