### ISSUE TITLE
American Journal of Roentgenology (ajr)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#238]
### Example:star::star: :
https://www-ajronline-org.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE:
http://ang.couperin.org/platforms/573b35a6da1293796946c5ad

**Comment by lisahamlett** [comment]
Has information on AnalogIST, but there's nothing for it in the main project.

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://www.ajronline.org:443/action/doSearch?AllField=brain
https://www.ajronline.org:443/action/doSearch?AllField=brain&Title=&Contrib=&PubIdSpan=&AfterMonth=&AfterYear=2004&BeforeMonth=&BeforeYear=2012
https://www.ajronline.org:443/action/showCollection?collection=&AllField=brain
https://www.ajronline.org:443/keyword/Mesothelioma
https://www.ajronline.org:443/page/collections
https://www.ajronline.org:443/topic/hcp1

TOC;HTML
https://www.ajronline.org:443/loi/ajr
https://www.ajronline.org:443/toc/ajr/current
https://www.ajronline.org:443/toc/ajr/212/2

ABS;HTML
https://www.ajronline.org:443/doi/abs/10.2214/AJR.07.2073

ARTICLE;HTML
https://www.ajronline.org:443/doi/full/10.2214/AJR.07.2073

ARTICLE;PDF
https://www.ajronline.org:443/doi/pdf/10.2214/AJR.07.2073

ARTICLE;PDFPLUS
https://www.ajronline.org:443/doi/pdfplus/10.2214/AJR.07.2073

SUPPL;HTML
https://www.ajronline.org:443/doi/suppl/10.2214/AJR.18.20111

SUPPL;PDF
https://www.ajronline.org:443/doi/suppl/10.2214/AJR.18.20111/suppl_file/02_18_20111_suppdata_s01.pdf

IMAGE;MISC
https://www.ajronline.org:443/na101/home/literatum/publisher/arrs/journals/content/ajr/2007/ajr.2007.189.issue-1/ajr.07.2073/production/images/medium/07_2073_01a.jpeg
https://www.ajronline.org:443/na101/home/literatum/publisher/arrs/journals/content/ajr/2007/ajr.2007.189.issue-1/ajr.07.2073/production/images/large/07_2073_01a.jpeg

VIDEO;MISC
https://www.ajronline.org:443/doi/suppl/10.2214/AJR.17.19456/suppl_file/09_17_19456_suppdata_s01.mp4

REF;HTML
https://www.ajronline.org:443/doi/ref/10.2214/AJR.18.20672

CITATION;HTML
https://www.ajronline.org:443/action/showCitFormats?doi=10.2214%2FAJR.07.2073

[ajr_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3511002/ajr_log.txt)
[ajr_test.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3511003/ajr_test.txt)

**Comment by AGCooper** [comment]
There is something about this parser that ezpaarse does not like. When I run it on the server with a full log file the process fails, when I remove the ajr parser things work again.

**Comment by lisahamlett** [comment]
@AGCooper Do you think it's a problem with the parser or the log?

**Comment by lisahamlett** [comment]
I'm going to put this in the parking lot for the month because I need Alex's help with it and he's about to leave for 3 weeks.  We can pick it back up in Project N.
