### ISSUE TITLE
Wiley (wiley)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#24]
Missing Domains:
aap.onlinelibrary.wiley.com
aapm.onlinelibrary.wiley.com
accp1.onlinelibrary.wiley.com
accpjournals.onlinelibrary.wiley.com
afspubs.onlinelibrary.wiley.com
aiche.onlinelibrary.wiley.com
anatomypubs.onlinelibrary.wiley.com
aocs.onlinelibrary.wiley.com
aornjournal.onlinelibrary.wiley.com
api.wiley.com
aps.onlinelibrary.wiley.com
as.wiley.com
asbmr.onlinelibrary.wiley.com
asi.onlinelibrary.wiley.com
asistdl.onlinelibrary.wiley.com
authorservices.wiley.com
awwa.onlinelibrary.wiley.com
besjournals.onlinelibrary.wiley.com
beva.onlinelibrary.wiley.com
binarystore.wiley.com
bjssjournals.onlinelibrary.wiley.com
bpspubs.onlinelibrary.wiley.com
bsapubs.onlinelibrary.wiley.com
bsppjournals.onlinelibrary.wiley.com
ceramics.onlinelibrary.wiley.com
cochranelibrary-wiley.com
conbio.onlinelibrary.wiley.com
currentprotocols.onlinelibrary.wiley.com
customer.wiley.com
doi.wiley.com
efsa.onlinelibrary.wiley.com
ejpr.onlinelibrary.wiley.com
esajournals.onlinelibrary.wiley.com
esj-journals.onlinelibrary.wiley.com
febs.onlinelibrary.wiley.com
headachejournal.onlinelibrary.wiley.com
hub.wiley.com
ila.onlinelibrary.wiley.com
iubmb.onlinelibrary.wiley.com
jlb.onlinelibrary.wiley.com
londmathsoc.onlinelibrary.wiley.com
maint.onlinelibrary.wiley.com
media.wiley.com
movementdisorders.onlinelibrary.wiley.com
news.wiley.com
newsroom.wiley.com
ngwa.onlinelibrary.wiley.com
nph.onlinelibrary.wiley.com
nyaspubs.onlinelibrary.wiley.com
obgyn.onlinelibrary.wiley.com
olabout.wiley.com
onlinelibrarystatic.wiley.com
ordering.onlinelibrary.wiley.com
physoc.onlinelibrary.wiley.com
professor.wiley.com
rai.onlinelibrary.wiley.com
rgs-ibg.onlinelibrary.wiley.com
rmets.onlinelibrary.wiley.com
rsaiconnect.onlinelibrary.wiley.com
rss.onlinelibrary.wiley.com
rss.onlinelibrary.wiley.com.pericles-stag.literatumonline.com
secure.cochranelibrary-wiley.com
secure.onlinelibrary.wiley.com
secure.wiley.com
setac.onlinelibrary.wiley.com
sfamjournals.onlinelibrary.wiley.com
sigmapubs.onlinelibrary.wiley.com
spssi.onlinelibrary.wiley.com
srcd.onlinelibrary.wiley.com
stemcellsjournals.onlinelibrary.wiley.com
uat.hub.wiley.com
wildlife.onlinelibrary.wiley.com
wires.wiley.com
wol1.onlinelibrary.wiley.com
wolbookstore.wiley.com
www.onlinelibrary.wiley.com
www.wileyhealthlearning.com
www.wileyopenaccess.com
www3.interscience.wiley.com
zslpublications.onlinelibrary.wiley.com

Priority:  High
Subscriber:  Shared
Tech Notes:  
Part of   Wiley parser; articles are offered up by onlinelibrary.wiley.com

**Comment by AGCooper** [comment]
@eipeele How do you want to handle the review process where I am not committing to the repo?

**Comment by lisahamlett** [comment]
https://trello.com/c/zJTlQ9Ic/16-wiley-wiley
http://ang.couperin.org/platforms/53ccdeecd5f7b93cbe52da1c
http://ang.couperin.org/platforms/5a61a9c522d6262a99be1c2b

**Comment by lisahamlett** [comment]
[Wiley.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1873094/Wiley.txt)

**Comment by AGCooper** [comment]
Looks like the ezpaarse community is already working on these: https://trello.com/c/soKIX3nz/451-wiley-2018-wiley-2018

**Comment by AGCooper** [comment]
Will move this to the parking lot.

**Comment by lisahamlett** [comment]
Updating to international repo.  Will see if there's still fallout in the missing domains file going forward.
