### ISSUE TITLE
IEEE (ieee)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#240]
### Example:star::star: :
https://www-ieee-org.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE:
http://ang.couperin.org/platforms/5409b83eadee407e1d8afe7d

**Comment by lisahamlett** [comment]
Needs PKB update from main project.

**Comment by lisahamlett** [comment]
@CB987 Remind me to use this to teach you about PKBs.

**Comment by lisahamlett** [comment]
Main project parser: https://github.com/ezpaarse-project/ezpaarse-platforms/tree/master/ieee
Our parser: https://github.com/emory-libraries/ezpaarse-platforms/tree/master/ieee

Need to update manifest and parser.
Need to update scraper.
Need to add missing PKBs.

**Comment by CB987** [comment]
I *think* I got everything-- but the TOC I added may be wrong; I wasn't sure which url to parse. 

ANNOYINGLY NOT PARSING
SEARCH;HTML;
https://www.ieee.org:443/searchresults/index.html?q=barton
https://ieeexplore.ieee.org:443/search/searchresult.jsp?newsearch=true&queryText=flower
https://ieeexplore.ieee.org:443/search/searchresult.jsp?contentType=books&queryText=water&highlight=true&returnType=SEARCH&returnFacets=ALL
REF;HTML;
https://ieeexplore.ieee.org:443/xpl/dwnldReferences?arnumber=8475993
IMAGE;MISC;
https://ieeexplore.ieee.org:443/rest/document/8475993/figures
BOOK;HTML;
https://ieeexplore.ieee.org:443/book/8040335
TOC;HTML;
https://ieeexplore.ieee.org:443/rest/publication/home/metadata?pubid=3533

ALREADY PARSING
ARTICLE;HTML; https://ieeexplore.ieee.org:443/document/8476057/
ARTICLE;PDF; https://ieeexplore.ieee.org:443/stamp/stamp.jsp?tp=&arnumber=8475993

[ieee_logs.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3536168/ieee_logs.txt)
