### ISSUE TITLE
Journal of Food Protection

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#241]
### Example:star::star: :
https://jfoodprotection-org.proxy.library.emory.edu/

www.jfoodprotection.org
jfoodprotection.org

### Priority: 
Medium

### Subscriber (Library): 
Health

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
Main links are through Proquest, but we still have links to the journal site, so I am going to go ahead and parse it.

**Comment by lisahamlett** [comment]
SEARCH;MISC
https://jfoodprotection.org:443/keyword/Bioaccumulation
https://jfoodprotection.org:443/action/doSearch?AllField=potato

TOC;HTML
https://jfoodprotection.org:443/toc/food/83/1
https://jfoodprotection.org:443/loi/food

ABS;HTML
https://jfoodprotection.org:443/doi/abs/10.4315/0362-028X.JFP-19-318

ARTICLE;HTML
https://jfoodprotection.org:443/doi/full/10.4315/0362-028X.JFP-19-318

ARTICLE;PDF
https://jfoodprotection.org:443/doi/pdf/10.4315/0362-028X.JFP-19-318

CITATION;HTML
https://jfoodprotection.org:443/action/showCitFormats?doi=10.4315%2F0362-028X.JFP-19-318

[jfoodprotection.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4042792/jfoodprotection.txt)
