### ISSUE TITLE
Journal of Vascular and Interventional Radiology (WHSCL 8)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#246]
### Example:star::star: :

https://login.proxy.library.emory.edu/login?url=https://www.jvir.org/

### Priority: 
Medium

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
JVIR seems to be part of Elsevier, but it has its own domain information.

**Comment by lisahamlett** [comment]
JVIR is not set up to proxy, so I need to add a stanza for that first.

**Comment by lisahamlett** [comment]
TOC, HTML
https://www.jvir.org:443/current
https://www.jvir.org:443/issue/S1051-0443(16)X0004-8

ARTICLE, HTML
https://www.jvir.org:443/article/S1051-0443(18)31582-3/fulltext
https://www.jvir.org:443/article/S1051-0443(16)30714-X/fulltext

ARTCILE, PDF
https://www.jvir.org:443/article/S1051-0443(18)31582-3/pdf
https://www.jvir.org:443/article/S1051-0443(16)30714-X/pdf

SUPPLEMENT, HTML
https://www.jvir.org:443/article/S1051-0443(16)30566-8/addons
https://www.jvir.org:443/action/showFullTextImages?pii=S1051-0443%2816%2930566-8

SUPPLEMENT, VIDEO
https://www.jvir.org:443/cms/10.1016/j.jvir.2016.09.028/attachment/58dd870f-e7e3-40e9-afed-1897cd74fe9c/mmc2.mp4
https://www.jvir.org:443/cms/10.1016/j.jvir.2016.09.028/attachment/8f4a8bdc-6d6a-4fb2-a962-2d5691cfd0c6/mmc1.mp4

SEARCH, HTML
https://www.jvir.org:443/action/doSearchSecure?searchType=quick&searchText=potato&occurrences=all&journalCode=jvir&searchScope=fullSite
https://www.jvir.org:443/action/doSearch?occurrences=all&searchText=brain&searchType=quick&searchScope=fullSite&journalCode=jvir

[jvir log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2877439/jvir.log.txt)
