### ISSUE TITLE
Add Oxford Academic to Oxford University Press

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#248]
### Example:star::star: :
https://academic-oup-com.proxy.library.emory.edu/nutritionreviews
https://academic-oup-com.proxy.library.emory.edu/sleep

### Priority: 
Medium

### Subscriber (Library): 
Health

### ezPAARSE:
http://ang.couperin.org/platforms/54116a16acd3da4c1bec5684

**Comment by lisahamlett** [comment]
Oxford Academic is already on SilverChair
