### ISSUE TITLE
Thieme

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#25]
Example: 
ebooks.thieme.com
Priority:  Low
Subscriber:  Health

**Comment by lisahamlett** [comment]
Not much for this one:

SEARCH, HTML
https://medone-education.thieme.com:443/cp/search;;searchterm=gunshot
https://medone-education.thieme.com:443/cp/search;content_type=ebook;searchterm=gunshot
https://medone-education.thieme.com:443/cp/search;content_type=ebook;searchterm=parasite
https://medone-education.thieme.com:443/cp/search;content_type=images
https://medone-education.thieme.com:443/cp/search;content_type=images;content_ids=1210827
https://medone-education.thieme.com:443/cp/search;content_type=images;content_ids=1929703
 
EBOOK, HTML
https://medone-education.thieme.com:443/ebooks/1210827
https://medone-education.thieme.com:443/ebooks/1929703
https://medone-education.thieme.com:443/ebooks/2156930
https://medone-education.thieme.com:443/ebooks/2193980
 
BIO, HTML
https://medone-education.thieme.com:443/p/author/profile/0000400241
https://medone-education.thieme.com:443/p/author/profile/8000000454
 
IMAGE, HTML
https://medone-education.thieme.com:443/media/2156930/ebook_2156930_SL82197621/im2156903
https://medone-education.thieme.com:443/media/2156930/ebook_2156930_SL82197621/im2156904
(NOTE: These give an error if you try to   go directly to the link, but that's how they show in the log.)

**Comment by AGCooper** [comment]
:+1:

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/54364d18f800ce6eff8d1350
https://trello.com/c/RbfcgEuu/117-thieme-thieme
