### ISSUE TITLE
The Clinics (Elsevier)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#250]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=https://www.theclinics.com/
https://proxy.library.emory.edu/login?url=https://www.neurosurgery.theclinics.com/
https://proxy.library.emory.edu/login?url=https://www.oto.theclinics.com/

### Priority: 
Medium

### Subscriber (Library): 
Health

### ezPAARSE
Analysis: None

**Comment by lisahamlett** [comment]
Needs to be added to EZproxy.

**Comment by lisahamlett** [comment]
Our subscription for this is through Science Direct, not the journal website, so this no longer needs to be parsed.

**Comment by lisahamlett** [comment]
Reopening because there _are_ actually links in Science Direct that pull you back to to journal website and you can access articles from there.

**Comment by lisahamlett** [comment]
Closing again because this no longer proxies and seems to be all open source.  Will reopen if it shows up on missing domains.

**Comment by lisahamlett** [comment]
By open source, I mean open access...
