### ISSUE TITLE
NK News - North Korea News, Analysis, Data & Opinion

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#253]
### Example:star::star: :
https://www-nknews-org.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
This is a horrible website.  Clicking authors and articles sometimes drops proxy.  Or it times out.  I can't tell...

SEARCH;MISC
https://www.nknews.org:443/?s=books&sort=date&start=01-01-2010&end=10-01-2020

TOC;HTML
https://www.nknews.org:443/category/news/
https://www.nknews.org:443/category/news/page/2/
https://www.nknews.org:443/category/featured-content/interview/
https://www.nknews.org:443/category/featured-content/interview/page/2/
https://www.nknews.org:443/category/nk-voices/defector-survey-2014/
https://www.nknews.org:443/tag/culture/
https://www.nknews.org:443/tag/culture/page/2/
https://www.nknews.org:443/gallery/
https://www.nknews.org:443/gallery/page/2/

ARTICLE;HTML
https://www.nknews.org:443/2020/01/kim-jong-un-turns-36-but-north-korea-is-conspicuously-silent-about-the-big-day/

BIO;HTML
https://www.nknews.org:443/content_author/oliver-hotham/

DATASET;MISC
https://www.nknews.org:443/pro/north-korea-company-database/

[nknews.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4047362/nknews.txt)
