### ISSUE TITLE
Mobile Sage Journals

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#254]
### Example:star::star: :
m.nsq.sagepub.com (Nursing   Science Quarterly: SAGE Journals)
m.msj.sagepub.com (Multiple Sclerosis Journal)
m.jia.sagepub.com (Journal of the International Association of Providers of AIDS Care (JIAPAC))
m.jhl.sagepub.com (Journal of Human Lactation)
m.ncp.sagepub.com (Nutrition in Clinical Practice)
m.ajs.sagepub.com (The American Journal of Sports Medicine)

### Priority: 
Medium

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
These webpages are no longer relevant.  They are dead links.
