### ISSUE TITLE
SIAM (siam)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#258]
### Example:star::star: :
https://www-siam-org.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/565d788344d4ba734b6613e1

**Comment by CB987** [comment]
SEARCH;HTML;
(parses as TOC)
https://epubs.siam.org:443/action/doSearch?AllField=physics&publication=  
https://epubs.siam.org:443/action/doSearch?publication=40000029
(don't parse)
https://epubs.siam.org:443/keyword/Conservation+Laws
https://epubs.siam.org:443/action/showPublications?pubType=book&category=10.1555/category.40000049&expand=10.1555/category.40000049
https://epubs.siam.org:443/action/showPublications?pubType=proceedings&category=10.1555/category.40105910&expand=10.1555/category.40105910

TOC;HTML; (doesn't parse)
https://epubs.siam.org:443/toc/sjcodc/13/6
https://epubs.siam.org:443/toc/mmsubt/17/2
https://epubs.siam.org:443/toc/smjmap.1/4/4
https://epubs.siam.org:443/page/locus
https://epubs.siam.org:443/doi/book/10.1137/1.9781611972863"  (gives "unitid":"1","doi":"10.1137/1")
https://epubs.siam.org:443/doi/book/10.1137/1.9781611975529 (print_identifier should be 9781611975529)

ABS;HTML:
https://epubs.siam.org:443/doi/abs/10.1137/1.9781611975529.ch1
{"rtype":"ABS","mime":"HTML","unitid":"1","doi":"10.1137/1"} should also include print_identifier 

REF;HTML; (doesn't parse)
https://epubs.siam.org:443/journal/mmsubt 
https://epubs.siam.org:443/journal/sjmaah

BOOK_SECTION;PDF;
https://epubs.siam.org:443/doi/pdf/10.1137/1.9781611975529.fm (parses as article, pdf... print_identifier should be 9781611975529)
https://epubs.siam.org:443/doi/pdf/10.1137/1.9781611975529.ch1 ({"rtype":"ARTICLE","mime":"PDF","unitid":"1","doi":"10.1137/1"} should be BOOK_SECTION and print_identifier)

[siam_logs.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3427636/siam_logs.txt)
