### ISSUE TITLE
STAT!Ref - The premier healthcare e-source (WHSCL 1)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#259]
### Example:star::star: :

www.statref.com
online.statref.com

### Priority: 
Medium

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
CONNECTION/SESSION
http://online.statref.com:80/Entry.aspx?lt=Login&SessionId=2A3CA04RKSRWLWKO

BOOK CHAPTER, HTML
http://online.statref.com:80/Document.aspx?docAddress=SaoWxNG8S1byvtPckclkVw!!&SessionId=2A3CA04RKSRWLWKO
http://online.statref.com:80/WebAPI/DocumentContent.aspx?docAddress=ABmTduPEbRVg-3K7Xv3KyA!!&cacheNumber=1538596021885&SessionID=2A3CA04RKSRWLWKO&dl=true
http://online.statref.com:80/WebAPI/DocumentContent.aspx?docAddress=UiOkn4cmIzV8x2YnFFDQYw!!&cacheNumber=1538596021885&SessionID=2A3CA04RKSRWLWKO&dl=true
http://online.statref.com:80/WebAPI/BookTitle.aspx?SessionID=2A3CA04RKSRWLWKO&FxID=15
http://online.statref.com:80/WebAPI/BookTitle.aspx?SessionID=2A3CA04RKSRWLWKO&FxID=99

BOOK CHAPTER, PDF
http://online.statref.com:80/Media.aspx?SessionID=2A3CA04RKSRWLWKO&Title=ACPM&Media=PDF/1014.pdf
http://online.statref.com:80/Media.aspx?SessionID=2A3CA04RKSRWLWKO&Title=ACPM&Media=PDF/1415.pdf

SEARCH, HTML
http://online.statref.com:80/Results.aspx?SessionID=2A3CA04RKSRWLWKO&query=potato
http://online.statref.com:80/Results.aspx?SessionID=2A3CA04RKSRWLWKO&query=mushroom

ARTICLE, PDF
http://online.statref.com:80/SplashContent/druginfoline_9_2018_min.pdf

ABSTRACT, HTML
http://online.statref.com:80/Evidence/article.aspx?article=22772&type=2&SessionID=2A3CA04RKSRWLWKO

Log: [STATRef.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2443606/STATRef.txt)
