### ISSUE TITLE
The Journal of Graduate Medical Education (WHSCL 7)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#260]
### Example:star::star: :

https://login.proxy.library.emory.edu/login?url=http://www.jgme.org/

### Priority: 
Medium

### Subscriber (Library): 
Health

**Comment by lisahamlett** [comment]
TOC, HTML
https://www.jgme.org:443/toc/jgme/11/1
https://www.jgme.org:443/toc/jgme/3/4

ARTCILE, HTML
https://www.jgme.org:443/doi/full/10.4300/JGME-D-18-01093.1
https://www.jgme.org:443/doi/full/10.4300/JGME-D-11-00221.1

ARTCICLE, PDF
https://www.jgme.org:443/doi/pdf/10.4300/JGME-D-18-01093.1
https://www.jgme.org:443/doi/pdf/10.4300/JGME-D-11-00221.1

SUPPLEMENT, JPEG
https://www.jgme.org:443/na101/home/literatum/publisher/pinnacle/journals/content/jgme/2019/19498357-11.1/jgme-d-18-01093.1/20190211/images/large/i1949-8357-11-1-1-t01.jpeg
https://www.jgme.org:443/na101/home/literatum/publisher/pinnacle/journals/content/jgme/2019/19498357-11.1/jgme-d-18-01093.1/20190211/images/large/i1949-8357-11-1-1-f02.jpeg

SEARCH, HTML
https://www.jgme.org:443/action/doSearch?AllField=potato
https://www.jgme.org:443/action/doSearch?AllField=brain
https://www.jgme.org:443/action/doSearch?displaySummary=true&Contrib=&Title=&Keyword=toddler&AllField=brain&Abstract=&PubIdSpan=&AfterMonth=&AfterYear=&BeforeMonth=&BeforeYear=&search=Search

[JGME Log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2877387/JGME.Log.txt)
