### ISSUE TITLE
The Medical Letter Home Page | The Medical Letter, Inc.

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#261]
### Example:star::star: :
https://secure-medicalletter-org.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Health

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;MISC
https://secure.medicalletter.org:443/solrsearch?query=brain&x=21&y=8
https://secure.medicalletter.org:443/most-read

TOC;HTML
https://secure.medicalletter.org:443/archives-tml?y=2014
https://secure.medicalletter.org:443/archives-tgl?y=2014
https://secure.medicalletter.org:443/TML2020FR

ARTICLE;HTML
https://secure.medicalletter.org:443/TML-issue-1589
https://secure.medicalletter.org:443/TML-article-1542b
https://secure.medicalletter.org:443/TG-article-138a

ARTICLE;PDF
https://secure.medicalletter.org:443/system/files/private/TML-issue-1589.pdf

[medicalletter.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4043339/medicalletter.txt)
