### ISSUE TITLE
Westlaw Sign In | Thomson Reuters (westlaw)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#263]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=https://1.next.westlaw.com/Search/Home.html?rs=IWLN1.0&vr=3.0&sp=002057769-2100

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
http://ang.couperin.org/platforms/54aa79e403c3239495447244
Says analysis unfeasible.  I think we can do it though.

**Comment by lisahamlett** [comment]
To access this one, go to the A-Z databases and search for "Westlaw Campus Research"

YOU CANNOT ACCESS IT THROUGH THE DIRECT LINK!

**Comment by lisahamlett** [comment]
This is not currently on the server and needs to be pulled in from the main project.

**Comment by lisahamlett** [comment]
CONNECTION;MISC
https://1.next.westlaw.com:443/V1/Session/GetSponsorInformation?sp=002057769-2100

SEARCH;HTML
https://1.next.westlaw.com:443/Search/Results.html?query=potato&jurisdiction=ALLFEDS&saveJuris=False&contentType=ALL&querySubmissionGuid=i0ad73aa60000016c77e58060f3cc3f9b&startIndex=1&searchId=i0ad73aa60000016c77e58060f3cc3f9b&kmSearchIdRequested=False&simpleSearch=False&isAdvancedSearchTemplatePage=False&skipSpellCheck=False&isTrDiscoverSearch=False&thesaurusSearch=False&thesaurusTermsApplied=False&ancillaryChargesAccepted=False&proviewEligible=False&eventingTypeOfSearch=FRM&transitionType=Search&contextData=%28sc.Default%29

SUPPL;HTML
https://1.next.westlaw.com:443/Document/Ib8b8e0f149af11db99a18fc28eb0d9ae/View/FullText.html?navigationPath=Search%2Fv1%2Fresults%2Fnavigation%2Fi0ad73aa60000016c77e695fdf3cc4041%3FNav%3DANALYTICAL%26fragmentIdentifier%3DIb8b8e0f149af11db99a18fc28eb0d9ae%26parentRank%3D0%26startIndex%3D1%26contextData%3D%2528sc.Search%2529%26transitionType%3DSearchItem&listSource=Search&listPageSource=48b34c72dd0c419554f44da798e493cd&list=ANALYTICAL&rank=1&sessionScopeId=e6e3f86807047ec07e0f287ea176d659cd7f0ef0016e2e2b147260b6bcf910e8&originationContext=Search%20Result&transitionType=SearchItem&contextData=%28sc.Search%29

https://1.next.westlaw.com:443/Document/I4374de02468811dabbce983553c9ef8b/View/FullText.html?navigationPath=Search%2Fv1%2Fresults%2Fnavigation%2Fi0ad73aa60000016c77e695fdf3cc4041%3FNav%3DANALYTICAL%26fragmentIdentifier%3DI4374de02468811dabbce983553c9ef8b%26parentRank%3D0%26startIndex%3D1%26contextData%3D%2528sc.Search%2529%26transitionType%3DSearchItem&listSource=Search&listPageSource=48b34c72dd0c419554f44da798e493cd&list=ANALYTICAL&rank=12&sessionScopeId=e6e3f86807047ec07e0f287ea176d659cd7f0ef0016e2e2b147260b6bcf910e8&originationContext=Search%20Result&transitionType=SearchItem&contextData=%28sc.Search%29

REF;HTML
https://1.next.westlaw.com:443/RelatedInformation/I4374de02468811dabbce983553c9ef8b/kcCitingReferences.html?docSource=b387ed47aac34d0b8b5a26a3e52f4e71&rank=12&facetGuid=h41554ea1965e1d2fac01b1e102fb72a7&originationContext=citingreferences&transitionType=CitingReferences&contextData=%28sc.Search%29

https://1.next.westlaw.com:443/RelatedInformation/I4374de02468811dabbce983553c9ef8b/kcTableOfAuthorities.html?originationContext=citingReferences&transitionType=TableOfAuthorities&contextData=(sc.Search)&docSource=b387ed47aac34d0b8b5a26a3e52f4e71&rank=12&rulebookMode=false

**Comment by lisahamlett** [comment]
[Westlaw.log](https://github.com/emory-libraries/ezpaarse-platforms/files/3487846/Westlaw.log)
