### ISSUE TITLE
AtoZdatabases: Target Company Lists

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#264]
### Example:star::star: :
https://www-atozdatabases-com.proxy.library.emory.edu

www.atozdatabases.com
atozdatabases.com

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
This site is crap.

SEARCH;MISC
https://www.atozdatabases.com:443/search
https://www.atozdatabases.com:443/ajax/getIndeedResults.htm?&Add_indeed_type=1&Add_query=&Add_location=Atlanta%2C+&Add_jobtype=-1&curDate=Thu+Jan+09+2020+18%3A48%3A45+GMT-0500+(Eastern+Standard+Time)&page=search&database=jobs&start=0
https://www.atozdatabases.com:443/ajax/cityAutocomplete.htm?city=Atlanta&database=combined&term=Atlanta

DATASET;HTML
https://www.atozdatabases.com:443/ajax/getIndeedForDetails.htm?query=company:Maias%20Books%20&%20Misc&l=Columbus,OH&sort=&radius=&st=&jt=&start=&limit=2&fromage=&filter=&latlong=1&co=us&chnl=&userip=192.27.0.5&useragent=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64;%20rv:56.0)%20Gecko/20100101%20Firefox/56.0%20Waterfox/56.3&v=2&format=json&callback=jobPortal&t=1578613626248

**Comment by lisahamlett** [comment]
There are very few GETs with this one.  It's all POSTs and scripting.  :(
