### ISSUE TITLE
Oxford Handbooks

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#265]
### Example:star::star: :
http://www.oxfordhandbooks.com.proxy.library.emory.edu/
Most recent addition is Criminology and Criminal Justice Collection
### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
SEARCH, HTML
--
http://www.oxfordhandbooks.com:80/browse?t0=ORR:AHU01560
http://www.oxfordhandbooks.com:80/browse?t0=ORR:AHU01790
http://www.oxfordhandbooks.com:80/browse?t0=ORR:SOC00070
http://www.oxfordhandbooks.com:80/browse?t0=ORR:SOC00500
http://www.oxfordhandbooks.com:80/oso/search:booktoggle/book?isQuickSearch=true&q=shakespeare&searchBtn=Search
http://www.oxfordhandbooks.com:80/search?btog=book&isQuickSearch=true&pageSize=10&q=shakespeare&sort=relevance
http://www.oxfordhandbooks.com:80/search?q=crossfire&searchBtn=Search&isQuickSearch=true
http://www.oxfordhandbooks.com:80/search?q=shakespeare&searchBtn=Search&isQuickSearch=true
 
ARTICLE, PDF
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780198713197.001.0001/oxfordhb-9780198713197-e-2?print=pdf
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199356157.001.0001/oxfordhb-9780199356157-part-2?print=pdf
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199566105.001.0001/oxfordhb-9780199566105-e-18?print=pdf
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199687169.001.0001/oxfordhb-9780199687169-e-16?print=pdf
 
TOC, HTML
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199566105.001.0001/oxfordhb-9780199566105?rskey=xO6BzS&result=1
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199733163.001.0001/oxfordhb-9780199733163
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199356157.001.0001/oxfordhb-9780199356157
 
ABSTRACT, HTML
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780195395068.001.0001/oxfordhb-9780195395068-e-33?rskey=Sj0iYI&result=1
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199211913.001.0001/oxfordhb-9780199211913-e-002?rskey=P4aJea&result=1
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199315178.001.0001/oxfordhb-9780199315178-e-24?rskey=qCDc7V&result=2
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199356157.001.0001/oxfordhb-9780199356157-e-54?rskey=vqbrA7&result=4
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199566105.001.0001/oxfordhb-9780199566105-e-10
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199566105.001.0001/oxfordhb-9780199566105-e-18?rskey=oJvf4O&result=1
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199687169.001.0001/oxfordhb-9780199687169-e-16?rskey=oJvf4O&result=5
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199733163.001.0001/oxfordhb-9780199733163-e-30?rskey=vqbrA7&result=2
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199838707.001.0001/oxfordhb-9780199838707-e-017?rskey=d63chp&result=1
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199733163.001.0001/oxfordhb-9780199733163-e-7
 
ARTICLE, HTML
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780198713197.001.0001/oxfordhb-9780198713197-e-2
http://www.oxfordhandbooks.com:80/view/10.1093/oxfordhb/9780199356157.001.0001/oxfordhb-9780199356157-part-2
