### ISSUE TITLE
Accessible Archives Complete

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#27]
#### Example:star::star: :
https://www-accessible-com.proxy.library.emory.edu

www.accessible.com
www.accessible-archives.com
accessible.com
accessible-archives.com

#### Priority: 
Low

#### Subscriber (Library): 
Woodruff

#### ezPAARSE
Analysis: None
Trello: None

**Comment by libah** [comment]
Article: ttps://www.accessible.com:443/accessible/search?AASearchForm=1&AATerm1=lynchings&AASearchInTag1=&AAOpConnectBox2=OR&AATerm2=&AASearchInTag2=&AAOpConnectBox3=OR&AATerm3=&AASearchInTag3=&AAOpConnectBox4=OR&AATerm4=&AASearchInTag4=&AALimit3=Newspapers&AALimit3=Book&AALimit3=American+Counties&AALimitStmt3=doc_type%3A+%5E&AALimit2A=&AALimit2=&AALimitHigh2=&AALimitStmt2=iso_date%3A+%5B%5E+TO+%5E%5D&AALimitStmt1=combined&AALimitStmt4=state%3A%28%2B%5E%29&AALimitStmt5=county%3A%28%2B%5E%29&AAOpConnectBox5=AND&AAOpWithinBox5=OR&AASearchInTag5=image_type&AANextPage=%2FsearchFormResults.jsp&AAErrorPage=%2FARCHIVESSimpleSearchForm.jsp

**Comment by libah** [comment]
IMAGE: https://www.accessible.com:443/accessible/docButton?AAWhat=builtPage&AAWhere=THECHRISTIANRECORDER.18930504_001.image&AABeanName=toc1&AANextPage=/printBuiltImagePage.jsp

**Comment by libah** [comment]
ARTICLE: https://www.accessible.com:443/accessible/docButton?AAWhat=builtPageIssueToc&AAWhere=THEPENNSYLVANIAGAZETTE.17560520&AABeanName=toc1&AANextPage=/printBuiltTocPage.jsp&AACheck=5.1.1.0.0 HTTP/1.1

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://www.accessible.com:443/accessible/search?[payload]
https://www.accessible-archives.com:443/collections/
https://www.accessible-archives.com:443/collections/african-american-newspapers/frederick-douglass-paper/

ARTICLE;HTML
https://www.accessible-archives.com:443/2016/02/detention-of-rebels-claiming-slaves/
https://www.accessible-archives.com:443/2020/04/womens-history-womans-tribune-1883-1909/


Where = publication title

TOC;HTML
https://www.accessible.com:443/accessible/docButton?AAWhat=builtPageIssueToc&AAWhere=GODEYSLADYSBOOK.18560100&AABeanName=toc1&AACheck=2.2050.2.0.0&AANextPage=/printBuiltTocPage.jsp
https://www.accessible.com:443/accessible/docButton?AAWhat=builtPageIssueToc&AAWhere=THENATIONALERA.18490419&AABeanName=toc1&AACheck=2.200.15.0.0&AANextPage=/printBuiltTocPage.jsp

ARTICLE;HTML
https://www.accessible.com:443/accessible/docButton?AAWhat=gotoJSP&AAWhere=2&AABeanName=toc1&AANextPage=/printerFriendlyDoc.jsp&AACheck=2.2050.2.0.0
https://www.accessible.com:443/accessible/docButton?AAWhat=gotoJSP&AAWhere=15&AABeanName=toc1&AANextPage=/printerFriendlyDoc.jsp&AACheck=2.200.15.0.0
https://www.accessible.com:443/accessible/docButton?AAWhat=builtPage&AAWhere=GODEYSLADYSBOOK.GO1856010010.00010&AABeanName=toc1&AACheck=2.2050.2.0.0&AANextPage=/printBuiltPage.jsp
https://www.accessible.com:443/accessible/docButton?AAWhat=builtPage&AAWhere=THENATIONALERA.FR1849041918.18173&AABeanName=toc1&AACheck=2.200.15.0.0&AANextPage=/printBuiltPage.jsp
https://www.accessible.com:443/accessible/docButton?AAWhat=builtPage&AAWhere=THENATIONALERA.FR1849041919.18174&AABeanName=toc1&AANextPage=/printBuiltPage.jsp
https://www.accessible.com:443/accessible/docButton?AAWhat=page&AAWhere=3&AABeanName=toc1&AANextPage=/printFullDocFromXML.jsp&AACheck=2.200.5.0.0
https://www.accessible.com:443/accessible/docButton?AAWhat=page&AAWhere=2&AABeanName=toc1&AANextPage=/printFullDocFromXML.jsp&AACheck=2.200.5.0.0

IMAGE;MISC
https://www.accessible.com:443/accessible/docButton?AAWhat=builtPage&AAWhere=GODEYSLADYSBOOK.18560100_069.image&AABeanName=toc1&AANextPage=/printBuiltImagePage.jsp
https://www.accessible.com:443/accessible/docButton?AAWhat=builtPage&AAWhere=GODEYSLADYSBOOK.18560100_012.image&AABeanName=toc1&AANextPage=/printBuiltImagePage.jsp
https://www.accessible.com:443/accessible/docButton?AAWhat=builtPage&AAWhere=THENATIONALERA.18490419_001.image&AABeanName=toc1&AANextPage=/printBuiltImagePage.jsp

[accessible.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4685506/accessible.txt)
