### ISSUE TITLE
AccessScience

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#28]
### Example:star::star: :

www.accessscience.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Nothing on ezPAARSE Trello or ang.couperin.org

**Comment by AGCooper** [comment]
@eipeele Part of High Wire platform.

**Comment by lisahamlett** [comment]
This is part of High Wire, but not on AnalogIST or in here.  It just needs to be added to High Wire.
