### ISSUE TITLE
AVON

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#281]
### Example:star::star: :
https://search.alexanderstreet.com/avon

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
SEARCH, HTML
https://search.alexanderstreet.com:443/avon/search?searchstring=bunnies&f%5B0%5D=format_facet%3AVideo
https://search.alexanderstreet.com:443/avon/search?f%5B0%5D%5B0%5D=discipline_subject_hierarchy_facet%3AAmerican%20Studies%7CAmerican%20Drama&sort_by=publication_date_sort&sort_order=DESC
https://search.alexanderstreet.com:443/avon/search?f%5B0%5D%5B0%5D=discipline_subject_hierarchy_facet%3AAmerican%20Studies%7CAmerican%20History&sort_by=publication_date_sort&sort_order=DESC

TOC, HTML
https://search.alexanderstreet.com:443/avon/browse/discipline

Any links you click on go to Alexander Street Press, which we already have a parser for.

LOG:
[AVON.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2255124/AVON.txt
