### ISSUE TITLE
Dialong

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#282]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=http://www.kaixidb.com/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: None

**Comment by lisahamlett** [comment]
Needs to be added to EZproxy.

**Comment by lisahamlett** [comment]
The only thing on this page is some type of sketchy client download.  I am not parsing that.
