### ISSUE TITLE
Theology ebscohost updates

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#285]
### Example:star::star: :
ATLA+ Religion Database + Serial; New Testament Abstracts; Old Testament Abstracts
https://proxy.library.emory.edu/login?url=http://search.ebscohost.com/login.aspx?authtype=ip,uid&custid=emu1&profile=ehost&defaultdb=lsdar&groupid=main
https://proxy.library.emory.edu/login?url=http://search.ebscohost.com/login.aspx?authtype=uid&user=emu1&password=emu1&profile=thehost&defaultdb=rvh
https://proxy.library.emory.edu/login?url=http://search.ebscohost.com/login.aspx?authtype=uid&user=emu1&password=emu1&profile=thehost&defaultdb=oah

### Priority: 
High

### Subscriber (Library): 
Theology

**Comment by lisahamlett** [comment]
ARTICLE, PDF
http://web.a.ebscohost.com:80/ehost/pdfviewer/pdfviewer?vid=4&sid=136bc65e-5714-42f2-923a-c8c6f623b01b%40sessionmgr4010
https://web.a.ebscohost.com:443/ehost/pdfviewer/pdfviewer?vid=0&sid=8af49e74-4850-4915-a19d-f9b217934e55%40sessionmgr4006
https://web.a.ebscohost.com:443/ehost/pdfviewer/pdfviewer?vid=0&sid=8d94b614-d52e-465a-858f-d540e83a51d3%40sessionmgr4006
https://web.a.ebscohost.com:443/ehost/pdfviewer/pdfviewer?vid=0&sid=f2daad45-d71f-422a-9118-ab5f91be2f06%40sessionmgr4008
https://web.a.ebscohost.com:443/ehost/pdfviewer/pdfviewer?vid=3&sid=19e71ca5-b358-4ba1-ac72-19e10887f13d%40sessionmgr4010

ABSTRACT, HTML
(These three are from the same set of results.)
https://web.a.ebscohost.com:443/ehost/detail/detail?vid=8&sid=19e71ca5-b358-4ba1-ac72-19e10887f13d%40sessionmgr4010&bdata=JnNpdGU9ZWhvc3QtbGl2ZSZzY29wZT1zaXRl
https://web.a.ebscohost.com:443/ehost/detail/detail?vid=9&sid=19e71ca5-b358-4ba1-ac72-19e10887f13d%40sessionmgr4010&bdata=JnNpdGU9ZWhvc3QtbGl2ZSZzY29wZT1zaXRl
https://web.a.ebscohost.com:443/ehost/detail/detail?vid=10&sid=19e71ca5-b358-4ba1-ac72-19e10887f13d%40sessionmgr4010&bdata=JnNpdGU9ZWhvc3QtbGl2ZSZzY29wZT1zaXRl
(These two are from a difference set of results)
https://web.a.ebscohost.com:443/ehost/detail/detail?vid=2&sid=fcc89c92-5553-4823-835f-05b3a9d8b767%40sessionmgr4008&bdata=JnNpdGU9ZWhvc3QtbGl2ZSZzY29wZT1zaXRl
https://web.a.ebscohost.com:443/ehost/detail/detail?vid=3&sid=fcc89c92-5553-4823-835f-05b3a9d8b767%40sessionmgr4008&bdata=JnNpdGU9ZWhvc3QtbGl2ZSZzY29wZT1zaXRl

SEARCH, HTML (One from each of the 3 databases)
http://web.a.ebscohost.com:80/ehost/Search/PerformSearch?sid=136bc65e-5714-42f2-923a-c8c6f623b01b@sessionmgr4010&vid=0
https://web.a.ebscohost.com:443/ehost/Search/PerformSearch?sid=2b5195ba-934b-44aa-b719-91599df111a3@sessionmgr4009&vid=0
https://web.a.ebscohost.com:443/ehost/Search/PerformSearch?sid=91ecf592-ff30-4e60-9aa3-c39731e72934@sessionmgr4009&vid=0

NOTE: Here is a full log entry for a search on Old Testament Abstracts.
I don't see anything to indicate the database.
10.110.27.161 HeLzK34FxtcCYRj lhamlet [06/Jun/2018:17:30:45 -0400] "POST https://web.a.ebscohost.com:443/ehost/Search/PerformSearch?sid=19e71ca5-b358-4ba1-ac72-19e10887f13d@sessionmgr4010&vid=5 HTTP/1.1" 302 758 https://web-a-ebscohost-com.proxy.library.emory.edu/ehost/results?vid=5&sid=19e71ca5-b358-4ba1-ac72-19e10887f13d%40sessionmgr4010&bquery=jail&bdata=JmRiPW9haCZ0eXBlPTAmc2l0ZT1laG9zdC1saXZlJnNjb3BlPXNpdGU%3d Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.27.161 HeLzK34FxtcCYRj lhamlet [06/Jun/2018:17:30:46 -0400] "GET https://web.a.ebscohost.com:443/ehost/results?vid=6&sid=19e71ca5-b358-4ba1-ac72-19e10887f13d%40sessionmgr4010&bquery=deborah&bdata=JmRiPW9haCZ0eXBlPTAmc2l0ZT1laG9zdC1saXZlJnNjb3BlPXNpdGU%3d HTTP/1.1" 200 110428 https://web-a-ebscohost-com.proxy.library.emory.edu/ehost/results?vid=5&sid=19e71ca5-b358-4ba1-ac72-19e10887f13d%40sessionmgr4010&bquery=jail&bdata=JmRiPW9haCZ0eXBlPTAmc2l0ZT1laG9zdC1saXZlJnNjb3BlPXNpdGU%3d Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.27.161 HeLzK34FxtcCYRj lhamlet [06/Jun/2018:17:30:47 -0400] "GET https://web.a.ebscohost.com:443/truesightedgemarker/!crd_prm!.!cm?crd_ver=0.9.5&crd_rnd=365749&crd_cnt=0.01&crd_tpb=1528320647157&crd_olt=700 HTTP/1.1" 200 410 https://web-a-ebscohost-com.proxy.library.emory.edu/ehost/results?vid=6&sid=19e71ca5-b358-4ba1-ac72-19e10887f13d%40sessionmgr4010&bquery=deborah&bdata=JmRiPW9haCZ0eXBlPTAmc2l0ZT1laG9zdC1saXZlJnNjb3BlPXNpdGU%3d Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

**Comment by lisahamlett** [comment]
Ebsco is a pain in the neck.

**Comment by AGCooper** [comment]
Thanks @lisahamlett but with ebscohost all we're doing apparently is building out the table of database names. Like:

``if (param.defaultdb === 'apn') {
      result.publication_title = 'Alternative Press Index';
    }``

**Comment by lisahamlett** [comment]
Aye
