### ISSUE TITLE
Ministry Matters

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#286]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=http://www.ministrymatters.com/

### Priority: 
High

### Subscriber (Library): 
Theology

**Comment by lisahamlett** [comment]
SEARCH, HTML
("romans" was 4 different kinds of searches)
https://www.ministrymatters.com:443/search/?t=a&q=romans
https://www.ministrymatters.com:443/search/?t=r&q=romans
https://www.ministrymatters.com:443/search/?t=l&q=romans
https://www.ministrymatters.com:443/search/?t=b&q=romans
https://www.ministrymatters.com:443/search/?t=a&q=masada

TOC, HTML
https://www.ministrymatters.com:443/library_beta/
https://www.ministrymatters.com:443/preach/
https://www.ministrymatters.com:443/teach/
https://www.ministrymatters.com:443/worship/
https://www.ministrymatters.com:443/reach/
https://www.ministrymatters.com:443/lead/
https://www.ministrymatters.com:443/reach/tag/evangelism
https://www.ministrymatters.com:443/lead/tag/leader_development
https://www.ministrymatters.com:443/teach/tag/vbs
https://www.ministrymatters.com:443/preach/tag/lectionary_preaching
https://www.ministrymatters.com:443/bin/14958/trinity-sunday-year-b
https://www.ministrymatters.com:443/bin/14759/books-preaching
https://www.ministrymatters.com:443/bin/14714/preaching-ideas-for-lent

ARTICLE, HTML
https://www.ministrymatters.com:443/all/entry/4521/romans-5-basic-bible-commentary
https://www.ministrymatters.com:443/all/entry/6662/who-is-jesus-christ-to-you
https://www.ministrymatters.com:443/worship/entry/2916/worship-connection-july-8-2018
https://www.ministrymatters.com:443/reach/entry/8534/a-suggestion-for-younger-evangelicals-lose-the-label
https://www.ministrymatters.com:443/lead/entry/8708/how-do-i-escape-the-mundane-and-experience-life
https://www.ministrymatters.com:443/teach/entry/6973/art-of-the-sermon-using-media-in-preaching-and-teaching
https://www.ministrymatters.com:443/teach/entry/4003/from-a-first-time-vbs-director

BOOK CHAPTER, HTML
https://www.ministrymatters.com:443/reader/9781426725845
https://www.ministrymatters.com:443/reader/9781426759734
https://www.ministrymatters.com:443/reader/9781426744259

ABSTRACT?, HTML
https://www.ministrymatters.com:443/product/9781501855146
https://www.ministrymatters.com:443/product/9780830762651
https://www.ministrymatters.com:443/product/9781501829635
