### ISSUE TITLE
Oxford Biblical Studies Online

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#287]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=http://www.oxfordbiblicalstudies.com/

### Priority: 
High

### Subscriber (Library): 
Theology

**Comment by lisahamlett** [comment]
I was mistaken... This one has a parser: https://github.com/emory-libraries/ezpaarse-platforms/issues/63
