### ISSUE TITLE
Chadwycke

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#288]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=http://luther.chadwyck.com/english/frames/home/home
Also:
http://acta.chadwyck.com (Acta Sanctorum)
http://ble.chadwyck.com (Chadwyck Bibliografia de la Literature Espanola)
http://britishperiodicals.chadwyck.co.uk (Chadwyck ProQuest British Periodicals)
http://colonial.chadwyck.com/ (Chadwyck Colonial State Papers Collection)
http://eebo.chadwyck.com (Chadwyck Early English Books Online)
http://collections.chadwyck.com (Chadwyck Literature Collections)
http://lion.chadwyck.com (Chadwyck Literature Online)
http://pld.chadwyck.co.uk (Chadwyck Patrologia Latina)

### Priority: 
High

### Subscriber (Library): 
Theology / Woodruff

**Comment by lisahamlett** [comment]
SEARCH, HTML
http://luther.chadwyck.com:80/english/frames/werke/search
http://luther.chadwyck.com:80/deutsch/frames/werke/search

TOC, HTML
http://luther.chadwyck.com:80/english/frames/werke/htxview?template=toc_hdft.htx&content=toc_top.htx
http://luther.chadwyck.com:80/deutsch/frames/werke/htxview?template=toc_hdft.htx&content=toc_top.htx
http://luther.chadwyck.com:80/english/frames/werke/toc?action=byid&id=L0000085&CONTROL=ON
http://luther.chadwyck.com:80/deutsch/frames/werke/toc?action=byid&id=L0000085&CONTROL=ON

BOOK, HTML
http://luther.chadwyck.com:80/english/frames/werke/fulltext?ALL=Y&action=byid&warn=Y&size=2877&id=Z000018206&div=0&sequence=0&file=../session/1528322223_25559
http://luther.chadwyck.com:80/deutsch/frames/alle/fulltext?ALL=Y&action=byid&warn=Y&size=2877&id=Z000018206&div=0&sequence=0&file=../session/1528322217_25370
http://luther.chadwyck.com:80/english/frames/werke/fulltext?ALL=Y&action=byid&warn=Y&size=2233&id=Z000022651&div=0&sequence=0&file=../session/1528322223_25559
http://luther.chadwyck.com:80/deutsch/frames/alle/fulltext?ALL=Y&action=byid&warn=Y&size=2238&id=Z000023239&div=0&sequence=0&file=../session/1528322217_25370
