### ISSUE TITLE
Religion and Theology Abstracts 

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#289]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=http://www.rtabstracts.org/

### Priority: 
High

### Subscriber (Library): 
Theology

**Comment by lisahamlett** [comment]
REF, HTML
http://www.rtabstracts.org:80/list-of-abstractors.php
http://www.rtabstracts.org:80/journals-we-abstract.php

SEARCH, HTML
http://www.rtabstracts.org:80/search/results.php

ABSTRACT, HTML
http://www.rtabstracts.org:80/search/singleresult.php?ac=2
http://www.rtabstracts.org:80/search/singleresult.php?ac=3
http://www.rtabstracts.org:80/search/singleresult.php?ac=4
This is what you get when you view multiple abstracts at once:
http://www.rtabstracts.org:80/search/detailedresults.php?s=
