### ISSUE TITLE
ACLS Humanities E-Book

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#29]
### Example:star::star: :

www.humanitiesebook.org

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
http://www.humanitiesebook.org.proxy.library.emory.edu/fulcrum/

"HEB’s publishing partner, Michigan Publishing, is currently working on the Fulcrum platform, a project funded by the Andrew W. Mellon Foundation.  The platform is building on the Hydra/Fedora framework, a popular choice of  many well-established research libraries looking for improved functionalities in their digital repositories and other content management solutions.  HEB joins a prestigious group of publishers partnering with the Fulcrum platform, such as Northwestern University Press, University of Minnesota Press, and Indiana University Press, among others."

**Comment by lisahamlett** [comment]
[ACLS Humanities EBook Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1696963/ACLS.Humanities.EBook.Links.txt)

**Comment by lisahamlett** [comment]
[HumanitiesEBook.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1873336/HumanitiesEBook.txt)
