### ISSUE TITLE
Digital Loeb Classical Library

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#290]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=http://www.loebclassics.com/

### Priority: 
High

### Subscriber (Library): 
Theology

**Comment by lisahamlett** [comment]
TOC, XML
https://www.loebclassics.com:443/view/LCL062/2018/volume.xml
https://www.loebclassics.com:443/view/LCL313/2018/volume.xml
https://www.loebclassics.com:443/view/LCL367/1943/volume.xml

TOC, HTML
https://www.loebclassics.com:443/authors
https://www.loebclassics.com:443/browse?t1=library.greek
https://www.loebclassics.com:443/browse?t1=library.latin
https://www.loebclassics.com:443/volumes

BOOK PART, XML
https://www.loebclassics.com:443/view/seneca_younger-hercules/2018/pb_LCL062.15.xml
https://www.loebclassics.com:443/view/seneca_younger-hercules/2018/pb_LCL062.17.xml
https://www.loebclassics.com:443/view/LCL367/1943/pb_LCL367.441.xml
https://www.loebclassics.com:443/view/livy-history_rome_39/2018/pb_LCL313.209.xml
https://www.loebclassics.com:443/view/lives_homer_10_appendix_romana/2003/pb_LCL496.451.xml?rskey=rhnkPY&result=1&mainRsKey=VGdx8B
https://www.loebclassics.com:443/view/seneca_younger-de_otio/1932/pb_LCL254.201.xml?rskey=AY7I7p&result=1&mainRsKey=ZSWre5
https://www.loebclassics.com:443/view/accius-by_works/1936/pb_LCL314.593.xml?rskey=8n2Vdk&result=3
https://www.loebclassics.com:443/view/aelian-characteristics_animals/1958/pb_LCL446.9.xml?rskey=wQo4Kc&result=2

SEARCH, HTML
https://www.loebclassics.com:443/search?q=homer
https://www.loebclassics.com:443/loeb/search.showresultswithinlink/$002flives_homer_10_appendix_romana$002f2003$002fwork.xml/VGdx8B?q=homer
https://www.loebclassics.com:443/search?q=aristotle
https://www.loebclassics.com:443/search?defaultView=loebSearch&pageSize=10&q=aristotle&sort=relevance&t1=library.latin
https://www.loebclassics.com:443/loeb/search.showresultswithinlink/$002fseneca_younger-de_otio$002f1932$002fwork.xml/ZSWre5?defaultView=loebSearch&pageSize=10&q=aristotle&sort=relevance&t1=library.latin
https://www.loebclassics.com:443/browse?t1=author.aristophanes
