### ISSUE TITLE
Thesaurus Linguae Graecae

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#291]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=http://stephanus.tlg.uci.edu

### Priority: 
High

### Subscriber (Library): 
Theology

**Comment by lisahamlett** [comment]
DICTIONARY ENTRY (I don't know how we class these), HTML
http://stephanus.tlg.uci.edu:80/Iris/lsj/DictData?eid1=1&eid2=2&eid3=3&n_eid=3&with_def=1&with_pages=1&with_rend_head=1&
http://stephanus.tlg.uci.edu:80/Iris/lsj/DictData?eid1=90&eid2=91&eid3=92&n_eid=3&with_def=1&with_pages=1&with_rend_head=1&
http://stephanus.tlg.uci.edu:80/Iris/cunliffe/DictData?eid1=1&eid2=2&eid3=3&n_eid=3&with_def=1&with_pages=1&with_rend_head=1&
http://stephanus.tlg.uci.edu:80/Iris/cunliffe/DictData?eid1=22&eid2=23&eid3=24&n_eid=3&with_def=1&with_pages=1&with_rend_head=1&
http://stephanus.tlg.uci.edu:80/Iris/powell/DictData?eid1=1&eid2=2&eid3=3&n_eid=3&with_def=1&with_pages=1&with_rend_head=1&
http://stephanus.tlg.uci.edu:80/Iris/powell/DictData?eid1=16&eid2=17&eid3=18&n_eid=3&with_def=1&with_pages=1&with_rend_head=1&
http://stephanus.tlg.uci.edu:80/Iris/lbg/DictData?eid1=1&eid2=2&eid3=3&n_eid=3&with_def=1&with_pages=1&with_rend_head=1&
http://stephanus.tlg.uci.edu:80/Iris/lbg/DictData?eid1=13707&eid2=13715&n_eid=2&with_def=1&with_pages=1&with_rend_head=1&

SEARCH, HTML
http://stephanus.tlg.uci.edu:80/Iris/lsj/WordSearch?word=omega
http://stephanus.tlg.uci.edu:80/Iris/lsj/Search?searchterm=medicine&searchtype=meanings&exact=1&nres=500&
http://stephanus.tlg.uci.edu:80/Iris/lsj/Search?searchterm=omega&searchtype=greek&exact=1&nres=500&
http://stephanus.tlg.uci.edu:80/Iris/cunliffe/WordSearch?word=theta
http://stephanus.tlg.uci.edu:80/Iris/cunliffe/Search?searchterm=money&searchtype=meanings&exact=1&nres=500&
http://stephanus.tlg.uci.edu:80/Iris/powell/WordSearch?word=apple
http://stephanus.tlg.uci.edu:80/Iris/powell/Search?searchterm=horse&searchtype=meanings&exact=1&nres=500&
http://stephanus.tlg.uci.edu:80/Iris/powell/Search?searchterm=kappa&searchtype=greek&exact=1&nres=500&
http://stephanus.tlg.uci.edu:80/Iris/lbg/WordSearch?word=water
http://stephanus.tlg.uci.edu:80/Iris/lbg/Search?searchterm=fire&searchtype=meanings&exact=1&nres=500&
http://stephanus.tlg.uci.edu:80/Iris/lbg/Search?searchterm=gamma&searchtype=greek&exact=1&nres=500&

**Comment by AGCooper** [comment]
https://trello.com/c/zrzRohP3/324-thesaurus-linguae-graecae-tlg

http://ang.couperin.org/platforms/56fd3cd815ae306636c96da9
