### ISSUE TITLE
Cambridge Companions Online

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#292]
### Example:star::star: :
https://proxy.library.emory.edu/login?url=http://cco.cambridge.org/uid=2892/private_home

### Priority: 
High

### Subscriber (Library): 
Theology

**Comment by lisahamlett** [comment]
ABSTRACT, HTML
https://www.cambridge.org:443/core/books/cambridge-companion-to-literature-and-science/C5374AB01C8B18E3B0FC30BAADCC47E4
https://www.cambridge.org:443/core/books/cambridge-companion-to-german-idealism/743A8D4031EDCFBE6C9FED9EF5A17909
https://www.cambridge.org:443/core/books/cambridge-companion-to-goethe/faust/3730D293ABE18CCE46A768887F47157A
https://www.cambridge.org:443/core/books/cambridge-companion-to-goethe/goethe-the-dramatist/0A029CA0DA2EE17D061572F537EAD973

BOOK PART, PDF
https://www.cambridge.org:443/core/services/aop-cambridge-core/content/view/EBAE0C3BE30489B1FB3FD9F3C0A6BFF0/9781107079724pre_i-iv.pdf/cambridge_companion_to_literature_and_science.pdf
https://www.cambridge.org:443/core/services/aop-cambridge-core/content/view/629A2EB70FF90FFF31813E6DD803B697/9781107079724ptl1_23-24.pdf/glimpses_of_present_and_future.pdf
https://www.cambridge.org:443/core/services/aop-cambridge-core/content/view/E1BC9229069BDFCABE5759AC93D18958/9781316556511c1_p21-42_CBO.pdf/enlightenment_and_idealism.pdf
https://www.cambridge.org:443/core/services/aop-cambridge-core/content/view/68D9472E9B6B0BF0153CE413FCC381B1/9781316556511c2_p43-64_CBO.pdf/absolute_idealism_and_the_rejection_of_kantian_dualism.pdf
https://www.cambridge.org:443/core/services/aop-cambridge-core/content/view/0A029CA0DA2EE17D061572F537EAD973/9780511999819c04_p66-83_CBO.pdf/goethe_the_dramatist.pdf

BOOK PART, HTML
https://www.cambridge.org:443/core/books/cambridge-companion-to-literature-and-science/snapshots-of-the-past/282F6D92996735EEE8E70BFBED86430B/core-reader
https://www.cambridge.org:443/core/books/cambridge-companion-to-literature-and-science/william-james-henry-james-and-the-impact-of-science/FE703A8B1CF96AA69061BB7611618EC9/core-reader
https://www.cambridge.org:443/core/books/cambridge-companion-to-german-idealism/kants-practical-philosophy/95BDFBA949E229F7158F9B5F1195C1BF/core-reader
https://www.cambridge.org:443/core/books/cambridge-companion-to-german-idealism/aesthetic-reflection-and-human-nature/DF91F1909D20AB9C649B8D497FB21AD7/core-reader
https://www.cambridge.org:443/core/shopping-cart/count?_=1528393086700 HTTP/1.1" 200 476 https://www-cambridge-org.proxy.library.emory.edu/core/books/cambridge-companion-to-modern-arab-culture/food-and-cuisine/705401A7154AD1986994CC49A9396F31/core-reader

SEARCH, HTML
https://www.cambridge.org:443/core/what-we-publish/collections/cambridge-companions/listing?q=faust&_csrf=3HhJxEcN-EMt5CWeaJRlAfXzrE8Za9Pact-c&searchWithinIds=CC5F57B75036F7D224B3BDE3A8A31A7F
https://www.cambridge.org:443/core/what-we-publish/collections/cambridge-companions/listing?q=food&_csrf=VfebVBjj-TqjClYg4BUdjSaINgu6KxKIT_uk&searchWithinIds=CC5F57B75036F7D224B3BDE3A8A31A7F
https://www.cambridge.org:443/core/books/cambridge-companion-to-modern-arab-culture/597D82150476C82529398F46BA2B2C32/listing?q=garlic&_csrf=vNvooS6I-BvgTkBzKkS0YorW0A4VUXGH9hUs&searchWithinIds=597D82150476C82529398F46BA2B2C32&aggs%5BproductTypes%5D%5Bfilters%5D=BOOK_PART
https://www.cambridge.org:443/core/books/cambridge-companion-to-modern-arab-culture/597D82150476C82529398F46BA2B2C32/listing?q=corn&_csrf=vNvooS6I-BvgTkBzKkS0YorW0A4VUXGH9hUs&searchWithinIds=597D82150476C82529398F46BA2B2C32&aggs%5BproductTypes%5D%5Bfilters%5D=BOOK_PART

**Comment by AGCooper** [comment]
This is probably the same as https://trello.com/c/YIH50UlD/50-cambridge-university-press-cup?
