### ISSUE TITLE
Project Muse

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#299]
### Example:star::star: :
http://muse.jhu.edu.proxy.library.emory.edu/browse/series/1180 

### Priority: 
High

### Subscriber (Library): 
Theology

**Comment by lisahamlett** [comment]
SEARCH, HTML
http://muse.jhu.edu:80/search?action=search&limit=subscription:y&limit=series_id:175&min=1&max=10&t=series_facet_select
http://muse.jhu.edu:80/search?action=search&limit=subscription:y&limit=series_id:1091&min=1&max=10&t=series_facet_select
http://muse.jhu.edu:80/search?action=browse&limit=subscription:y&limit=publisher_id:189&min=1&max=10&t=publisher_facet_select
http://muse.jhu.edu:80/search?action=browse
http://muse.jhu.edu:80/search?action=search&query=content:holy%20roman%20empire:and&min=1&max=10&t=header

TOC, HTML
http://muse.jhu.edu:80/book/1540
http://muse.jhu.edu:80/journal/148
http://muse.jhu.edu:80/issue/32071

BOOK PART, PDF
http://muse.jhu.edu:80/chapter/30762/pdf
http://muse.jhu.edu:80/chapter/30770/pdf

ARTICLE, HTML
http://muse.jhu.edu:80/article/583764
http://muse.jhu.edu:80/article/583762

ARTICLE, PDF
http://muse.jhu.edu:80/article/583764/pdf
http://muse.jhu.edu:80/article/583762/pdf
