### ISSUE TITLE
Adam Matthews Digital

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#30]
### Example:star::star: :
www.18thcjournals.amdigital.co.uk
www.africanamericancommunities.amdigital.co.uk
www.americanhistory.amdigital.co.uk
www.amexplorer.amdigital.co.uk
www.china.amdigital.co.uk
www.eastindiacompany.amdigital.co.uk
www.empire.amdigital.co.uk
www.everydaylife.amdigital.co.uk
www.gender.amdigital.co.uk
www.globalcommodities.amdigital.co.uk
www.grandtour.amdigital.co.uk
www.jewishlife.amdigital.co.uk
www.literarymanuscriptsleeds.amdigital.co.uk
www.login.amdigital.co.uk
www.londonlowlife.amdigital.co.uk
www.rockandroll.amdigital.co.uk
www.romanticism.amdigital.co.uk
www.travelwriting.amdigital.co.uk
www.victorianpopularculture.amdigital.co.uk
www.aihc.amdigital.co.uk
www.slavery.amdigital.co.uk
resources.amdigital.co.uk
www.aap.amdigital.co.uk
www.americanwest.amdigital.co.uk
www.chinacultureandsociety.amdigital.co.uk
www.churchmissionarysociety.amdigital.co.uk
www.colonialamerica.amdigital.co.uk
www.firstworldwar.amdigital.co.uk
www.indiaraj.amdigital.co.uk
www.literarymanuscriptsberg.amdigital.co.uk
www.massobservation.amdigital.co.uk
www.medievalfamilylife.amdigital.co.uk
www.medievaltravel.amdigital.co.uk
www.perditamanuscripts.amdigital.co.uk
www.racerelations.amdigital.co.uk
www.shakespeareinperformance.amdigital.co.uk
www.virginiacompanyarchives.amdigital.co.uk
### Priority: 
Medium

### Subscriber (Library): 
Woodruff

**Comment by eipeele** [comment]
Platform started by ezpaarse community, but only has one domain:  https://github.com/ezpaarse-project/ezpaarse-platforms/tree/master/amdigital

**Comment by AGCooper** [comment]
From AnalogIST: http://ang.couperin.org/platforms/58f75fe5f44d7f7aa7b4135d
