### ISSUE TITLE
New titles for Nature-Palgrave

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#306]
For Springer-Nature-Palgrave the additional titles are here:

  *   Springer: Sports Medicine and Academic Psychiatry
  *   Palgrave: Latino Studies, Comparative European Politics, Eastern Economic Journal, IMF Economic Review, Social Theory and Health, Security Journal, and Psychoanalysis, Culture and Society
  *   ~~Nature Astronomy~~
  *   ~~Nature Biomedical Engineering~~
  *   ~~Nature Catalysis~~
  *   ~~Nature Electronics~~
  *   ~~Nature Energy~~
  *   ~~Nature Human Behaviour~~
  *   ~~Nature Microbiology~~
  *   ~~Nature Reviews Materials~~
  *   ~~Nature Sustainability~~

**Comment by lisahamlett** [comment]
Nature Astronomy, Nature Biomedical Engineering, Nature Catalysis, Nature Electronics, Nature Energy, Nature Human Behaviour, Nature Microbiology, Nature Reviews Materials, and Nature Sustainability are grouped under Nature because of how their new site creates links.

**Comment by lisahamlett** [comment]
This is already being done.
