### ISSUE TITLE
allAfrica

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#31]
### Example:star::star: :

allAfrica

### Priority: 
Low

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Nothing on Trello or Couperin

**Comment by lisahamlett** [comment]
ARTICLE, PDF
http://allafrica.com:80/download/resource/main/main/idatcs/00111751:f3daf74e033943cd85650d285f28bed0.pdf
http://allafrica.com:80/download/resource/main/main/idatcs/00111945:41291ee17637670b93f8e032cd0519b7.pdf
 
AUDIO, MP3
http://allafrica.com:80/download/resource/main/main/idatcs/00111925:d103fdb9f1dd661fa49b661274d15b12.mp3
http://allafrica.com:80/download/resource/main/main/idatcs/00111941:36f8a8185205a761b939481d42644d59.mp3
http://allafrica.com:80/download/resource/main/main/idatcs/00120001:23f196b4f0f889df837141e4a6af1f12.mp3
 
TOC, HTML
http://allafrica.com:80/list/group/main/main/h-resource/bt.html
http://allafrica.com:80/list/photoessay/post/post/doc/all.html
http://allafrica.com:80/list/resource/main/main/cat/southafrica.html
http://allafrica.com:80/list/resource/main/main/doc/all.html
http://allafrica.com:80/list/resource/main/main/type/doc.html
http://allafrica.com:80/list/resource/main/main/type/web.html
http://allafrica.com:80/view/group/main/main/id/00059768.html
http://allafrica.com:80/view/group/main/main/id/00059994.html
 
SEARCH, HTML
http://allafrica.com:80/search/?search_string=england
 
ARTICLE, HTML
http://allafrica.com:80/stories/201803230621.html
http://allafrica.com:80/stories/201804020301.html
 
REF, HTML
http://allafrica.com:80/view/resource/main/main/id/00111751.html
http://allafrica.com:80/view/resource/main/main/id/00111941.html
http://allafrica.com:80/view/resource/main/main/id/00111945.html
http://allafrica.com:80/view/resource/main/main/id/00120001.html
http://allafrica.com:80/view/resource/main/main/id/00120003.html
http://allafrica.com:80/view/resource/main/main/id/00120006.html
http://allafrica.com:80/view/resource/main/main/id/00120010.html
 
PHOTOESSAY - ARTICLE?, HTML
http://allafrica.com:80/view/photoessay/post/post/id/201803260001.html
http://allafrica.com:80/view/photoessay/post/post/id/201804030001.html
