### ISSUE TITLE
Ambrose Digital Video

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#32]
### Example:star::star: :

www.ambrosevideo.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Nothing on Trello or Couperin

**Comment by lisahamlett** [comment]
VIDEO, MP4
http://cfph.ambrosevideo.com:80/FGX/FGX.mp4
http://cfph.ambrosevideo.com:80/FNX/FNX.mp4
http://cfph.ambrosevideo.com:80/NRS/NRS.mp4
http://cfph.ambrosevideo.com:80/SH/SH.mp4
 
REF?, HTML
http://www.ambrosevideo.com:80/ambrose-news/136-library-discovery-services
http://www.ambrosevideo.com:80/ambrose-news/148-go-in-depth-the-neuroscience-of-addiction
 
TOC, HTML
http://www.ambrosevideo.com:80/screening-room/133-nrs
http://www.ambrosevideo.com:80/screening-room/151-fgx
http://www.ambrosevideo.com:80/screening-room/153-fnx
http://www.ambrosevideo.com:80/screening-room/24-SH
http://www.ambrosevideo.com:80/screening-room/list-titles
