### ISSUE TITLE
Dynamed (WHSCL 6)

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/ezpaarse-platforms#324]
### Example:star::star: :
https://login.proxy.library.emory.edu/login?url=https://www.dynamed.com/

### Priority: 
High

### Subscriber (Library): 
Health

This is an EBSCO database but I don’t see it on the EBSCO list in LibStats. I realize that we can only get top level numbers for  EBSCO  databases, but if those totals can be parsed by person, division, etc., it would be very helpful.

**Comment by lisahamlett** [comment]
Dynamed has its own domain (not EBSCO), so it should be fine.
There's nothing on AnalogIST or Trello and it wasn't proxying.

EBSCO posted a stanza on their website as of 8/2/18 and it seems to work:
TITLE DynaMed Plus
URL http://www.dynamed.com/
DJ dynamed.com
DJ ebsco-content.com
HJ ac.ebsco-content.com
HJ auth.dynamed.com
HJ calc.dynamed.com
HJ global.ac.ebsco-content.com
HJ largecontent.ebsco-content.com
HJ pws.ebsco-content.com
HJ smallcontent.ebsco-content.com
HJ store.dynamed.com
HJ www.dynamed.com

**Comment by lisahamlett** [comment]
Original issue: https://github.com/emory-libraries/ezpaarse-platforms/issues/174

When this issue was mentioned before, DynaMed did not have its own domain.  It was still under the EBSCO domain, so the parser was merged into EBSCO.

**Comment by lisahamlett** [comment]
Not much is stored for Dynamed:

INITIAL ACCESS
http://www.dynamed.com:80/api/bootprofile

MOST ACTIONS WITHIN DOMAIN
http://www.dynamed.com:80/api/TopicDetail
https://calc.dynamed.com:443/calculators/index.asp

SEARCH, HTML
http://www.dynamed.com:80/api/BuzzDmpSearch

ARTICLE, HTML (only shows up on the first click.  No subsequent articles show)
http://www.dynamed.com:80/topics/dmp~AN~T116756/Superficial-vein-thrombosis-SVT

[DynaMed Log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2578582/DynaMed.Log.txt)
