### ISSUE TITLE
AACR - American Association of Cancer Research (WHSCL 2)

### ISSUE THREAD

**Issue by lisahamlett** [emory-libraries/ezpaarse-platforms#327]
### Example:star::star: :
https://login.proxy.library.emory.edu/login?url=http://www.aacr.org/
https://login.proxy.library.emory.edu/login?url=http://aacrjournals.org/

### Priority: 
High

### Subscriber (Library): 
Health

### Domains:
~aacr.org~
~aacrjournals.org~
~cancerdiscovery.aacrjournals.org~
~cancerimmunolres.aacrjournals.org~
~cancerpreventionresearch.aacrjournals.org~
~cancerres.aacrjournals.org~
~canimmessentials.aacrjournals.org~
~canreviews.aacrjournals.org~
~cdnews.aacrjournals.org~
~cebp.aacrjournals.org~
~cgd.aacrjournals.org~
~clincancerres.aacrjournals.org~
cme.aacrjournals.org
~educationbook.aacrjournals.org~
intl-preventionportal.aacrjournals.org
~mcr.aacrjournals.org~
~mct.aacrjournals.org~
~preventionportal.aacrjournals.org~

### Database Stanza:
https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/aacrjournals

**Comment by lisahamlett** [comment]
This was not set to proxy at all and the OCLC stanza online is out of date.  I added it anyway because the old website links refer to the new and I created a new stanza to proxy the new website.

I can do searches on the AACR site:
SEARCH, HTML
https://www.aacr.org:443/pages/searchresults.aspx?k=potato
https://www.aacr.org:443/pages/searchresults.aspx?k=chemotherapy
However, when I click on any articles, presentations, etc., it drops proxy.

Here are the types from the journal site:
SEARCH, HTML
http://aacrjournals.org:80/search/tomatoes%20exclude_meeting_abstracts%3A1
http://aacrjournals.org:80/search/cows%20exclude_meeting_abstracts%3A1

TOC, HTML
http://cancerres.aacrjournals.org:80/content/78/20?utm_source=current&utm_medium=dropdown&utm_campaign=menu&current-issue=y
http://cancerres.aacrjournals.org:80/content/by/volume
http://cancerres.aacrjournals.org:80/content/78/12

ABSTRACT, HTML
http://cancerres.aacrjournals.org:80/content/38/6/1556
http://cebp.aacrjournals.org:80/content/early/2018/10/06/1055-9965.EPI-18-0286
http://cancerres.aacrjournals.org:80/content/78/12/3147

SUPPLEMENT, DOCX
http://cebp.aacrjournals.org:80/content/cebp/suppl/2018/10/06/1055-9965.EPI-18-0286.DC1/198621_2_supp_4983966_pdx05f.docx
http://cebp.aacrjournals.org:80/content/cebp/suppl/2018/10/06/1055-9965.EPI-18-0286.DC1/198621_2_supp_4983968_pdx051.docx

ARTICLE, PDF
http://cebp.aacrjournals.org:80/content/cebp/early/2018/10/06/1055-9965.EPI-18-0286.full.pdf
http://cebp.aacrjournals.org:80/content/cebp/early/2018/10/06/1055-9965.EPI-18-0286.full.pdf

SUPPLEMENT, PDF
http://cancerres.aacrjournals.org:80/content/canres/38/6/local/back-matter.pdf

TOC, PDF
http://cancerres.aacrjournals.org:80/content/canres/38/6.toc.pdf

LOG:
[AACR_Log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2484738/AACR_Log.txt)

**Comment by AGCooper** [comment]
https://trello.com/c/mXyXBQy4/40-american-association-for-cancer-research-hw

http://ang.couperin.org/platforms/54082f7e3cf20ffee9eea43d
