### ISSUE TITLE
American National Biography

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#33]
#### Example:star::star: :
https://www-anb-org.proxy.library.emory.edu/

anb.org
www.anb.org

#### Priority: 
Low

#### Subscriber (Library): 
Woodruff

#### ezPAARSE
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://www.anb.org:443/search?q=mark+twain&searchBtn=Search&isQuickSearch=true
https://www.anb.org:443/search?submittedFilterId=by-format&q=mark+twain&isQuickSearch=true&btog=chap&pageSize=20&sort=titlesort&type_5=subjectreference

TOC;HTML
https://www.anb.org:443/page/news
https://www.anb.org:443/page/tools-and-resources

**DOI = https://doi.org/10.1093/anb/9780198606697.article.1600745**

ARTICLE;HTML
https://www.anb.org:443/view/10.1093/anb/9780198606697.001.0001/anb-9780198606697-e-1600745

ARTICLE;PDF
https://www.anb.org:443/view/10.1093/anb/9780198606697.001.0001/anb-9780198606697-e-1600745?print=pdf

IMAGE;MISC
https://www.anb.org:443/view/10.1093/anb/9780198606697.001.0001/anb-9780198606697-e-1600745?mediaType=Image

ARTICLE;HTML
https://www.anb.org:443/newsitem/337/whats-new-january-2020

[anb.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4252235/anb.txt)
