### ISSUE TITLE
APA Style CENTRAL

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#34]
### Example:star::star: :

apastylecentral.apa.org

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
APA in "freezer"
https://trello.com/c/d66jMESY/80-american-psychiatric-association-apa

http://ang.couperin.org/platforms/54350cf85189fdbe16d53b74

**Comment by lisahamlett** [comment]
Nothing for American Psychological Association (APA) on Trello or http://ang.couperin.org/

**Comment by eipeele** [comment]
According to Jessie Copeland, we do not subscribe to this resource anymore.  Closing this issue.
