### ISSUE TITLE
Factiva (factiva)

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/ezpaarse-platforms#343]
### Example:star::star: :
https://trello.com/c/xbAbAtCl/184-factiva

It seems like that consultations or searches are counted twice : for one connection and two searches done, two connections and three searches are recognized.

I checked and I think I see what is happening. I log in and do 1 search and get the attached parsed output. 1 login (I believe the parsers ignore POSTs and only count GETs) 2 searches (because every time you open or use the search tab it gets registered). I'm trying to think of what to do.

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
This is what you get when you type into the search box and press enter: 
[Search.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3010665/Search.txt)

This is the only thing that isn't a part of a script and it only appears once:
GET https://global.factiva.com:443/WebResource.axd?d=lM1UArKg03omlzYrizKIMjSPZWShDqaVD01uS8U6thnUgAuS1w0jS-m4HlHV3flM-b6pN1s5QGpsUHaDTtWhL4PbLo29JUld6MYWO7zHQLzeUvTLMODujqL9V1n9xGtmDa4ccx4pGOuT57357Ji2PRer_V41&t=635742183660000000

**Comment by lisahamlett** [comment]
- When you log in, there's on GET for https://global.factiva.com:443/en/sess/login.asp which can be used as a connection.
- Searches get multiples for https://global.factiva.com:443/controls/search/SearchBuilder
- MP3s get single results
- Nothing else is parsing
