### ISSUE TITLE
Artnet

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#35]
#### Example:star::star: :
http://www.artnet.com.proxy.library.emory.edu/

#### Priority: 
Medium

#### Subscriber (Library): 
Woodruff

#### ezPAARSE
Analysis: None
Trello: None

**Comment by CB987** [comment]
SEARCH;HTML;
http://www.artnet.com:80/search/artists/?q=barton
http://www.artnet.com:80/search/?q=rainbow
http://www.artnet.com:80/search/articles/?q=luis-de-jesus
http://www.artnet.com:80/artists/artists-starting-with-b
http://www.artnet.com:80/artists/artists-starting-with-b%c3%adr%e2%80%93bis
http://www.artnet.com:80/api/search/rainbow/artworks
http://www.artnet.com:80/api/galleries/rainbow/1/0
http://www.artnet.com:80/pdb/faadsearch/FAADResults3.aspx?Page=1&ArtType=FineArt
http://www.artnet.com:80/PDB/FAADSearch/FAADResults3.aspx?Page=1&ArtType=DecArt

ABS;HTML;
http://www.artnet.com:80/galleries/luis-de-jesus
http://www.artnet.com:80/galleries/avant-gallery/

TOC;HTML;
http://www.artnet.com:80/artists/alexander-barton/
http://www.artnet.com:80/artists/perrine-lievens/
http://www.artnet.com:80/galleries/aca-galleries/the-end-of-western-art
ttp://www.artnet.com:80/galleries/avant-gallery/there-goes-the-neighborhood-new-art-for-the-new-new-york
http://www.artnet.com:80/galleries/roberts-projects/control/
http://www.artnet.com:80/galleries/galerie-von-bartha/artists/
http://www.artnet.com:80/galleries/avant-gallery/artworks/
https://www.artnet.com:443/auctions/photographs-0719
https://www.artnet.com:443/auctions/post-war-and-contemporary-art

REF;HTML;
http://www.artnet.com:80/PDB/FAADSearch/LotDetailView.aspx?Page=1&artType=FineArt&subTypeId=11
http://www.artnet.com:80/PDB/FAADSearch/LotDetailView.aspx?Page=1&artType=DecArt&subTypeId=159
https://www.artnet.com:443/auctions/artists/richard-hambleton/untitled-jumping-cat-4
https://www.artnet.com:443/auctions/artists/anish-kapoor/untitled-8
http://www.artnet.com:80/auction-houses/ewbanks/artist-banksy/

REF;PDF;
http://www.artnet.com:80/pdb/faadsearch/lotpdfviewer.ashx?Page=1&artType=FineArt&subTypeId=11
http://www.artnet.com:80/pdb/faadsearch/lotpdfviewer.ashx?Page=1&artType=DecArt&subTypeId=159

ARTICLE;HTML;
https://news.artnet.com:443/partner-content/booths-armory-show-2019
https://news.artnet.com:443/partner-content/art-guide-kent-connecticut
https://news.artnet.com:443/art-world/lisa-spellman-1604485
https://news.artnet.com:443/opinion/mural-controversy-devon-cook-mark-sanchez-reply-1599019
https://news.artnet.com:443/art-world/san-francisco-mural-victor-arnautoff-dewey-crumpler-1596409
https://news.artnet.com:443/market/christies-space-sale-flops-1604191
https://news.artnet.com:443/art-world/brancusi-lawsuit-1604065

IMAGE;HTML;
http://www.artnet.com:80/artists/landon-metz/untitled-a-F-4-l8cx00TtsWGlxClVWg2
http://www.artnet.com:80/artists/guy-le-baube/wool-a-1GdD4YzM8KIbY5srOuiETA2
http://www.artnet.com:80/artists/billy-apple/four-blue-knots-for-r-d-laing-a-rq3XAg8ygsCFqp9r2j9kZA2

[artnet_logs.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3422410/artnet_logs.txt)
