### ISSUE TITLE
Artstor (LCS)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#36]
### Example:star::star: :

Artstor

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/548973b384f7d88bcf5e3145
https://trello.com/c/8wdYB2eN/172-artstor-digital-library-artstor

**Comment by lisahamlett** [comment]
TOC, HTML
http://library.artstor.org:80/api/collections/103/categorynames
http://library.artstor.org:80/api/collections/35543
http://library.artstor.org:80/api/categories/1035284832
http://library.artstor.org:80/api/categories/10374058875

SEARCH, HTML
http://library.artstor.org:80/api/search/v1.0/search

ARTICLE, HTML
http://library.artstor.org:80/api/v1/metadata?object_ids=ARCHIVISION_111011290713
http://library.artstor.org:80/api/v1/metadata?object_ids=ARCHIVISION_111011290128
https://library.artstor.org:443/api/v1/metadata?object_ids=AMICO_MINIAPOLIS_103823768&legacy=false

LOG:
[ARTstor Log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2250895/ARTstor.Log.txt)

**Comment by lisahamlett** [comment]
Artstor was dropping into TABLEAU_INPUT until 7/11/17.  It had one occurrence to 4/23/18 and one in 10/23/17 but nothing otherwise. It had a lot of usage before that though.

**Comment by lisahamlett** [comment]
I double checked the links and, if we add the ones above, this should resolve the parser issue.

**Comment by lisahamlett** [comment]
Needs to be added to the server
