### ISSUE TITLE
GuideStar (Highest)

### ISSUE THREAD

**Issue by lisahamlett** [emory-libraries/ezpaarse-platforms#369]
### Example:star::star: :
https://www-guidestar-org.proxy.library.emory.edu/search

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello

**Comment by CB987** [comment]
This is where the databases @ emory link takes you, but it's not the front page
https://www-guidestar-org:443/search
it also gives an error message on load, maybe bc nothing is in the search field?
The front page is https://www.guidestar.org:443/

for everything that has **-******* it's their ein (tax number), which should be unique

SEARCH, HTML
GET https://www.guidestar.org:443/search
POST https://www.guidestar.org:443/search/SubmitSearch 

REF, HTML
https://www.guidestar.org:443/profile/13-1915124
https://www.guidestar.org:443/profile/23-2451475

REPORT, PDF
https://www.guidestar.org:443/Profile/ViewCCPdf?ein=23-2451475
https://www.guidestar.org:443/Profile/ViewCCPdf?ein=22-3936753

also a REPORT, PDF (pdf of tax form)
https://pdf.guidestar.org:443/PDF_Images/2017/942/705/2017-942705685-0feab72f-9.pdf
https://pdf.guidestar.org:443/PDF_Images/2003/481/102/2003-481102881-1-9.pdf

REPORT? or DATA?, PDF (a Comprehensive Financial Trends Analysis multi-page pdf)
https://www.guidestar.org:443/profile/CompFtaPdfLocal/94-2705685
https://www.guidestar.org:443/profile/CompFtaPdfLocal/48-1102881
