### ISSUE TITLE
Brepols Online

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#37]
### Example:star::star: :

www.brepolsonline.net

### Priority: 
Medium

### Subscriber (Library): 

Woodruff

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/5571a5583d42b4db783dc4a0
https://trello.com/c/D3TXMdui/258-brepols-online

**Comment by lisahamlett** [comment]
[Brepols Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1657812/Brepols.Links.txt)

**Comment by AGCooper** [comment]
Looks like they also authenticate by IP not necessarily proxy.

**Comment by AGCooper** [comment]
@lisahamlett would you complete the publication_title if loop? The branch is brep

**Comment by AGCooper** [comment]
@AGCooper When testing with the web portal see if the metadata api adds rtype.

**Comment by AGCooper** [comment]
[Brepols Log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1704991/Brepols.Log.txt)
