### ISSUE TITLE
Palgrave-macmillan parser lacks article parsing

### ISSUE THREAD

**Issue by CB987** [emory-libraries/ezpaarse-platforms#372]
### Example:star::star: :
www.palgrave.com:443/us/book/9783319905808
this goes to the TOC instead of ARTICLE... fixed this one but look for article or book resources to add to parser

### Priority: 
Low

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
https://github.com/emory-libraries/ezpaarse-platforms/pull/371
