### ISSUE TITLE
BrowZine by Third Iron

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#38]
### Example:star::star: :

browzine.com
api.thirdiron.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Nothing about BrowZine on ezPAARSE Trello or ang.couperin.org

**Comment by AGCooper** [comment]
@epeele this seems like it's more than a platform. It is really an access provider for platforms and their content.

**Comment by AGCooper** [comment]
Smaple URLs:

- https://browzine.com:443/libraries
- http://api.thirdiron.com:80/v2/token-form?success=/libraries/481/accept-token&failure=/token-failure/481&libraryId=481&forceAuth=true
- http://api.thirdiron.com:80/v2/api-tokens
- https://browzine.com:443/libraries/481/accept-token?token=e9c58f49-ee08-4822-9f47-fc52b89c4c51

After search:
> https://proxy.library.emory.edu:443/login?auth=shibboleth&url=http://ovidsp.ovid.com/ovidweb.cgi?T=JS&PAGE=fulltext&D=ovft&MODE=ovid&NEWS=N&SEARCH=%220304-3959%22.is%20and%20%22158%22.vo%20and%20%22%22.ip%20and%20%22S1%22.pg%20or%20%2210.1097/j.pain.0000000000000877%22.di&CSC=Y&FT_format=PDF

**Comment by eipeele** [comment]
Have parser parse https://browzine.com:443/libraries/481/accept-token?token=d1b77709-4fe6-4358-a02a-de70982c842d so that it recognizes /libraries.  After authentication it drops proxy anyway so we can't get that info.

I know it's not one of the current supported rtypes, but could we just make it say ACCESS or AUTH since that's what this is doing?  Thoughts?

This will at least measure if people are using it, which I think is what they want out of it since Woodruff and health are both pushing people towards it.

**Comment by AGCooper** [comment]
@eipeele What about SEARCH for rtype?
