### ISSUE TITLE
Cab Direct

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#39]
### Example:star::star: :
https://login.proxy.library.emory.edu/login?url=http://www.cabdirect.org/
http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA51297034950002486

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/58ef38a8bcf94cd98e0496e0
https://trello.com/c/TDYoedBb/402-cab-ebooks-cabi

https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/CABI_Resources

**Comment by CB987** [comment]
- update manifest:
www.cabdirect.org
cabdirect.org
Manifest from ez-paarse already includes cabi.org. cabdirect also includes links to plantwise.org and invasive-species.org, but these links drop proxy.

SEARCH, HTML
https://www.cabdirect.org:443/cabdirect/search/?q=rainbow&facet1f=Your%20Products&facet1o=OR&facet1v=FT&facets=1
https://www.cabdirect.org:443/cabdirect/search/?q=au%3a%22Babaheydari%2c+S.+B.%22
https://www.cabi.org:443/cabthesaurus/mtwdk.exe?searchstring=&k=default&w=rainbow&l=60&s=1&t=1&n=15&x=0&tt=0
https://www.cabdirect.org:443/cabdirect/search/?q=cc%3aAA500

ABSTRACT, HTML
https://www.cabdirect.org:443/cabdirect/abstract/20183359796?q=(rainbow)+AND+(+((sc%3a((+%22FT%22+)+))+))
https://www.cabdirect.org:443/cabdirect/abstract/20143226753?q=(hobbit)+AND+(+((sc%3a((+%22CA%22+)+))+))

The resources below are different but do not seem to be distinguishable by PDF so... not really sure what the rtype should be?
ARTICLE, PDF
https://www.cabdirect.org:443/cabdirect/FullTextPDF/2018/20183359796.pdf
https://www.cabdirect.org:443/cabdirect/FullTextPDF/2014/20143226753.pdf

BOOK, PDF
https://www.cabdirect.org:443/cabdirect/FullTextPDF/2017/20173071957.pdf

BOOK _SECTION, PDF
https://www.cabdirect.org:443/cabdirect/FullTextPDF/2019/20193035305.pdf


[CABdirect_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3095553/CABdirect_log.txt)
