### ISSUE TITLE
Cairn

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#40]
### Example:star::star: :

www.cairn-int.info

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/53f4a1212426ac515b9e266c
https://trello.com/c/rKJTqlf0/29-cairn-cairn

**Comment by lisahamlett** [comment]
[Cairn Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1657875/Cairn.Links.txt)
