### ISSUE TITLE
Worldbank Add Print Identifiers

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/ezpaarse-platforms#409]
### Example:star::star: :
https://elibrary.worldbank.org:443/doi/full/10.1596/978-1-4648-1002-2_Module2

print_identifier = 978-1-4648-1002-2

### ezPAARSE
Analysis:

Trello:

**Comment by AGCooper** [comment]
Also rtype = DATA should be DATA_SET

**Comment by lisahamlett** [comment]
Aye, aye, Cap'n!
