### ISSUE TITLE
Grand Secretariat

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#41]
### Example:star::star: :
http://www3.stat.sinica.edu.tw.proxy.library.emory.edu/

archive.ihp.sinica.edu.tw
hanchi.ihp.sinica.edu.tw
www.ihp.sinica.edu.tw
ihp.sinica.edu.tw
sinica.edu.tw

#### Priority: 
Low

#### Subscriber (Library): 
Woodruff

#### ezPAARSE
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
Website is dead.  Links in DiscoverE go to EBSCO.
