### ISSUE TITLE
Update Adam Matthew Digital [amdigital]

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/ezpaarse-platforms#422]
### Example:star::star: :
http://www.empire.amdigital.co.uk.proxy.library.emory.edu/ (Empire Online—AM Digital)

http://www.churchmissionarysociety.amdigital.co.uk.proxy.library.emory.edu/ (Church Missionary Society Periodicals—AM Digital)

http://www.eastindiacompany.amdigital.co.uk.proxy.library.emory.edu/ (East India Company Archives—AM Digital)

http://www.colonialamerica.amdigital.co.uk.proxy.library.emory.edu/ (Colonial America—AM Digital)

http://www.amexplorer.amdigital.co.uk.proxy.library.emory.edu/ (Archives Explorer—AM Digital)]

### Priority: 
High

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/58f75fe5f44d7f7aa7b4135d

Trello: https://trello.com/c/Z90wvFuK/405-archives-direct-adam-matthew-digital-amdigital

**Comment by lisahamlett** [comment]
Full domain list:
amdigital.co.uk
www.18thcjournals.amdigital.co.uk
www.aap.amdigital.co.uk
www.africanamericancommunities.amdigital.co.uk
www.aihc.amdigital.co.uk
www.amdigital.co.uk
www.americanhistory.amdigital.co.uk
www.americanindiannewspapers.amdigital.co.uk
www.americanwest.amdigital.co.uk
www.amexplorer.amdigital.co.uk
www.archiveexplorer.amdigital.co.uk
www.archivesdirect.amdigital.co.uk
www.china.amdigital.co.uk
www.chinacultureandsociety.amdigital.co.uk
www.churchmissionarysociety.amdigital.co.uk
www.colonialamerica.amdigital.co.uk
www.consumerculture.amdigital.co.uk
www.eastindiacompany.amdigital.co.uk
www.eighteenthcenturydrama.amdigital.co.uk
www.empire.amdigital.co.uk
www.everydaylife.amdigital.co.uk
www.exploration.amdigital.co.uk
www.firstworldwar.amdigital.co.uk
www.frontierlife.amdigital.co.uk
www.gender.amdigital.co.uk
www.genderidentityandsocialchange.amdigital.co.uk
www.globalcommodities.amdigital.co.uk
www.grandtour.amdigital.co.uk
www.indiaraj.amdigital.co.uk
www.jewishlife.amdigital.co.uk
www.jwtadvertisingamerica.amdigital.co.uk
www.literarymanuscriptsberg.amdigital.co.uk
www.literarymanuscriptsleeds.amdigital.co.uk
www.literaryprintculture.amdigital.co.uk
www.login.amdigital.co.uk
www.londonlowlife.amdigital.co.uk
www.marketresearch.amdigital.co.uk
www.massobservation.amdigital.co.uk
www.masstourism.amdigital.co.uk
www.medicalservicesandwarfare.amdigital.co.uk
www.medievalfamilylife.amdigital.co.uk
www.medievaltravel.amdigital.co.uk
www.migration.amdigital.co.uk
www.perditamanuscripts.amdigital.co.uk
www.popularmedicine.amdigital.co.uk
www.racerelations.amdigital.co.uk
www.researchsource.amdigital.co.uk
resources.amdigital.co.uk
www.rockandroll.amdigital.co.uk
www.romanticism.amdigital.co.uk
www.servicenewspapers.amdigital.co.uk
www.shakespeareinperformance.amdigital.co.uk
www.shakespearesglobearchive.amdigital.co.uk
www.slavery.amdigital.co.uk
www.socialismonfilm.amdigital.co.uk
www.travelwriting.amdigital.co.uk
www.victorianpopularculture.amdigital.co.uk
www.virginiacompanyarchives.amdigital.co.uk
www.worldsfairs.amdigital.co.uk
