### ISSUE TITLE
Add KISS [kiss]

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/ezpaarse-platforms#423]
### Example:star::star: :
http://kiss.kstudy.com.proxy.library.emory.edu/ (KISS)

### Priority: 
High

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis:

Trello:

**Comment by CB987** [comment]
SEARCH, HTML
http://kiss.kstudy.com:80/subject/subject1.asp?datas=06,31,kiss
http://kiss.kstudy.com:80/subject/subject2.asp
http://kiss.kstudy.com:80/subject/subj-thesis-view.asp?key=8
http://kiss.kstudy.com:80/dataReport/data2.asp?key=204
http://kiss.kstudy.com:80/inc/aside_view_thesis.asp?key=3660962,3217329,3656253
http://kiss.kstudy.com:80/inc/aside_view_thesis.asp?key=3660962,3217329,3656253,2851753,404440,404449,3664469,1637421,3581678,3186305,3666921,3547940,3667618,3587276

REF, HTML
http://kiss.kstudy.com:80/publish/pub-office.asp?queryIn=7113
http://kiss.kstudy.com:80/publish/pub-office.asp?queryIn=7120

TOC, HTML
http://kiss.kstudy.com:80/journal/journal-view.asp?key1=30199&key2=7136
http://kiss.kstudy.com:80/journal/journal-view.asp?key1=30127&key2=7129
 
ABSTRACT, HTML
http://kiss.kstudy.com:80/thesis/thesis-view.asp?key=3660962
http://kiss.kstudy.com:80/thesis/thesis-view.asp?key=3217329
http://kiss.kstudy.com:80/thesis/thesis-view.asp?key=3656253

ARTICLE, PDF
http://kiss.kstudy.com:80/search/download.asp?ftproot=http://210.101.116.15/kiss5/download_journal.asp&inst_key=7129&a_imag=2c800098.pdf&isDownLoad=0&publ_key=30127
http://kiss.kstudy.com:80/search/download.asp?ftproot=http://210.101.116.15/kiss5/download_journal.asp&inst_key=7129&a_imag=2c800099.pdf&isDownLoad=0&publ_key=30127
http://kiss.kstudy.com:80/search/download.asp?ftproot=http://210.101.116.15/kiss5/download_journal.asp&inst_key=2321&a_imag=2u301418.pdf&isDownLoad=1&publ_key=30772&down_name=%E2%80%98%EC%8B%A0%EC%8B%9C%EB%8C%80%E2%80%99%EC%99%80%20%EC%A4%91%EA%B5%AD%EC%9D%98%20%EC%97%AD%EC%82%AC%20%EB%8B%A4%EC%8B%9C%20%EC%93%B0%EA%B8%B0%20%EC%9D%BC%EA%B5%AD%EC%82%AC%EC%99%80%20%EC%A7%80%EC%97%AD%EC%82%AC%EC%9D%98%20%EA%B2%BD%EA%B3%84%EC%97%90%EC%84%9C
http://kiss.kstudy.com:80/search/open_viewer.asp?ftproot=http://210.101.116.61/74000018/index.asp&inst_key=5050&a_imag=74000018.pdf&isDownLoad=0&publ_key=25492
http://kiss.kstudy.com:80/search/open_viewer.asp?ftproot=http://210.101.116.61/06006260/index.asp&inst_key=8010&a_imag=06006260.pdf&isDownLoad=0&publ_key=25450

[kiss_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3316388/kiss_log.txt)
