### ISSUE TITLE
DUXIU (Highest)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#43]
### Example:star::star: :
http://www.duxiu.com.proxy.library.emory.edu/ 

### Domains: 
book.duxiu.com
count.duxiu.com
frelt.duxiu.com
img.duxiu.com
jour.duxiu.com
newspaper.duxiu.com
qk.duxiu.com
qw.duxiu.com
relt.duxiu.com
relt1.duxiu.com
relt2.duxiu.com
simg.duxiu.com
unicover.duxiu.com
vrefer.duxiu.com
www.duxiu.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello

**Comment by lisahamlett** [comment]
SEARCH, HTML
http://qw.duxiu.com:80/getPage?sw=potato&ecode=utf-8
http://qw.duxiu.com:80/getPage?sw=brain&ecode=utf-8
http://qw.duxiu.com:80/gosearch.jsp?sw=brain&allsw=%23%2Callbrain&searchtype=&channel=searchThesis&bCon=&ecode=utf-8
http://jour.duxiu.com:80/gosearch.jsp?sw=brain&allsw=%23%2Callbrain&channel=searchCP&bCon=&ecode=utf-8&searchtype=&Field=all
http://jour.duxiu.com:80/gosearch.jsp?sw=brain&allsw=%23%2Callbrain&channel=searchVideo&bCon=&ecode=utf-8&searchtype=&Field=all
http://book.duxiu.com:80/gosearch.jsp?sw=brain&allsw=%23%2Callbrain&searchtype=&channel=searchDoc&bCon=&ecode=utf-8&Field=all
http://www.duxiu.com:80/gosearch.jsp?channel=searchCourse&ecode=utf-8&sw=mind&Field=all
http://www.duxiu.com:80/gosearch.jsp?channel=searchFirstDrs.jhtml&ecode=utf-8&sw=blue&Field=all
http://book.duxiu.com:80/searchEncy?Field=all&channel=searchEncy&sw=carrot&ecode=utf-8&edtype=&searchtype=&view=0
http://book.duxiu.com:80/searchInfo?Field=all&channel=searchInfo&sw=blacksmith&ecode=utf-8&edtype=&searchtype=&view=0
http://vrefer.duxiu.com:80/searchGovernment?Field=all&channel=searchGovernment&sw=bridge&ecode=utf-8&edtype=&searchtype=&view=0

REF, HTML
http://book.duxiu.com:80/bookDetail.jsp?dxNumber=000016213781&d=BF1D22D4A90B8ADF9CF61B0CCCB1676C
http://book.duxiu.com:80/bookDetail.jsp?dxNumber=000005229290&d=D2D23AD5C1D5E69A0680AEC4A4E9AA2E
http://jour.duxiu.com:80/JourDetail.jsp?dxNumber=100258237321&d=B46BAE24AC2B4A43E08D625E2B268E35
http://newspaper.duxiu.com:80/NPDetail.jsp?dxNumber=300325262136&d=6EEB65558274CC8C3C28B6452C9FE086
http://newspaper.duxiu.com:80/NPDetail.jsp?dxNumber=300325290163&d=DD9EBC576D0F2530AFAD8D4BF2AB8707
http://book.duxiu.com:80/videoDetail.jsp?dxid=163803630969&d=9D8F4B491F23F40CC4FB78A9FD84C68D
http://book.duxiu.com:80/videoDetail.jsp?dxid=163803613459&d=4AB3C2EB889B03F600C534B6FB7F039F
http://jour.duxiu.com:80/CPDetail.jsp?dxNumber=330107221474&d=DB048A79FEB38102452708AADB2C8C3D
http://book.duxiu.com:80/patentDetail.jsp?dxid=166022216488&d=9E19A092352F1948D5F49FCC047ED567
http://book.duxiu.com:80/StdDetail.jsp?dxid=320150885025&d=4E5400CB12C210379C0120228B11B8BD
http://jour.duxiu.com:80/thesisDetail.jsp?dxNumber=390102513141&d=C90969D30D1392AC1689F64A75418331
http://book.duxi.com:80/godownexam.jsp?dxid=400112204339&d=A5C339C6E04F539F99907F7C6EB28114
http://book.duxiu.com:80/courseDetail.jsp?dxid=400100671692&d=63CDE68AB1857D663BDBD25D7BA230A9&sw=mind&ecode=utf-8
http://book.duxiu.com:80/InfoDetail.jsp?dxNumber=360118685645&d=9259B2820DFD44F2BF758DA1042B19ED
http://book.duxiu.com:80/searchDict?Field=all&channel=searchDict&sw=mind&ecode=utf-8&edtype=&searchtype=&view=0
http://book.duxiu.com:80/searchDict?sw=mind+of+convict+tattoo&channel=searchDict&ecode=utf-8
http://book.duxiu.com:80/EncyDetail.jsp?dxid=403710174382&d=381ABC9CE704439D88399C30752F2025
http://book.duxiu.com:80/EncyDetail.jsp?dxid=403713385167&d=4DB9B4BC318ED0D763FF1E5D8C97FE0B&stitle=carrot
http://vrefer.duxiu.com:80/publicinfoDetail?dxid=400505987423&d=4823920D633F84E1A5831BF35AC1CDB9
http://vrefer.duxiu.com:80/publicinfoDetail?dxid=400504254654&d=2AD1CD09C6341D721FA9D521F5BD5AA8

BOOK PART, HTML
http://book.duxiu.com:80/readDetail.jsp?dxNumber=000016213781&d=BF1D22D4A90B8ADF9CF61B0CCCB1676C&t=1
http://book.duxiu.com:80/readDetail.jsp?dxNumber=000005229290&d=D2D23AD5C1D5E69A0680AEC4A4E9AA2E&t=3

BOOK PART, PDF
http://qw.duxiu.com:80/godownpdf.jsp?kid=65676B686B686C6D3637353530333734&pagenum=99&epage=101&a=188F458266335F85D0B1C7D2B4EEB69D&bt=qw&dxNumber=000030080757&sch=brain&zjid=000030080757_37
http://qw.duxiu.com:80/godownpdf.jsp?kid=6969696D6A6E6B6C3238313035373338&pagenum=109&epage=109&a=8743606FBD35AAB644E9C6EE8FB93B0F&bt=qw&dxNumber=000001309122&sch=brain&zjid=000001309122_132
http://qw.duxiu.com:80/godownpdf.jsp?kid=63666265636B696A3638333139383732&pagenum=29&epage=32&a=477110DE29765CD58BBA62F46000971A&bt=qw&dxNumber=000016139576&sch=Brain-BasedTeaching%A3%A6Learning&zjid=000016139576_29

ARTICLE, PDF
http://book.duxiu.com:80/godowndoc.jsp?dxid=400271577283&d=097B8C533DF3A071F202C9E497E77C29
http://book.duxiu.com:80/godowndoc.jsp?dxid=400278381068&d=38D5441113527B4F570C6964BE0AB856
http://book.duxiu.com:80/godowndoc.jsp?dxid=400640416056&d=7746EE1637C2B4D6C67B2F6827B41DE5
http://book.duxiu.com:80/godownexam.jsp?dxid=400123901604&d=71E3EB46AF2C329B1463813848F39F5E

[DUXIU LOG.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3082259/DUXIU.LOG.txt)

**Comment by lisahamlett** [comment]
You MUST use the search engine to access resources here.  If you click a cover from the main page and try to go to it, it will drop proxy.  I tried tweaking the stanza and could not fix the issue.

**Comment by AGCooper** [comment]
@lisahamlett "BOOK PART" shoud be "BOOK_SECTION"
