### ISSUE TITLE
EIU

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#44]
### Example:star::star: :
country.eiu.com
data.eiu.com
gfs.eiu.com
graphics.eiu.com
portal.eiu.com
search.eiu.com
service.eiu.com
store.eiu.com
viewswire.eiu.com
www.eiu.com

https://login.proxy.library.emory.edu/login?url=http://www.eiu.com/

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
Nothing on AnalogIST, Trello.

Added stanza to ezProxy:
https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/Economist_Intelligence_Unit

**Comment by lisahamlett** [comment]
SEARCH, HTML
http://search.eiu.com:80/default.aspx?sText=potato
http://search.eiu.com:80/default.aspx?sText=goats

ARTICLE, HTML
http://www.eiu.com:80/industry/article/2000497984/usa-food-us-potato-giant-bets-on-biotech-potatoes/2013-05-15
http://www.eiu.com:80/industry/article/417465825/food-and-drink-the-unsung-hero-of-the-external-sector/2018-12-18
http://viewswire.eiu.com:80/index.asp?layout=VWArticleVW3&article_id=725731056
http://country.eiu.com:80/article.aspx?articleid=1987582182
http://country.eiu.com:80/article.aspx?articleid=437449027&Country=Bahamas&topic=Economy
http://country.eiu.com:80/article.aspx?articleid=107592994&Country=Germany&topic=Economy&subtopic=Forecast&subsubtopic=Policy+trends

ARTICLE, PDF
http://industry.eiu.com:80/handlers/filehandler.ashx?issue_id=777081261&mode=pdf
http://www.eiu.com:80/Handlers/WhitepaperHandler.ashx?fi=Democracy_Index_2018.pdf&mode=wp&campaignid=Democracy2018
http://www.eiu.com:80/Handlers/WhitepaperHandler.ashx?fi=Industries_in_2019.pdf&mode=wp&campaignid=Industries2019

DATA, HTML
http://data.eiu.com:80/EIUTableView.aspx?initial=true&pubtype_id=1353181320
http://data.eiu.com:80/EIUTableView.aspx?initial=true&pubtype_id=1393181324

[EIU_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2819207/EIU_log.txt)
