### ISSUE TITLE
SAGE Knowledge (sk)

### ISSUE THREAD

**Issue by lisahamlett** [emory-libraries/ezpaarse-platforms#442]
### Example:star::star: :
http://sk.sagepub.com.proxy.library.emory.edu

### Priority: 
High

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis:
http://ang.couperin.org/platforms/59f165e8884aa7daec163f6e

**Comment by CB987** [comment]
SEARCH;HTML;
http://sk.sagepub.com:80/Data/GetAllLists
http://sk.sagepub.com:80/Data/GetAllLists

TOC;HTML;
http://sk.sagepub.com:80/books/accumulation-by-dispossession?fromsearch=true
http://sk.sagepub.com:80/books/globalization-and-indigenous-peoples-in-asia
http://sk.sagepub.com:80/cqpress/the-new-york-times-on-gay-and-lesbian-issues?fromsearch=true
http://sk.sagepub.com:80/cqpress/mercenaries-a-guide-to-private-armies-and-private-military-companies?fromsearch=true

ABS;HTML;
http://sk.sagepub.com:80/reference/globalstudies?fromsearch=true
http://sk.sagepub.com:80/reference/the-sage-handbook-of-globalization?fromsearch=true
http://sk.sagepub.com:80/reference/schoolchoice?fromsearch=true
http://sk.sagepub.com:80/navigator/international-business-and-globalization?fromsearch=true

BOOK_SECTION;HTML;
http://sk.sagepub.com:80/Data/GetSimilarContent?doi=10.4135%2F9781452218557.n1&eIsbn=9781452218557   same result also http://sk.sagepub.com:80/reference/globalstudies/n1.xml (url of page)
http://sk.sagepub.com:80/Data/GetSimilarContent?doi=10.4135%2F9781452218557.n444&eIsbn=9781452218557
http://sk.sagepub.com:80/Data/GetSimilarContent?doi=10.4135%2F9781452218328.n1&eIsbn=9781452218328
http://sk.sagepub.com:80/Data/GetSimilarContent?doi=10.4135%2F9781608717545.n1&eIsbn=9781608717545
http://sk.sagepub.com:80/Data/GetSimilarContent?doi=10.4135%2F9781483340319.n6&eIsbn=9781483340319

BOOK_SECTION;PDF;
http://sk.sagepub.com:80/reference/download/globalstudies/n444.pdf
http://sk.sagepub.com:80/reference/download/schoolchoice/n1.pdf
http://sk.sagepub.com:80/cqpress/download/mercenaries-a-guide-to-private-armies-and-private-military-companies/n6.i1.pdf

[sk_logs.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3436393/sk_logs.txt)

**Comment by lisahamlett** [comment]
There's a PKB for this one I didn't notice before.  I will update that since no one else is trained on PKB.
Oh, and I'll train Clare for next time.

**Comment by lisahamlett** [comment]
The PKB has been added.
