### ISSUE TITLE
Elgaronline

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#45]
#### Example:star::star: :
https://www-elgaronline-com.proxy.library.emory.edu/

#### Priority: 
Medium

#### Subscriber (Library): 
Woodruff

#### ezPAARSE
Analysis: http://analyses.ezpaarse.org/platforms/56b85fc4b6ff1a4ef762b9a8
Trello: https://trello.com/c/ocpie8qr/316-elgaronline-elgar

**Comment by lisahamlett** [comment]
SEARCH, HTML
https://www.elgaronline.com:443/browse?pageSize=10&level=parent&sort=datedescending&t0=Economics_Main_ID
https://www.elgaronline.com:443/browse?pageSize=10&level=parent&sort=datedescending&t0=LawACA_Main_ID
https://www.elgaronline.com:443/search?q1=computers&searchBtn=
https://www.elgaronline.com:443/search?q1=bananas&searchBtn=
https://www.elgaronline.com:443/search?type_0=series&f_0=series&q_0=Leuven%20Global%20Governance%20series

ABSTRACT, HTML
https://www.elgaronline.com:443/abstract/Research_Reviews/9781785367427/9781785367427.xml?rskey=OfaBR4&result=1
https://www.elgaronline.com:443/abstract/Research_Reviews/9781786438904/9781786438904.xml?rskey=2VKG4N&result=1

BOOK SECTION, HTML
https://www.elgaronline.com:443/view/nlm-book/9781849807777/c04_sec85.xml?rskey=qoQRWS&result=1
https://www.elgaronline.com:443/view/nlm-book/9781849807777/c04_sec21.xml

BOOK SECTION, XML
https://www.elgaronline.com:443/view/9781784711450.00017.xml?rskey=Ye4whX&result=5
https://www.elgaronline.com:443/view/9781784711450.00014.xml

BOOK SECTION, PDF
https://www.elgaronline.com:443/downloadpdf/9781784711450.00017.pdf
https://www.elgaronline.com:443/downloadpdf/9781784711450.00014.pdf

LOG:
[elgaronline.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2271218/elgaronline.txt)
