### ISSUE TITLE
Ethnologue

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#46]
#### Example:star::star: :
https://www-ethnologue-com.proxy.library.emory.edu/

www.ethnologue.com
ethnologue.com

#### Priority: 
Low

#### Subscriber (Library): 
Woodruff

#### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
TOC;HTML
https://www.ethnologue.com:443/browse/countries
https://www.ethnologue.com:443/browse/names/n

ENCYCLOPAEDIA_ENTRY;HTML
https://www.ethnologue.com:443/language/nds
https://www.ethnologue.com:443/language/nds/map
https://www.ethnologue.com:443/cloud/nds
https://www.ethnologue.com:443/country/CO
https://www.ethnologue.com:443/country/JM/languages
https://www.ethnologue.com:443/country/JM/status
https://www.ethnologue.com:443/country/JM/maps
https://www.ethnologue.com:443/map/CRB_n

REF;HTML
https://www.ethnologue.com:443/product/23-Digest-CO

ARTICLE;HTML
https://www.ethnologue.com:443/guides/largest-families

[ethnologue.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4313184/ethnologue.txt)
