### ISSUE TITLE
Euromonitor

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#47]
### Example:star::star: :
https://login.proxy.library.emory.edu/login?url=http://www.portal.euromonitor.com/
http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA51292566810002486

### Priority: 
High

### Subscriber (Library): 

Woodruff

**Comment by lisahamlett** [comment]
https://trello.com/c/6wcpqHbd/160-euromonitor-international
http://ang.couperin.org/platforms/54db34f0eb3a852d79e1d50c

**Comment by lisahamlett** [comment]
[Euromonitor Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1696996/Euromonitor.Links.txt)

**Comment by lisahamlett** [comment]
https://trello.com/c/6wcpqHbd/160-euromonitor-international
http://ang.couperin.org/platforms/54db34f0eb3a852d79e1d50c

Updated stanza in ezProxy:
https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/Passport_Euromonitor_International

**Comment by lisahamlett** [comment]
This thing is a mess.  I will work on links and the parser for this one.

**Comment by lisahamlett** [comment]
Terms and Conditions
http://www.portal.euromonitor.com:80/portal/policy/termsandconditions?ControllerName=Default&ActionName=Index

Accept Terms and Conditions (CONNECTION, MISC)
http://www.portal.euromonitor.com:80/portal/policy/accepttermsandconditions?ControllerName=Default&ActionName=Index

SEARCH, HTML
http://www.portal.euromonitor.com:80/searchui/main.js?version=20180704_1

REPORT, HTML
http://www.portal.euromonitor.com:80/portal/dashboard/analysisrelateddashboards?analysisId=437029&analysisTypeId=1&_=1556038899215
http://www.portal.euromonitor.com:80/portal/dashboard/analysisrelateddashboards?analysisId=431730&analysisTypeId=1&_=1556038977927
http://www.portal.euromonitor.com:80/portal/dashboard/analysisrelateddashboards?analysisId=462055&analysisTypeId=1&_=1556039093829
http://www.portal.euromonitor.com:80/portal/dashboard/analysisrelateddashboards?analysisId=425067&analysisTypeId=1&_=1556039384508

REPORT, PDF
http://www.portal.euromonitor.com:80/portal/analysis/downloadpdf?analysisId=462055&analysisTypeId=1&itemTypeId=48&elementId=0&elementTypeId=0&checksum=014264A2BDEE0CCDE0F27E9FBC42BAFD&searchString=TesT
http://www.portal.euromonitor.com:80/portal/analysis/downloadpdf?analysisId=463751&analysisTypeId=1&itemTypeId=79&elementId=0&elementTypeId=0&checksum=75A5D61DDAAB0566278C42D1A0072DF9&searchString=TesT

DATA, HTML
http://www.portal.euromonitor.com:80/portal/statisticsevolution/exporttoolsasync?measureTypeId=119&_=1556039200418
http://www.portal.euromonitor.com:80/portal/statisticsevolution/exporttoolsasync?measureTypeId=124&_=1556039291849
http://www.portal.euromonitor.com:80/portal/statisticsevolution/exporttoolsasync?measureTypeId=296&_=1556039343412

analysisId = Title ID
_ = Item ID

[euromonitor.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3108846/euromonitor.txt)
