### ISSUE TITLE
Factiva (Woodruff 1)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#48]
### Example:star::star: :
suggest.factiva.com
utilities.factiva.com
viewer.factiva.com
www.wsj.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Card is archived in list 11 - Analysis infeasible
https://trello.com/c/dEbCQsL0/157-factiva#

See also:
http://ang.couperin.org/platforms/54cf77d86fb3dcfacb0a517e

**Comment by lisahamlett** [comment]
suggest.factiva.com, utilities.factiva.com, and viewer.factiva.com are unproxied.
factiva.com does proxy but it's under dowjones.com

I tried to log in/create an account, but it asks for a Corporate ID and Corporate Password.
I don't know what else to do.  :(

I'll upload the log momentarily.  Gotta boot up the linux box.

**Comment by lisahamlett** [comment]
I didn't find much.  I have no idea what the codes mean, but this is what I got.

[factivalinks.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1557060/factivalinks.txt)

**Comment by AGCooper** [comment]
EZpaarse has this platform as unparseable and oblique. That is the urls that are logged do not reflect any content. Parking this issue.

**Comment by lisahamlett** [comment]
From 11/17/2017:
> 
> Card is archived in list 11 - Analysis infeasible
> https://trello.com/c/dEbCQsL0/157-factiva#
> 
> See also:
> http://ang.couperin.org/platforms/54cf77d86fb3dcfacb0a517e
>

Updated OCLC Stanza on Server:
https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/Factiva

**Comment by lisahamlett** [comment]
SEARCH, HTML
https://global.factiva.com:443/ha/default.aspx

AUDIO, MP3
https://global.factiva.com:443/APNRUW0020181003eea5002ut.mp3?tkn=9lqW0VRwuX1Vy8wElyjuGlQnuO5rd42YIqe8DUknG7ucAXG553GSEh6I2PX_2Fm4YWvkfywGSwJMp5vOyMwklFnkd_2B7dnkjKVzD6fbGhdcubB3qv0WemPaLxIy9M0F9Bz76TIyaKW_2BdoiT73iL3b3V_2F0Xz8lu8o4b9tCXy_2F4Z65tKMBHVCqZl3HT0hg9gkBkmGgStYZk_2F2bUrsbfaz5H3pvO_2FvGVqF8fT3enCbvmynHy0_3D_7C2

Actions result in codes like these that mean nothing:
https://global.factiva.com:443/ha/blank.aspx?foo=false&hhid=Id1_109339
https://global.factiva.com:443/ha/blank.aspx?foo=false&hhid=Id2_2ed15b

LOG: [Factiva Log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2443558/Factiva.Log.txt)

Maybe we just do initial connection and let the stakeholders know we can't do anything more than that?  Unless you can see something I can't see...
