### ISSUE TITLE
Heterocycles

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#50]
#### Example:star::star: :
https://www-heterocycles-jp.proxy.library.emory.edu

www.heterocycles.jp
heterocycles.jp

#### Priority: 
Low

#### Subscriber (Library): 
Woodruff

#### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
TOC;HTML
https://www.heterocycles.jp:443/newlibrary/libraries/prepress
https://www.heterocycles.jp:443/newlibrary/libraries/prepress/regular
https://www.heterocycles.jp:443/newlibrary/libraries/journal/98/12/current 
https://www.heterocycles.jp:443/newlibrary/libraries/journal/36/9
https://www.heterocycles.jp:443/newlibrary/libraries/mostcited
https://www.heterocycles.jp:443/newlibrary/special

ARTICLE;HTML
https://www.heterocycles.jp:443/newlibrary/libraries/fulltext/24480/91/9

ARTICLE;PDF
https://www.heterocycles.jp:443/newlibrary/downloads/PDF/26724/100/4
https://www.heterocycles.jp:443/newlibrary/downloads/PDFwithLinks/24480/91/9

SUPPL;PDF
https://www.heterocycles.jp:443/newlibrary/downloads/PDFsi/26724/100/4

ENCYCLOPAEDIA_ENTRY;HTML
https://www.heterocycles.jp:443/newlibrary/natural_products/structure
https://www.heterocycles.jp:443/newlibrary/natural_products/structure/group/Alkaloids
https://www.heterocycles.jp:443/newlibrary/natural_products/structure/journal/OrgBiomolChem
https://www.heterocycles.jp:443/newlibrary/natural_products/synthesis
https://www.heterocycles.jp:443/newlibrary/brushups

[heterocycles.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4313241/heterocycles.txt)
