### ISSUE TITLE
IndiaStat

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#52]
#### Example:star::star: :
https://www-indiastat-com.proxy.library.emory.edu/

www.indiastat.com
indiastat.com

#### Priority: 
Low

#### Subscriber (Library): 
Woodruff

#### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
This website is awful. 😡

**Comment by lisahamlett** [comment]
There's not much here.  Most of the links go to other pages and/or clickbait.

SEARCH;HTML
https://www.indiastat.com:443/Searchresult.aspx

TOC;HTML
https://www.indiastat.com:443/cooperatives-data/104592/stats.aspx
https://www.indiastat.com:443/transport-data/30/roads/246/stats.aspx

DATASET;MISC
https://www.indiastat.com:443/table/agriculture-data/2/retail-prices-of-food-commodities-2019/1209287/1236466/data.aspx
https://www.indiastat.com:443/table/transport-data/30/roads/246/106281/data.aspx

**Comment by lisahamlett** [comment]
[indiastat.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4307911/indiastat.txt)
