### ISSUE TITLE
InfoWeb Readex

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#53]
### Example:star::star: :

All Databases: https://login.proxy.library.emory.edu/login?url=http://www.infoweb.newsbank.com
Access World News: http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA51297546670002486
AccessUN: http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA51298179790002486
Readex: http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA51297172430002486

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
Nothing on Analogist or Trello.

Updated ezProxy stanza:
https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/NewsBank

**Comment by CB987** [comment]
DOMAINS
infoweb.newsbank.com

SEARCH, HTML
- https://infoweb.newsbank.com:443/apps/news/results?p=WORLDNEWS&fld-base-0=alltext&sort=YMD_date%3AD&maxresults=20&val-base-0=rainbow&t=product%3AAWNB
- https://infoweb.newsbank.com:443/apps/news/results?p=WORLDNEWS&t=product%3AAWNB%21Access%2BWorld%2BNews&sort=YMD_date%3AD&fld-base-0=alltext&val-base-0=%28%22climate%20change%22%20OR%20%22global%20warming%22%29%20AND%20%28pope%20OR%20christian%20OR%20catholic%20OR%20religio%2A%29&bln-base-1=AND&fld-base-1=wct&val-base-1=500-999999&maxresults=20&f=topic&landing_topicname=climate-change&landing_subcategory=issues-in-religion&landing_category=religion
- https://infoweb.newsbank.com:443/apps/news/issue-browse?p=WORLDNEWS&t=pubname%3AAEA5%21Albany%2BExaminer%2B%2528GA%2529/year%3A2016%212016/mody%3A0216%21February%2B16&action=browse&format=text
- https://infoweb.newsbank.com:443/apps/news/issue-browse?p=WORLDNEWS&t=pubname%3APBMM%21Business%2BMirror%2B%2528Manila%252C%2BPhilippines%2529/year%3A2019%212019/mody%3A0103%21January%2B03&f=advanced&action=browse&format=text
- https://infoweb.newsbank.com:443/iw-search/we/Static/?p_product=Earth&f_location=earth&p_theme=current&p_action=list&p_nbid=O67S53VOMTU1NjEwOTk5Ny44ODI2Mzg6MToxNToxNzAuMTQwLjE0Mi4yNTI
- https://infoweb.newsbank.com:443/iw-search/we/Static/?p_product=Geog&f_location=geog&p_theme=current&p_action=list&p_nbid=O67S53VOMTU1NjEwOTk5Ny44ODI2Mzg6MToxNToxNzAuMTQwLjE0Mi4yNTI
- https://infoweb.newsbank.com:443/apps/news/hot-topics/current-events?p=Hottopics&pnews=WORLDNEWS
- https://infoweb.newsbank.com:443/apps/news/hot-topics/science%2C-technology-%26-health?p=Hottopics&pnews=WORLDNEWS

ARTICLE, HTML
- https://infoweb.newsbank.com:443/apps/news/document-view?p=WORLDNEWS&t=product%3AAWNB%21Access%2BWorld%2BNews&sort=YMD_date%3AD&fld-base-0=alltext&val-base-0=%28%22climate%20change%22%20OR%20%22global%20warming%22%29%20AND%20%28pope%20OR%20christian%20OR%20catholic%20OR%20religio%2A%29&bln-base-1=AND&fld-base-1=wct&val-base-1=500-999999&maxresults=20&f=topic&landing_topicname=climate-change&landing_subcategory=issues-in-religion&landing_category=religion&docref=news/172C5D542A270400 
- https://infoweb.newsbank.com:443/apps/news/document-view?p=WORLDNEWS&t=product%3AAWNB/stp%3ABlog%21Blog&sort=YMD_date%3AD&fld-base-0=alltext&maxresults=20&val-base-0=rainbow&docref=news/172FFE5E4D54A8A0
- https://infoweb.newsbank.com:443/iw-search/we/Static?p_product=Earth&f_location=earth&p_theme=current&p_action=doc&p_nbid=O67S53VOMTU1NjEwOTk5Ny44ODI2Mzg6MToxNToxNzAuMTQwLjE0Mi4yNTI&f_docnum=172F8EE719450268&f_topic=1&f_prod=BTI2&f_type=&d_refprod=SPECIALREPORTS
-https://infoweb.newsbank.com:443/iw-search/we/Static?p_product=Geog&f_location=geog&p_theme=current&p_action=doc&p_nbid=O67S53VOMTU1NjEwOTk5Ny44ODI2Mzg6MToxNToxNzAuMTQwLjE0Mi4yNTI&f_docnum=13E65170CD4815E0&f_topic=1&f_prod=YEMB&f_type=&d_refprod=SPECIALREPORTS

[newsbank_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3112567/newsbank_log.txt)
