### ISSUE TITLE
IngentaConnect

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#54]
### Example:star::star: :
https://login.proxy.library.emory.edu/login?url=http://www.ingentaconnect.com/
http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA21213043930002486

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
[IgentaConnect Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1700576/IgentaConnect.Links.txt)

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/5a7da6d275cd50e577d60849
https://trello.com/c/jBXBaQ4s/454-ingenta-connect

https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/INGENTAconnect

**Comment by AGCooper** [comment]
[ic.log](https://github.com/emory-libraries/ezpaarse-platforms/files/3108577/ic.log)
