### ISSUE TITLE
Karger Publishers

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#55]
### Example:star::star: :

www.karger.com

### Priority: 

Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/53cce8c1af1a9772d2f5ee0a
https://trello.com/c/ulgk0MZ8/24-karger

**Comment by lisahamlett** [comment]
[Karger Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1657848/Karger.Links.txt)

**Comment by AGCooper** [comment]
This is already part of the current repository. I am adding it to our repository.
