### ISSUE TITLE
LexisNexis

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#56]
### Example:star::star: :
w3.lexisnexis.com
web.lexisnexis.com
www.lexisnexis.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
https://trello.com/c/dh4ZidLi/63-lexisnexis-jurisclasseur-lexisnexis
http://ang.couperin.org/platforms/54106ab65289ee1461720c5c

**Comment by AGCooper** [comment]
Both of these domain names redirect to www.lexisnexis.com

**Comment by AGCooper** [comment]
Is already part of the parser for www.lexisnexis.com [lexisnexis]

**Comment by eipeele** [comment]
Already exists.
