### ISSUE TITLE
Loeb Classics

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#57]
### Example:star::star: :
www.hup.harvard.edu
www.loebclassics.com

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
I think we completed this one when we onboarded Theology:
https://github.com/emory-libraries/ezpaarse-platforms/issues/290
https://github.com/emory-libraries/ezpaarse-platforms/pull/304

**Comment by lisahamlett** [comment]
http://analyses.ezpaarse.org/platforms/5b2bdf3352deebbf1025be9a
https://trello.com/c/hOw9CUVL/478-digital-loeb-classical-library-loeb

I checked HUP, but it is it's own thing.  Everything Loeb on their site refers to loebclassics.com.
