### ISSUE TITLE
Morgan and Claypool Publishers

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#58]
#### Example:star::star: :
https://www-morganclaypool-com.proxy.library.emory.edu/

www.morganclaypool.com
morganclaypool.com

#### Priority: 
Low

#### Subscriber (Library): 
Woodruff

#### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://www.morganclaypool.com:443/action/doSearch?AllField=spider&x=16&y=8&SeriesKey=
https://www.morganclaypool.com:443/page/browseLbS.jsp

TOC;HTML
https://www.morganclaypool.com:443/author/Cambazoglu%2C+B+Barla
https://www.morganclaypool.com:443/loi/icr
https://www.morganclaypool.com:443/toc/icr/9/6
https://www.morganclaypool.com:443/page/colloquium_one

ABS;HTML
https://www.morganclaypool.com:443/doi/abs/10.2200/S00952ED1V01Y201909ICR069
https://www.morganclaypool.com:443/doi/abs/10.4199/C00038ED1V01Y201107DBR002

ARTICLE;PDF
https://www.morganclaypool.com:443/doi/pdf/10.2200/S00952ED1V01Y201909ICR069
https://www.morganclaypool.com:443/doi/pdf/10.4199/C00038ED1V01Y201107DBR002

ARTICLE;PDFPLUS
https://www.morganclaypool.com:443/doi/pdfplus/10.2200/S00952ED1V01Y201909ICR069
https://www.morganclaypool.com:443/doi/pdfplus/10.4199/C00038ED1V01Y201107DBR002

[morganclaypool.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4307965/morganclaypool.txt)
