### ISSUE TITLE
Newspaper Archive

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#59]
### Example:star::star: :

access.newspaperarchive.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
[Newspaper Archive Links.xlsx](https://github.com/emory-libraries/ezpaarse-platforms/files/1657736/Newspaper.Archive.Links.xlsx)

**Comment by lisahamlett** [comment]
[Newspaper Archive Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1657739/Newspaper.Archive.Links.txt)

**Comment by lisahamlett** [comment]
Here are the relevant links with R-type and M-type.
[Newspaper Archive Links with Rtype.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1721768/Newspaper.Archive.Links.with.Rtype.txt)
