### ISSUE TITLE
British Online Archives

### ISSUE THREAD

**Issue by lisahamlett** [emory-libraries/ezpaarse-platforms#608]
### Example:star::star: :
https://microform-digital.proxy.library.emory.edu/boa/

### Priority: 
High

### Subscriber (Library): 
Woodruff Library

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
@CB987 Remember to drop logs on the issue for testing. :)

**Comment by CB987** [comment]
[boa_logs.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4220155/boa_logs.txt)

**Comment by lisahamlett** [comment]
Close but do not add to ezPAARSE!!!  Returns multiple false hits.
