### ISSUE TITLE
A&AePortal

### ISSUE THREAD

**Issue by lisahamlett** [emory-libraries/ezpaarse-platforms#609]
### Example:star::star: :
https://www-aaeportal-com.proxy.library.emory.edu/

### Priority: 
High

### Subscriber (Library): 
Woodruff Library

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by CB987** [comment]
[A&Ae_logs.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4200202/A.Ae_logs.txt)
SEARCH;HTML;
https://www.aaeportal.com:443/?id=-14027&template=template_quicksearch&searchterm=dorothy%20wilyman
https://www.aaeportal.com:443/?id=-14817&advancedsearch=true&pageno=1
https://www.aaeportal.com:443/?id=-14988&advancedsearch=true&pageno=1

TOC;HTML;
https://www.aaeportal.com:443/publications/-19552/mrs--delany-and-her-circle
https://www.aaeportal.com:443/publications/-16879/the-societe-anonyme-and-the-dreier-bequest-at-yale-university--a-catalogue-raisonne
https://www.aaeportal.com:443/publications/-14084/watercolors-by-winslow-homer--the-color-of-light
https://www.aaeportal.com:443/publications/-19551/globalizing-impressionism--reception--translation--and-transnationalism

CHAPTERorBOOK_SECTION;HTML;
https://www.aaeportal.com:443/?id=-14817&fromsearch=true
https://www.aaeportal.com:443/?id=-16891
https://www.aaeportal.com:443/?id=-18378&fromsearch=true

IMAGE?orREF;HTML;
https://www.aaeportal.com:443/images/26465/white-blue
https://www.aaeportal.com:443/images/15716/savoy-vase
https://www.aaeportal.com:443/images/40020/arif-pasha--istanbul

BOOK?orBOOK_SECTION?;HTML; << it says ebook but it seems short for a book. Maybe is article or lesson? Is part of a course pack. Or is also the page for a publisher.
https://www.aaeportal.com:443/?id=10499&cid=-13696 << lesson
https://www.aaeportal.com:443/?id=10559&cid=-13970 << lesson
https://www.aaeportal.com:443/?id=10408&cid=-13811 << lesson
https://www.aaeportal.com:443/?id=10559&cid=-13760 << lesson? 
https://www.aaeportal.com:443/?id=-15795&cid=28813 << publisher
https://www.aaeportal.com:443/?id=-15794&cid=44875 << author
https://www.aaeportal.com:443/?id=-15794&cid=23383 << author page
