### ISSUE TITLE
Open Book Publishers

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#62]
### Example:star::star: :
https://www-openbookpublishers-com.proxy.library.emory.edu/

www.openbookpublishers.com
openbookpublishers.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://www.openbookpublishers.com:443/section/29/1

ABS;HTML
https://www.openbookpublishers.com:443/product/1108

BOOK_SECTION;HTML (.html or .xhtml to prevent scripts from getting caught)
https://www.openbookpublishers.com:443/htmlreader/978-1-78374-137-3/main.html
https://www.openbookpublishers.com:443/htmlreader/978-1-78374-137-3/author.xhtml
https://www.openbookpublishers.com:443/htmlreader/978-1-78374-137-3/intro.xhtml
https://www.openbookpublishers.com:443/htmlreader/978-1-78374-137-3/ch01.xhtml

BOOK_SECTION;PDF
https://www.openbookpublishers.com:443/10.11647/obp.0192.01.pdf
https://www.openbookpublishers.com:443/reader/340

[openbookpublishers.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4308552/openbookpublishers.txt)
