### ISSUE TITLE
Oxford Biblical Studies

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#63]
### Example:star::star: :

www.oxfordbiblicalstudies.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
[Oxford Biblical Studies with RType.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1776679/Oxford.Biblical.Studies.with.RType.txt)
