### ISSUE TITLE
Oxford Bibliographies

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#64]
### Example:star::star: :

www.oxfordbibliographies.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
Domain registered to OXFORD UNIVERSITY PRESS:
http://analogist.couperin.org/platforms/54116a16acd3da4c1bec5684
https://trello.com/c/qMvApJ31/58-oxford-university-press-oup

**Comment by lisahamlett** [comment]
[Oxford Bibliographies Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1696738/Oxford.Bibliographies.Links.txt)

**Comment by lisahamlett** [comment]
[Oxford Bibliographies Links with Rtype.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1721792/Oxford.Bibliographies.Links.with.Rtype.txt)
