### ISSUE TITLE
Oxford Clinical Psychology

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#65]
### Example:star::star: :

www.oxfordclinicalpsych.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
Domain registered to OXFORD UNIVERSITY PRESS:
http://analogist.couperin.org/platforms/54116a16acd3da4c1bec5684
https://trello.com/c/qMvApJ31/58-oxford-university-press-oup

**Comment by lisahamlett** [comment]
[Oxford Clinical Psychology Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1696862/Oxford.Clinical.Psychology.Links.txt)

**Comment by lisahamlett** [comment]
[Oxford Clinical Psychology with Rtype.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1721828/Oxford.Clinical.Psychology.with.Rtype.txt)
