### ISSUE TITLE
Oxford English Dictionary

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#66]
### Example:star::star: :

www.oed.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
[OED with RType.xlsx](https://github.com/emory-libraries/ezpaarse-platforms/files/1782831/OED.with.RType.xlsx)

**Comment by lisahamlett** [comment]
[OEDwithRType.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1782832/OEDwithRType.txt)
