### ISSUE TITLE
Oxford History of Western Music

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#67]
### Example:star::star: :

www.oxfordwesternmusic.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.
[Oxford Western Music with RType.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1776626/Oxford.Western.Music.with.RType.txt)
