### ISSUE TITLE
Policy Map

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#68]
### Example:star::star: :

www.policymap.com

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Nothing on ezPAARSE Trello or ang.couperin.org

**Comment by AGCooper** [comment]
https://trello.com/c/EQiQ5h4h/445-policymap-pm

http://ang.couperin.org/platforms/5a319d6f6028b1e159cd8144
