### ISSUE TITLE
ProQuest

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#70]
### Example:star::star: :
https://www-proquest-com.proxy.library.emory.edu/
For a full list of domains, see https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/ProQuest

### NOTE:
This has been updated on AnalogIST since we did the original fork and will need to be imported from there, not just modified here.
https://github.com/ezpaarse-project/ezpaarse-platforms/tree/master/proquest

### Priority: 
High

### Subscriber (Library): 
Woodruff

### ezPAARSE:
Analysis: http://ang.couperin.org/platforms/552d04c63c918773e8adb432

**Comment by lisahamlett** [comment]
https://trello.com/c/5N6prj6i/178-proquest
http://ang.couperin.org/platforms/552d04c63c918773e8adb432

**Comment by eipeele** [comment]
Example⭐️⭐️ :

1: News Policy and Politics Magazine Archive $40,941
http://www.proquest.com/products-services/News-Policy-Politics-Magazine-Archive.html
2. Women’s Magazine Archive I: One-Time Purchase, $40,941 http://www.proquest.com/products-services/Womens-Magazine-Archive.html
3: History Vault: American Politics and Society from Kennedy to Watergate
http://cisupa.proquest.com/ksc_assets/history_vault/americanpoliticsandsociety.pdf
4: History Vault: Women’s Studies from the Schlesinger Library Collections
http://cisupa.proquest.com/ksc_assets/history_vault/struggleforwomen.pdf
5: History Vault: American Indians and the American West, 1809-1971
http://proquest.libguides.com/historyvault/amerindians
6: History Vault: Immigration: Records of the INS http://cisupa.proquest.com/ksc_assets/history_vault/immigration_insrecords.pdf
7: History Vault: American Politics and the Early Cold War—Truman and Eisenhower Administrations, 1945-1961

Priority:

High

Subscriber (Library):

Woodruff

#Note: ProQuest isn't a completed parser from EZPaarse, so this may need to wait until that is complete or at least in available beta.

**Comment by eipeele** [comment]
Being worked on by the EZPaarse community at large.  Parked until that community has released a version.

**Comment by eipeele** [comment]
Adding newspaperslibrary.proquest.com

*check when community releases

**Comment by lisahamlett** [comment]
This is listed as "up to date" on AnalogIST as of October 16, 2018.

**Comment by lisahamlett** [comment]
Since the data in Couperin is newer than what is in our repository, we first need to copy the data from the main repository and update ours.  Then we can add anything that is missing since this hasn't been updated since 2017

**Comment by lisahamlett** [comment]
[proquest.log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3273656/proquest.log.txt)
