### ISSUE TITLE
RoperWeb

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#71]
### Example:star::star: :
https://www-ropercenter-cornell-edu.proxy.library.emory.edu/

ropercenter.cornell.edu
roperweb.ropercenter.cornell.edu
www.ropercenter.cornell.edu

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://ropercenter.cornell.edu:443/CFIDE/cf/action/ipoll/ipollResult.cfm?keyword=dwight+eisenhower
https://ropercenter.cornell.edu:443/CFIDE/cf/action/ipoll/ipollResult.cfm?filterSearchWithin=Search+Within&keywordDisplay=dwight%2520eisenhower
https://ropercenter.cornell.edu:443/CFIDE/cf/action/ipoll/ipollResult.cfm?keyword=&exclude=&topic=taxing&organization=Any&fromDate=&toDate=&questionViewId=&label=&studyId=&sortBy=BEG_DATE_DESC

REF;MISC
https://ropercenter.cornell.edu:443/CFIDE/cf/action/ipoll/questionDetail.cfm?keyword=&keywordoptions=1&exclude=&excludeOptions=1&topic=taxing&organization=Any&label=&fromdate=1/1/1935&toDate=&stitle=&sponsor=Fox%20News&studydate=01-JAN-34&sample=1000&qstn_list=&qstnid=1945594&qa_list=&qstn_id4=1945594&study_list=&lastSearchId=317679980979&archno=&keywordDisplay=
https://ropercenter.cornell.edu:443/CFIDE/cf/action/ipoll/questionDetail.cfm?keyword=80653&keywordoptions=&exclude=&excludeOptions=&topic=Any&organization=Any&label=&fromdate=1/1/1935&toDate=&stitle=&sponsor=Fox%20News&studydate=01-JAN-34&sample=1000&qstn_list=&qstnid=1945594&qa_list=&qstn_id4=1945594&study_list=&lastSearchId=317679980982&archno=&keywordDisplay=

REF;MISC
https://ropercenter.cornell.edu:443/CFIDE/cf/action/ipoll/downloadQSTN.cfm?ref=questionDetail&txt=1&questionID=1945594
https://ropercenter.cornell.edu:443/CFIDE/cf/action/ipoll/downloadQSTN.cfm?ref=questionDetail&csv=1&questionID=1945594

[ropercenter.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4308015/ropercenter.txt)
