### ISSUE TITLE
Routledge Encyclopedia of Philosophy Online

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#72]
### Example:star::star: :
https://www-rep-routledge-com.proxy.library.emory.edu/

www.rep.routledge.com
rep.routledge.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://www.rep.routledge.com:443/search?searchString=immanuel+kant&newSearch=

ABS;HTML
https://www.rep.routledge.com:443/articles/biographical/kant-immanuel-1724-1804/v-1
https://www.rep.routledge.com:443/articles/overview/medieval-philosophy/v-1
https://www.rep.routledge.com:443/articles/thematic/business-ethics/v-1

ARTICLE;HTML
https://www.rep.routledge.com:443/articles/biographical/kant-immanuel-1724-1804/v-1/sections/pure-concepts-of-the-understanding
https://www.rep.routledge.com:443/articles/overview/medieval-philosophy/v-1/sections/philosophical-theology-1
https://www.rep.routledge.com:443/articles/thematic/business-ethics/v-1/sections/external-stakeholders-social-responsibility

SUPPL;HTML
https://www.rep.routledge.com:443/articles/thematic/business-ethics/v-1/bibliography/business-ethics-bib

[rep-routledge.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4308066/rep-routledge.txt)
