### ISSUE TITLE
Routledge Handbooks Online (Woodruff 2)

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#73]
### Example:star::star: :

www.routledgehandbooks.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
Routledge is a division of Taylor & Francis Publishers / Informa Group.
I'm not sure how the structure there works, but thought it might be worth pointing out.

**Comment by lisahamlett** [comment]
[Routledge Handbooks Online Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1696620/Routledge.Handbooks.Online.Links.txt)

**Comment by lisahamlett** [comment]
[Routledge Handbooks Links with Rtype.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1721901/Routledge.Handbooks.Links.with.Rtype.txt)

**Comment by AGCooper** [comment]
Part of Taylor and Francis
