### ISSUE TITLE
Safari Tech Books Online

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#74]
### Example:star::star: :

ssl.safaribooksonline.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by AGCooper** [comment]
The link we have to Safari books in D@E is proquest.safaribooksonline.com. So is this part of proquest?

**Comment by AGCooper** [comment]
ssl.safaribooksonline.com redirects to safari5.bvdep.com which doesn't seem to be much for us.

**Comment by lisahamlett** [comment]
Going through discoverE redirects to https://learning.oreilly.com:
http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA51364853650002486
The safaribooksonline.com domain does not exist anymore, so I am closing this issue.
I will look at putting in one for O'Reilly instead.
