### ISSUE TITLE
Sage Journals

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#75]
### Example:star::star: :

uk.sagepub.com => us.sagepub.com (redirect)

methods.sagepub.com

### Priority: 
High

### Subscriber (Library): 
Shared

### Analysis:
http://ang.couperin.org/platforms/5587c180b51a32a3375cfe1d

**Comment by AGCooper** [comment]
Apparently this is part of High Wire.

**Comment by AGCooper** [comment]
Also part of high wire. hw_AllTitles_2016-12-19.txt

**Comment by AGCooper** [comment]
Actually this is really confusing. There are dozens of references to different sage publications. But the sage journals have their own platform. And the only other url I can find (at least in today's log) is for methods, which seems to be different from journals.

**Comment by AGCooper** [comment]
Sage Journals are already being parsed so I'm moving this to done.
