### ISSUE TITLE
SciVerse Scopus

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#76]
### Example:star::star: :

syndic8.scopus.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by eipeele** [comment]
This is a URL that takes you to a Scopus HTML feeder.  Scopus overall is already a parser.  Possibly not necessary to add this.

**Comment by lisahamlett** [comment]
SEARCH, HTML
https://www.scopus.com:443/results/results.uri?numberOfFields=0&src=s&clickedLink=&edit=&editSaveSearch=&origin=searchbasic&authorTab=&affiliationTab=&advancedTab=&scint=1&menu=search&tablin=&searchterm1=windows&field1=TITLE_ABS_KEY&dateType=Publication_Date_Type&yearFrom=Before+1960&yearTo=Present&loadDate=7&documenttype=All&accessTypes=All&resetFormLink=&st1=windows&st2=&sot=b&sdt=b&sl=22&s=TITLE-ABS-KEY%28windows%29&sid=8347198d14a9e2ca0df729eef8c1d9a9&searchId=8347198d14a9e2ca0df729eef8c1d9a9&txGid=d826d5e76f142f5920b8fa38394f09b4&sort=plf-f&originationType=b&rr=
https://www.scopus.com:443/results/results.uri?src=p&sort=plf-f&st1=windows&st2=&sid=8347198d14a9e2ca0df729eef8c1d9a9&sot=b&sdt=b&sl=22&s=TITLE-ABS-KEY%28windows%29&cl=t&offset=1&ss=plf-f&ws=r-f&ps=r-f&cs=r-f&origin=resultslist&zone=queryBar

ABSTRACT, HTML
https://www.scopus.com:443/record/display.uri?eid=2-s2.0-85048661176&origin=resultslist&sort=plf-f&src=s&st1=windows&st2=&sid=8347198d14a9e2ca0df729eef8c1d9a9&sot=b&sdt=b&sl=22&s=TITLE-ABS-KEY%28windows%29&relpos=0&citeCnt=0&searchTerm=
https://www.scopus.com:443/record/display.uri?eid=2-s2.0-85042539108&origin=resultslist&sort=plf-f&src=s&sid=9bb807a7ea1b25ed02c6722305550f17&sot=a&sdt=a&sl=17&s=SOURCE-ID+%2828773%29&relpos=0&citeCnt=0&searchTerm=

ABSTRACT, PDF
https://www.scopus.com:443/record/pdfdownload.uri?origin=recordpage&sid=&src=s&stateKey=OFD_972761636&eid=2-s2.0-85048661176&sort=&listId=&clickedLink=&selectedCitationInformationItemsAll=on&selectedCitationInformationItems=Author%28s%29&selectedCitationInformationItems=Document+title&selectedCitationInformationItems=Year&selectedCitationInformationItems=Source+title&selectedCitationInformationItems=Volume%2C+issue%2C+pages&selectedCitationInformationItems=Citation+count&selectedCitationInformationItems=Source+%26+document+type&selectedCitationInformationItems=EID&selectedCitationInformationItems=Access+Type%09%09%09%09
https://www.scopus.com:443/record/pdfdownload.uri?origin=recordpage&sid=&src=s&stateKey=OFD_972761636&eid=2-s2.0-85042539108&sort=&listId=&clickedLink=&selectedCitationInformationItemsAll=on&selectedCitationInformationItems=Author%28s%29&selectedCitationInformationItems=Document+title&selectedCitationInformationItems=Year&selectedCitationInformationItems=Source+title&selectedCitationInformationItems=Volume%2C+issue%2C+pages&selectedCitationInformationItems=Citation+count&selectedCitationInformationItems=Source+%26+document+type&selectedCitationInformationItems=EID&selectedCitationInformationItems=Access+Type%09%09%09%09

TOC, HTML
https://www.scopus.com:443/sources.uri?zone=TopNavBar&origin=resultslist
https://www.scopus.com:443/sourceid/28773

LOG:
[Scopus.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2254356/Scopus.txt)

**Comment by lisahamlett** [comment]
Didn't see Elizabeth's note...
I can't find anything that syndic8.scopus.com does... 

When you access it, you get this: https://syndic8.scopus.com:443/action/manage

Log entry:
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:41:21 -0400] "GET http://syndic8.scopus.com:80/ HTTP/1.1" 302 0 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:41:21 -0400] "GET https://syndic8.scopus.com:443/ HTTP/1.1" 200 862 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:41:21 -0400] "GET https://syndic8.scopus.com:443/action/manage HTTP/1.1" 200 13411 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:41:22 -0400] "GET https://syndic8.scopus.com:443/images/logo_Elsevier.svg HTTP/1.1" 200 2051 https://syndic8-scopus-com.proxy.library.emory.edu/action/manage Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:41:22 -0400] "GET https://syndic8.scopus.com:443/action/platformFile?name=RssScopusLogoOrange.svg&contentType=image/svg%2Bxml&platformCode=SC HTTP/1.1" 200 1776 https://syndic8-scopus-com.proxy.library.emory.edu/pages/common/style.jsp?components=login&platformCode=SC&ver=1.0 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:41:22 -0400] "GET https://syndic8.scopus.com:443/images/relexLogo.svg HTTP/1.1" 200 3423 https://syndic8-scopus-com.proxy.library.emory.edu/action/manage Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.213.222 KWLd4njZSFMnxU3 lhamlet [02/Aug/2018:12:41:58 -0400] "GET http://proxy.library.emory.edu:80/admin HTTP/1.1" 200 339 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

**Comment by eipeele** [comment]
I'm with Lisa on this.  Just add that one thing to see if people use it.

**Comment by eipeele** [comment]
@AGCooper will this be worked on or does it need to move to another project?

**Comment by lisahamlett** [comment]
Parser: https://github.com/emory-libraries/ezpaarse-platforms/tree/master/scopus

http://ang.couperin.org/platforms/54118eed4892f3207f4d0aa6
https://trello.com/c/NziIJj8x/77-scopus

**Comment by lisahamlett** [comment]
https://github.com/emory-libraries/ezpaarse-platforms/tree/master/scopus

http://ang.couperin.org/platforms/54118eed4892f3207f4d0aa6
https://trello.com/c/NziIJj8x/77-scopus

CONNECTION, MISC
https://syndic8.scopus.com:443/action/manage?currentActivity=null

SEARCH, HTML
https://www.scopus.com:443/results/results.uri?numberOfFields=0&src=s&clickedLink=&edit=&editSaveSearch=&origin=searchbasic&authorTab=&affiliationTab=&advancedTab=&scint=1&menu=search&tablin=&searchterm1=Robots&field1=TITLE_ABS_KEY&dateType=Publication_Date_Type&yearFrom=Before+1960&yearTo=Present&loadDate=7&documenttype=All&accessTypes=All&resetFormLink=&st1=Robots&st2=&sot=b&sdt=b&sl=21&s=TITLE-ABS-KEY%28Robots%29&sid=b72f503f1be3971c39b816da2ca468f6&searchId=b72f503f1be3971c39b816da2ca468f6&txGid=ed12a4401291d345f219edd30a592986&sort=plf-f&originationType=b&rr=
https://www.scopus.com:443/results/results.uri?editSaveSearch=&sort=plf-f&src=s&st1=Robots&nlo=&nlr=&nls=&sid=738cfe6dd647d3d7f26d96236249be1f&sot=b&sdt=sisr&sl=21&s=TITLE-ABS-KEY%28Robots%29&ref=%28salad%29&origin=resultslist&zone=leftSideBar&txGid=19e24613138faa85db1709fffd933364
https://www.scopus.com:443/sources.uri?zone=TopNavBar&origin=resultslist
https://www.scopus.com:443/sources?sortField=citescore&sortDirection=desc&isHiddenField=false&field=subject&subject=&asjcs=1108&Apply=Apply&_openAccess=on&_countCheck=on&count=0&countField=documentsMin&_bestPercentile=on&_quartile=on&_quartile=on&_quartile=on&_quartile=on&_type=on&_type=on&_type=on&_type=on&year=2017&offset=&resultsPerPage=20
https://www.scopus.com:443/results/authorNamesList.uri?origin=searchauthorlookup&src=al&edit=&poppUp=&basicTab=&affiliationTab=&advancedTab=&st1=Smith&st2=&institute=&orcidId=&authSubject=LFSC&_authSubject=on&authSubject=HLSC&_authSubject=on&authSubject=PHSC&_authSubject=on&authSubject=SOSC&_authSubject=on&s=AUTHLASTNAME%28Smith%29&sdt=al&sot=al&searchId=86319d2b10ae6a14f43258cbdd10ae4d&exactSearch=off&sid=86319d2b10ae6a14f43258cbdd10ae4d
https://www.scopus.com:443/results/affiliationResults.uri?origin=SearchAffiliationLookup&selectionPageSearch=afsp&affilFormOnly=true&src=af&edit=&affilCity=&affilCntry=&authorTab=&basicTab=&advancedTab=&basicAffilSearchTab=&affilName=Emory&s=AFFIL%28Emory%29&sl=12&sdt=aff&sot=afsp&sort=afcnt-f&searchId=870e06af22fd9be4356f612b0badaad0&sid=870e06af22fd9be4356f612b0badaad0

REF, HTML
https://www.scopus.com:443/sourceid/21100773746
https://www.scopus.com:443/sourceid/24004

TOC, HTML
https://www.scopus.com:443/source/retrieveDocs.uri?sourceId=24004&year=2017&docType=so&pg=1
https://www.scopus.com:443/source/retrieveDocs.uri?sourceId=21100773746&year=2017&docType=cc&pg=1
