### ISSUE TITLE
Social Explorer

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#77]
### Example:star::star: :

www.socialexplorer.com

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
This one drops proxy whenever you open it.

**Comment by AGCooper** [comment]
EZProxxy is only an entry point for this platform, that's why the parser is so small.
