### ISSUE TITLE
Sociometrics

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#78]
### Example:star::star: :
https://www-socio-com.proxy.library.emory.edu/

Technically, we only have subscription to the data products ( https://www-socio-com.proxy.library.emory.edu/products/data ) but we should parse it all in case we expand the subscription at some point.

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: None
Trello: None

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello.

TOC, HTML
https://www.socio.com:443/products/evidence_based_programs
https://www.socio.com:443/products/capacity_building_tools
https://www.socio.com:443/products/data
https://www.socio.com:443/products/dasra2324
https://www.socio.com:443/products/dils-data-and-internet-literacy-series
https://www.socio.com:443/products/dasra0102

SEARCH, HTML
https://www.socio.com:443/products?utf8=%E2%9C%93&keywords=commodore+64&x=0&y=0
https://www.socio.com:443/products?utf8=%E2%9C%93&keywords=bananas&x=0&y=0

BOOK PART, HTML
https://www.socio.com:443/products/dasra2324/contents/14509
https://www.socio.com:443/products/dasra2324/contents/2039
https://www.socio.com:443/products/dasra0102/contents/2068

LOG:
[sociometrics.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2271402/sociometrics.txt)

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://www.socio.com:443/products
https://www.socio.com:443/products/data
https://www.socio.com:443/products?utf8=%E2%9C%93&keywords=potato&x=0&y=0
https://www.socio.com:443/products?utf8=%E2%9C%93&per_page=&search%5Bresource_type%5D%5B%5D=2&keywords=infant

ABS;HTML
https://www.socio.com:443/products/infant-stimulation-and-physical-therapy-an-early-intervention-program-for-children-with-spastic-diplegia
https://www.socio.com:443/products/daappp-99

SUPPL;HTML
https://www.socio.com:443/products/daappp-99/contents/4466

SUPPL;MISC
https://www.socio.com:443/products/daappp-99/contents/4466/download
https://www.socio.com:443/products/mda-0103/contents/download_all

[socio_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3517870/socio_log.txt)
