### ISSUE TITLE
SourceOECD/iLibrary

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#79]
### Example:star::star: :

www.oecd-ilibrary.org

~unilibrary.org (wouldn't load as of 12/6/2017)~

http://www.un-ilibrary.org/ (12/20/2017)

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Didn't parse: http://www.oecd-ilibrary.org/urban-rural-and-regional-development/data/small-regions-tl3/demographic-statistics_data-00525-en

**Comment by AGCooper** [comment]
Pull request merged and all done.
