### ISSUE TITLE
The History Makers

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#81]
### Example:star::star: :
https://www-thehistorymakers-org.proxy.library.emory.edu/

da.thehistorymakers.org
devwww.thehistorymakers.org
emory.thehistorymakers.org
marc.thehistorymakers.org
smdigital.thehistorymakers.org
thmdigital.thehistorymakers.org
www.thehistorymakers.org
thehistorymakers.org

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
SEARCH;HTML
https://www.thehistorymakers.org:443/search?search_api_fulltext=martin+luther+king
https://www.thehistorymakers.org:443/advanced-search?search_api_fulltext=atlanta

REF;HTML
https://www.thehistorymakers.org:443/media
https://www.thehistorymakers.org:443/special-collections
https://www-thehistorymakers-org:443/special-events
https://www-thehistorymakers-org:443/education
https://www-thehistorymakers-org:443/digital-humanities
https://www-thehistorymakers-org:443/digital-archives

ABS;HTML
https://www-thehistorymakers-org:443/special-collections/details/pioneers-struggle
https://www-thehistorymakers-org:443/node/114863

BIO;HTML
https://www.thehistorymakers.org:443/biography/luther-williams-41
https://www.thehistorymakers.org:443/biography/judy-richardson-41

DATASET;MISC
https://devwww.thehistorymakers.org:443/pits/

REF;PDF
https://devwww.thehistorymakers.org:443/sites/default/files/2019-01/PITS%20Curriculum_0.pdf
http://www.thehistorymakers.org:80/sites/production/files/S2001_014_PITS_EAD_WEB.pdf

[thehistorymakers.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4653081/thehistorymakers.txt)
