### ISSUE TITLE
Tibetan Buddhist Resource Center

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#83]
### Example:star::star: :
https://www-tbrc-org.proxy.library.emory.edu
https://www-tbrc-org.proxy.library.emory.edu/#!specials/core

www.tbrc.org
tbrc.org

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
Most results such as searches and browses are all POSTs.

IMAGE;MISC
https://www.tbrc.org:443/browser/ImageService?work=W23762&igroup=2636&image=230&first=230&last=233&fetchimg=yes
https://www.tbrc.org:443/browser/ImageService?work=W1KG4531&igroup=I1KG4559&image=1&first=1&last=186&fetchimg=yes

BOOK_SECTION;PDF
http://www.tbrc.org:80/eBooks/W23762-2636-230-233-abs.pdf
http://www.tbrc.org:80/eBooks/W1KG4531-I1KG4559-1-186-abs.pdf
http://www.tbrc.org:80/eBooks/W23762-2636-230-233-any.pdf
http://www.tbrc.org:80/eBooks/W1KG4531-I1KG4559-1-186-any.pdf

[tbrc.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/4653226/tbrc.txt)
