### ISSUE TITLE
University of Chicago Journals

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#84]
### Example:star::star: :

www.journals.uchicago.edu

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
Links: 
[uchicagojournals.log](https://github.com/emory-libraries/ezpaarse-platforms/files/1583388/uchicagojournals.log)

**Comment by lisahamlett** [comment]
Full log, per your request:
[uchicagoLH.log](https://github.com/emory-libraries/ezpaarse-platforms/files/1598814/uchicagoLH.log)
