### ISSUE TITLE
University Press Scholarship Online

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#85]
### Example:star::star: :

stanford.universitypressscholarship.com
www.universitypressscholarship.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by AGCooper** [comment]
https://trello.com/c/aTeRUGDW/346-university-press-scholarship-online-upso

http://ang.couperin.org/platforms/573b2ce4a9a670fcddddabc3
