### ISSUE TITLE
Vault Campus Edition

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#86]
### Example:star::star: :
access.vault.com
guides.vault.com
jobs.vault.com
www.vault.com
careerinsider.vault.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
SEARCH, HTML
http://www.vault.com:80/search-results?q=google&wt=comp
http://www.vault.com:80/search-results?q=boeing&wt=comp

ARTICLE, HTML
http://www.vault.com:80/internship_program/aerospace/boeing-company/overview
http://www.vault.com:80/internship-rankings/best-tech-engineering-internships/
http://www.vault.com:80/internship_program/commercial-banking-and-financial-services/barclays-investment-bank-(americas)-functions-and-technology-summer-analyst-and-associate-programs/overview
http://www.vault.com:80/company-profiles/management-strategy/at-kearney/employee-reviews
http://www.vault.com:80/company-profiles/management-strategy/at-kearney/company-reviews
http://www.vault.com:80/internship-rankings/most-prestigious-companies-to-intern-for/
http://www.vault.com:80/school_profiles/undergrad/tufts-university
http://www.vault.com:80/product.aspx?isbn=9781438177014
http://www.vault.com:80/product.aspx?isbn=9781438167589

TOC, HTML
http://www.vault.com:80/rankings-reviews
http://www.vault.com:80/internship-programs
http://www.vault.com:80/resumes
http://www.vault.com:80/rankings-reviews/schools/explore-colleges
http://www.vault.com:80/vault-guide.aspx
http://www.vault.com:80/category.aspx?id=125581
http://jobs.vault.com:80/JobSeeker/JobList.aspx

LOG
[Vault.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2251290/Vault.txt)
:
