### ISSUE TITLE
Web of Knowledge

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#87]
### Example:star::star: :
toc.webofknowledge.com
www.researcherid.com

### Priority: 
High

### Subscriber (Library): 
Shared

**Comment by eipeele** [comment]
Only missing a couple of domains:  https://github.com/ezpaarse-project/ezpaarse-platforms/tree/master/wos

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/5878908edb308a343cf604c6
https://trello.com/c/8ksAEfB1/394-web-of-science-wos

toc.webofknowledge.com throws an error

SEARCH, HTML
http://apps.webofknowledge.com:80/Search.do?product=WOS&SID=7DA7CXc69C6iBjcTsUO&search_mode=GeneralSearch&prID=1d45cacc-27f0-44c2-987a-127c4c2eb80f
http://apps.webofknowledge.com:80/Search.do?product=WOS&SID=7DA7CXc69C6iBjcTsUO&search_mode=GeneralSearch&prID=f61cb3cb-d64f-4157-ad46-d910e755eaf8
http://apps.webofknowledge.com:80/OneClickSearch.do?product=WOS&search_mode=OneClickSearch&excludeEventConfig=ExcludeIfFromFullRecPage&colName=WOS&SID=7DA7CXc69C6iBjcTsUO&field=AU&value=Zheng,%20DM
http://www.researcherid.com:80/ViewHomePageProfileSearch.action;jsessionid=4FEB05D72CFAC9E8E29C18C5BB0C730B
http://www.researcherid.com:80/rid/F-5186-2010
http://www.researcherid.com:80/rid/F-1214-2017
http://www.researcherid.com:80/ViewProfileSearch.action

ABSTRACT, HTML
http://apps.webofknowledge.com:80/full_record.do?product=WOS&search_mode=GeneralSearch&qid=1&SID=7DA7CXc69C6iBjcTsUO&page=1&doc=1
http://apps.webofknowledge.com:80/CitedFullRecord.do?product=WOS&colName=WOS&SID=7DA7CXc69C6iBjcTsUO&search_mode=CitedFullRecord&isickref=WOS:000176486900010&cacheurlFromRightClick=no
http://apps.webofknowledge.com:80/full_record.do?product=WOS&search_mode=GeneralSearch&qid=9&SID=7DA7CXc69C6iBjcTsUO&page=1&doc=1
http://apps.webofknowledge.com:80/?product=WOS&DestParams=%3FUT%3DWOS%3A000345974300009%26customersID%3DRID%26product%3DWOS%26action%3Dretrieve%26mode%3DFullRecord&Func=Frame&DestFail=http%3A%2F%2Fwww.webofknowledge.com&SrcApp=RID&SrcAuth=RID&SID=7DA7CXc69C6iBjcTsUO&customersID=RID&mode=FullRecord&IsProductCode=Yes&Init=Yes&DestApp=WOS&action=retrieve&UT=WOS%3A000345974300009

LOG:
[WOS.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2254734/WOS.txt)
