### ISSUE TITLE
Worldcat

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#89]
### Example:star::star: :
Emory Databases routes through Galileo, which is weird...
https://proxy.library.emory.edu/login?url=http://www.galileo.usg.edu/express?link=zowc 

Actual Proxy Link:
https://emory-on-worldcat-org.proxy.library.emory.edu/advancedsearch?databaseList=283

### Priority: 
High

### Subscriber (Library): 
Shared

**Comment by lisahamlett** [comment]
Couldn't find anything on AnalogIST or Trello.

**Comment by lisahamlett** [comment]
[Worldcat Links.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1696685/Worldcat.Links.txt)

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello.

https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/OCLC_WorldCat_Discovery
https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/OCLC_WorldCat_Local

**Comment by lisahamlett** [comment]
SEARCH, HTML
https://emory.on.worldcat.org:443/search?queryString=kw%3A%28potato%29&databaseList=283&origPageViewName=pages%2Fadvanced-search-page&clusterResults=true&scope=
https://emory.on.worldcat.org:443/search?queryString=au%3DBaker%2C%20Keith&databaseList=283
https://emory.on.worldcat.org:443/search?sortKey=BEST_MATCH&databaseList=283&queryString=au%3DBaker%2C+Keith&changedFacet=author&clusterResults=on&scope=&format=all&database=all&author=Booth%2C+David&year=all&yearFrom=&yearTo=&language=all&topic=all
https://emory.on.worldcat.org:443/search?queryString=ti%3A%28Tom+Sawyer+Abroad%29&databaseList=283&origPageViewName=pages%2Fadvanced-search-page&clusterResults=true&scope=
https://emory.on.worldcat.org:443/search?databaseList=283&queryString=se:The%20Oxford%20Mark%20Twain

REF, HTML
https://emory.on.worldcat.org:443/ajax/public/holdings/1782154/1?address=&scope=
https://emory.on.worldcat.org:443/ajax/public/holdings/9986818/1?address=&scope=
https://emory.on.worldcat.org:443/ajax/public/holdings/64624802/1?address=&scope=
https://emory.on.worldcat.org:443/ajax/public/holdings/34515238/1?address=&scope=

[Worldcat.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3108681/Worldcat.txt)

**Comment by lisahamlett** [comment]
REF is something like this:
/^\/ajax\/public\/holdings\/([0-9]+)\/1
title_id = unitid = match[1]
