### ISSUE TITLE
WanFang Data

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#91]
### Example:star::star: :

ad.wanfangdata.com.cn
c.g.wanfangdata.com.cn
c.wanfangdata.com.cn
check.wanfangdata.com.cn
d.g.wanfangdata.com.cn
d.wanfangdata.com.cn
g.wanfangdata.com.cn

### Priority: 
Low

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Duplicate with https://github.com/emory-libraries/ezpaarse-platforms/issues/42
