### ISSUE TITLE
The American Journal of Psychiatry

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#92]
### Example:star::star: :
ajp.psychiatryonline.org

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by AGCooper** [comment]
AJP is part of psychiatryonline.

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/573b34ffc6bd6e67576d6750
https://trello.com/c/VX4gydMO/351-psychiatryonline-po

Added Stanza to ezProxy:
https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/PsychiatryOnline

**Comment by lisahamlett** [comment]
https://github.com/emory-libraries/ezpaarse-platforms/tree/master/PO

**Comment by lisahamlett** [comment]
This is already included in PsychiatryOnline, so I am closing the ticket.
