### ISSUE TITLE
American Public Health Association [AJHP]

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#93]
### Example:star::star: :

ajph.aphapublications.org
http://ajph.aphapublications.org/
### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by eipeele** [comment]
https://trello.com/c/MYQDjxzI/352-american-journal-of-public-health-ajph

**Comment by AGCooper** [comment]
http://ang.couperin.org/platforms/573b356237cfe8c752b31b66

proxytest.library.emory.edu/login?url=http://ajph.aphapublications.org

**Comment by lisahamlett** [comment]
[ajphdone.log](https://github.com/emory-libraries/ezpaarse-platforms/files/1479876/ajphdone.log)
Here's the file of links.
