### ISSUE TITLE
Annual Reviews

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#94]
### Example:star::star: :

anthro.annualreviews.org
www.annualreviews.org

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by AGCooper** [comment]
This is already in ezpaarse.

https://trello.com/c/CFJL0U1t/42-annual-reviews-ar
http://ang.couperin.org/platforms/5408d15fbdaeda681daa6a70
