### ISSUE TITLE
e-Korean Studies

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#95]
### Example:star::star: :
http://e-koreanstudies.com.proxy.library.emory.edu/

e-koreanstudies.com
www.e-koreanstudies.com

### Priority: 
Low

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://ang.couperin.org/platforms/to_be_completed/

**Comment by lisahamlett** [comment]
www.e-koreanstudies.com is no longer a website.  If it pops back up later, we'll work on it then.
