### ISSUE TITLE
World Bank e-Library

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#96]
### Example:star::star: :
https://elibrary-worldbank-org.proxy.library.emory.edu/

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

### ezPAARSE
Analysis: http://analyses.ezpaarse.org/platforms/552cfa3f35ed938324892385
Trello: https://trello.com/c/DUwkMLMU/205-world-bank

**Comment by lisahamlett** [comment]
http://analyses.ezpaarse.org/platforms/552cfa3f35ed938324892385
https://trello.com/c/DUwkMLMU/205-world-bank

**Comment by lisahamlett** [comment]
SEARCH, HTML
https://elibrary.worldbank.org:443/action/doSearch?AllField=bananas
https://elibrary.worldbank.org:443/page/wb-regions
https://elibrary.worldbank.org:443/page/wb-topics
https://elibrary.worldbank.org:443/page/wb-books
https://elibrary.worldbank.org:443/page/recommended-readings
https://elibrary.worldbank.org:443/page/wb-other-research
https://elibrary.worldbank.org:443/topic/be
https://elibrary.worldbank.org:443/topic/t021
https://elibrary.worldbank.org:443/action/showPublications?PubType=type-other-research&SeriesKey=kp03
https://elibrary.worldbank.org:443/action/showDataView?region=be

TOC, HTML
https://elibrary.worldbank.org:443/doi/book/10.1596/978-1-4648-1281-1?chapterTab=true
https://elibrary.worldbank.org:443/loi/wber
https://elibrary.worldbank.org:443/toc/wber/24/3
https://elibrary.worldbank.org:443/loi/deor
https://elibrary.worldbank.org:443/toc/deor/12/2
https://elibrary.worldbank.org:443/doi/book/10.1596/978-0-8213-9635-3?chapterTab=true

DATASET, HTML (not sure what we call these)
https://elibrary.worldbank.org:443/action/showDataView?indicator=SH.DYN.MORT
https://elibrary.worldbank.org:443/action/showDataView?indicator=SH.STA.BRTC.ZS

DATASET, CSV
https://elibrary.worldbank.org:443/action/showDataView?indicator=SH.DYN.MORT&download=csv
https://elibrary.worldbank.org:443/action/showDataView?indicator=SH.STA.BRTC.ZS&download=csv

ABSTRACT, HTML
https://elibrary.worldbank.org:443/doi/abs/10.1596/978-1-4648-1281-1_ch3
https://elibrary.worldbank.org:443/doi/abs/10.1093/wber/lhq018
https://elibrary.worldbank.org:443/doi/abs/10.1596/1020-797X_12_2_19
https://elibrary.worldbank.org:443/doi/book/10.1596/978-0-8213-9635-3
https://elibrary.worldbank.org:443/doi/abs/10.1596/9780821396353_CH02

BOOK PART, PDF (the ch extension restricts it to a pdf of the chapter only)
https://elibrary.worldbank.org:443/doi/pdf/10.1596/978-1-4648-1281-1_ch3
https://elibrary.worldbank.org:443/doi/pdf/10.1596/9780821396353_CH02

BOOK, PDF (without the ch extension, it shows the whole book)
https://elibrary.worldbank.org:443/doi/pdf/10.1596/978-1-4648-1281-1

ARTICLE, PDF
https://elibrary.worldbank.org:443/doi/pdf/10.1093/wber/lhq018
https://elibrary.worldbank.org:443/doi/pdf/10.1596/1020-797X_12_2_19

LOG:
[elibrary_worldbank.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/2275424/elibrary_worldbank.txt)

**Comment by lisahamlett** [comment]
Technically part of ProQuest, but since it has its own domains and link format, I am going to go ahead and write it separately.
