### ISSUE TITLE
EBLIB

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#97]
### Example:star::star: :

emory.eblib.com

### Priority: 
Medium

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
Nothing on AnalogIST or Trello.

Stanza:
https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/EBL

**Comment by lisahamlett** [comment]
This is now part of ProQuest and does not have its own domain anymore -- everything refers to ProQuest.
So, I am going to close this issue and add a note to the ProQuest issue.
