### ISSUE TITLE
Kanopy

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#98]
### Example:star::star: :

emory.kanopystreaming.com

www.kanopystreaming.com

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
https://login.proxy.library.emory.edu/login?qurl=https://www.kanopystreaming.com/

**Comment by lisahamlett** [comment]
The addresses in the log start with http://emory.kanopystreaming.com:80/
However, even through the proxy, the addresses look like this in the website and don't show in the log: http://emory.kanopystreaming.com/video/national-parks-episode-1-scripture-nature
When I add the :80, the website drops it.
Is this a proxy problem?

**Comment by lisahamlett** [comment]
Here's all I could get through the proxy:
[kanopylinks.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/1492859/kanopylinks.txt)

**Comment by eipeele** [comment]
I saw a pull request for this one was merged, is this parser complete?

**Comment by AGCooper** [comment]
Yes. And a pull request for it was also sent to ezpaarse project.
