### ISSUE TITLE
Faculty 1000

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/ezpaarse-platforms#99]
### Example:star::star: :
https://f1000.proxy.library.emory.edu/
https://f1000research-com.proxy.library.emory.edu/

Not listed in the A-Z list and the archives are at PubMed Central through discoverE.
However, WHSCL links directly to it in a few places, so we should go ahead and parse it:
http://health.library.emory.edu/resources/basic-sciences/literature.html

### Priority: 
High

### Subscriber (Library): 
Woodruff

**Comment by lisahamlett** [comment]
http://ang.couperin.org/platforms/54351948eb6fe80673615d90
https://trello.com/c/2CC7Udcv/112-f1000-faculty-of-1000

Stanza:
https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/F1000

**Comment by CB987** [comment]
DOMAINS
f1000.com
f1000research.com

SEARCH, HTML
https://f1000.com:443/prime/sections?keywords=rainbow+environment+forest&hp=2
https://f1000research.com:443/browse
https://f1000research.com:443/search?q=rainbow
https://f1000research.com:443/browse/slides?&selectedDomain=slides
https://f1000research.com:443/browse/f1000-faculty-reviews?&selectedDomain=f1000-faculty-reviews
https://f1000research.com:443/browse/documents?&selectedDomain=documents
https://blog.f1000.com:443/topics/open-data/
https://f1000.com:443/prime/recommendations/all?fieldsCriteria[0].fieldName=all&fieldsCriteria[0].operator=AND&fieldsCriteria[0].value=rainbow

TOC, HTML
https://f1000research.com:443/gateways/disease_outbreaks	
https://f1000research.com:443/gateways/bioconductor
https://f1000research.com:443/gateways/disease_outbreaks?selectedDomain=documents
https://f1000research.com:443/gateways/disease_outbreaks?selectedDomain=posters
https://f1000research.com:443/gateways/disease_outbreaks?selectedDomain=slides
https://f1000research.com:443/collections/BOSC
https://f1000research.com:443/collections/python
https://f1000research.com:443/collections/BOSC?selectedDomain=slides

REF, HTML
https://f1000research.com:443/collections/BOSC/about-this-collection
https://f1000research.com:443/posters/6-499


ARTICLE, HTML
https://blog.f1000.com:443/2019/04/25/malaria-past-and-present/
https://blog.f1000.com:443/2010/07/06/a-biologist-a-chemist-and-a-physicist-walk-into-a-bar/
https://blog.f1000.com:443/2019/04/04/fairsharing-where-to-look-when-you-dont-know-where-to-look/
https://blog.f1000.com:443/2019/03/26/failure-is-not-necessarily-bad-it-makes-you-tough-and-mature-scientifically/
https://f1000research.com:443/articles/7-208/v1
https://f1000research.com:443/articles/8-616/v1
https://f1000.com:443/prime/1028491
https://f1000research.com:443/documents/7-1444
https://f1000research.com:443/slides/7-636
https://f1000research.com:443/slides/8-586
https://f1000.com:443/prime/interaction/openarticle/735502654

ARTICLE, PDF
https://f1000research.com:443/stats-pmc/downloads-views?doi=10.12688%2Ff1000research.10851.1
https://f1000research.com:443/stats-pmc/downloads-views?doi=10.12688%2Ff1000research.18506.1
https://f1000research.com:443/stats-pmc/downloads-views?doi=10.12688%2Ff1000research.11622.2


[f1000_log.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3153996/f1000_log.txt)
